### ISSUE TITLE
Linking error - bitcode

### ISSUE THREAD

**Issue by mikach** [zendesk/zendesk_sdk_chat_ios#104]
Hello!

When I'm trying to archive app with ZDCChatAPI included I got an error:

```
bitcode bundle could not be generated because 'ZDCChatAPI.framework/ZDCChatAPI(ZDCMobileProvisionAnalyzer.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
```

ZDCChat version 1.3.0.1

**Comment by mikach** [comment]
And it looks like `ZDCOfflineMessageView.o` was also built without full bitcode.

**Comment by TofPlay** [comment]
Same issue

**Comment by StevenDiviney** [comment]
@TofPlay @mikach Thanks you for bringing this to our attention. We are investigating this now and working on a fix

**Comment by TofPlay** [comment]
@StevenDiviney do you have an estimation for the fix?

**Comment by StevenDiviney** [comment]
@TofPlay @mikach We have just released 1.3.0.2 to fix this issue.

**Comment by TofPlay** [comment]
@StevenDiviney 👍 🙂

**Comment by mikach** [comment]
`1.3.0.2` works for me, thank you!
