### ISSUE TITLE
Can't build using Bitcode flag v1.3.0.1

### ISSUE THREAD

**Issue by ynotski** [zendesk/zendesk_sdk_chat_ios#107]
Env variables:

ZDCChat SDK v1.3.0.1 installed via cocopods
Base iOS SDK iOS v9.3

After updating to the latest SDK, in order to fix the table view cell crash, I am no longer able to build with full bitcode support due to `ZDCChat.framework`

```ld: bitcode bundle could not be generated because '/.....ZDCChat.framework/ZDCChat(ZDCOfflineMessageView.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7 ```

Please can you provide a solution and a reason why it regressed from v1.2.0.1 which we previously, successfully built with full bitcode support  ?

Cheers,

Tony

**Comment by baz8080** [comment]
Hi Tony,

We have a `1.3.0.2` version with bitcode re-enabled. Thanks!

**Comment by ynotski** [comment]
@baz8080 Beautiful 👍
