### ISSUE TITLE
Chat doesn't initiate first time

### ISSUE THREAD

**Issue by ankit-bhardwaj** [zendesk/zendesk_sdk_chat_ios#11]
When i initiate chat for the first time in application it gave me this error

*** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]

while for the next time everything is working.

I checked your sample and go in the "Chat (Pre-set data)" same error came 

2015-08-04 18:49:07.967 Chat Sample[4021:102576] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]

Secondly tag are not coming

**Comment by grahamcruse** [comment]
Hi Ankit

Apologies for the slow response, can you confirm if this is still an issue for you in version 1.1?

Thanks

Graham

**Comment by ankit-bhardwaj** [comment]
Thanks Graham,

I have updated the SDK and now tags are updating correctly.

However once concern, please suggest if i am wrong ?
When i push department and tags. department only came when i initiate the chat. is it the correct behaviour?

Apart from that everything works fine.
Thanks 
Ankit

**Comment by grahamcruse** [comment]
Hi Ankit,

Good to hear that's fixed for you. The department behaviour is expected; the department has been set but it's not applicable until the visitor has sent a message and become an incoming chat.

Thanks
Graham
