### ISSUE TITLE
Change Chat title/other strings based on app conditions

### ISSUE THREAD

**Issue by jinnamohamed1** [zendesk/zendesk_sdk_chat_ios#110]
Hi 
Please let me know if there is any way to change the chat title based on certain conditions? Tried by changing "ios.ZDCChat.title" in ZDCChatStrings file. But could not change during run time based on some app functionality conditions.

**Comment by schlan** [comment]
Hi @jinnamohamed1, in the current version it's not possible to change the title during runtime. \
I'm going to mark this issue as closed, but feel free to create a feature request in our [community forum](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs).
