### ISSUE TITLE
ChatViewcontroller cannot navigate back when embeded navigation controller in a container view

### ISSUE THREAD

**Issue by daarkfish** [zendesk/zendesk_sdk_chat_ios#114]
I have a viewcontroller A which has a container view embedded a navigation controller to Viewcontroller B , when I call startChatIn in ViewControllerB it will be directed to the chatviewcontroller but when i click on the "Back" left navigation button , nothing has happen. It suppose to pop back to the previous screen. Same happen to end chat button.

**Comment by oarrabi** [comment]
Hello @daarkfish,

I tried to reproduce this in with a setup that looks like the attached image:
![screenshot](https://cloud.githubusercontent.com/assets/1461052/18952709/8a6c4a7a-8653-11e6-9a8e-1b53616f7401.png)

however, I was unable to reproduce it.

Would it be possible to elaborate more on the setup?
It would be great if you could share a sample app that reproduces the issue.

Thanks,
Omar...

**Comment by daarkfish** [comment]
I figured It's my mistake on my side. Thanks anyway.
