### ISSUE TITLE
Cannot set completion action on ZDCOfflineMessageHandler

### ISSUE THREAD

**Issue by dangochi** [zendesk/zendesk_sdk_chat_ios#117]
- SDK version: 1.3.2.1

It looks like the ZDCOfflineMessageAction property on ZDCOfflineMessageHandler was removed, yet the typedef for the completion block is still there, and the documentation on the init method still specifies there's an action block param when there isn't. 

It looks like this got removed between versions 1.2 and 1.3 of the SDK. I'm guessing it means it's no longer supported, but I was wondering if you're planning on bringing that back in the future?

**Comment by RonanMcH** [comment]
Hi @dangochi ,
The `ZDCOfflineMessageAction` typedef should have been deleted and the header documentation should have been updated. Thanks for pointing this out. There is currently no plans to bring it back if you would like to make a feature request for it, please post it on our [community](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs) forum.
Thanks,
Ronan.
