### ISSUE TITLE
Support another Languages 

### ISSUE THREAD

**Issue by AhmedShammala** [zendesk/zendesk_sdk_chat_ios#121]
hello ,
how i can support new Languages like Arabic language in Localization ?

**Comment by AhmedShammala** [comment]
+1

**Comment by RonanMcH** [comment]
Hi @AhmedShammala ,
Currently the Zendesk Chat SDK does not support Right to Left languages. It is on our road map for the future but I cannot provide a timeline for it currently.   
Thanks,
Ronan.

**Comment by AhmedShammala** [comment]
look leave  RTL thing to me and talk to me about strings now i change one file to ar and translate all strings there .
now how i can switch  language in app and Zendesk Chat Apply that without restart the app ?
i use this  

```
[[NSUserDefaults standardUserDefaults] setObject:[NSArray arrayWithObjects:@"ar", nil] forKey:@"AppleLanguages"];
[[NSUserDefaults standardUserDefaults] synchronize];
```

it's work Great But problem i need to restart app to apply the new language 

to be know i use this library for Switching languages [Language Manger](https://github.com/maximbilan/ios_language_manager)
when i use this library to switch language all app Switching Perfect Except this Library i need to restart the app to apply .

any thoughts or ideas i will be thankful .

**Comment by oarrabi** [comment]
Hello @AhmedShammala,

We designed the SDKs bundle to be loaded and cached when the application starts.
That`s why you need to restart the application in order for them to be picked up.

I don`t think its possible at the moment to change the language at runtime. It is also a use case that we won't be supporting anytime soon, sorry for that.

Thanks,
Omar...

**Comment by RonanMcH** [comment]
Hi @AhmedShammala,
I am going to tentatively close this issue. Please feel free to reopen it if you still have questions around translations.
Thanks,
Ronan

**Comment by dimohamdy** [comment]
@ronan-mch  how I can localize to Arabic ?

**Comment by dimohamdy** [comment]
@AhmedShammala  how you get the keys in localize file please share your solution?

**Comment by AhmedShammala** [comment]
@dimohamdy i rename one of this languages to "ar"

<img width="256" alt="screen shot 2018-03-18 at 9 32 20 am" src="https://user-images.githubusercontent.com/11911318/37563686-55fd6ee0-2a8f-11e8-9de6-7f8bd7dbe859.png">

**Comment by dimohamdy** [comment]
@AhmedShammala thanks for your fast response but I want to know, how you translate the text inside localize file?

**Comment by AhmedShammala** [comment]
@dimohamdy  ahmed i don't understand ,  you should open the file localizable. strings > Open as > ASCII List

and there change the values .

**Comment by dimohamdy** [comment]
@AhmedShammala  thank the trick is open as ASCII List

**Comment by AhmedShammala** [comment]
@rusdariusalex  Unfortunately NO .
