### ISSUE TITLE
App crashes when try to take photo from camera

### ISSUE THREAD

**Issue by mikach** [zendesk/zendesk_sdk_chat_ios#122]
- SDK version: 1.3.2.1
- Xcode version: 8
- iOS or Simulator: IOS
- iOS Version: 10

Steps to Reproduce:

1. Start chatting
2. Try take a photo from camera
3. App crashes

**Comment by RonanMcH** [comment]
Hi @mikach,
Have you included the `NSCameraUsageDescription` key with a description in your `info.plist` of your application? Please let us know if this fixes the issue or not.
Thanks,
Ronan.

**Comment by mikach** [comment]
@RonanMcH fixed now, thanks! Probably you need to add info about that key to getting started docs.
