### ISSUE TITLE
Change theme to dark

### ISSUE THREAD

**Issue by mikach** [zendesk/zendesk_sdk_chat_ios#124]
How can I change chat theme to dark?

**Comment by RonanMcH** [comment]
Hi @mikach ,
There are no out of the box themes with the Zendesk Chat SDK currently. The documentation for theming the UI is [here](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/customization#styling-your-chat-ui). 
Thanks,
Ronan

**Comment by mikach** [comment]
@RonanMcH can you give me an example how to apply dark theme? I looked at ZopimChatSample and didn't find how to apply the whole theme.

**Comment by RonanMcH** [comment]
Hi @mikach , 
I am afraid I can't provide you with a dark theme but can only point you in the right direction. The Chat SDK doesn't have a concept of a theme but instead has individual appearance selectors for each UI component. An implementation of all the available appearance selectors and how you use them is in the sample application in the [ChatStyling.m](https://github.com/zendesk/zendesk_sdk_chat_ios/blob/master/ZopimChatSample/ZopimChatSample/ChatStyling.m).
Regards,
Ronan.

**Comment by oarrabi** [comment]
Hello @mikach, 
I am going to close this issue for now, if this issue persists, or if you have any other question. Please dont hesitate to contact us :)
