### ISSUE TITLE
Please confirm - are those issues have been fixed in latest release?

### ISSUE THREAD

**Issue by EvgenyKarkan** [zendesk/zendesk_sdk_chat_ios#125]
Just a 'copy-paste' from https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/knownissues

`v1.3.0.1`

`- The bottom part of chat messages is clipped.` - what about this issue? 

I'm just asking.

**Comment by StevenDiviney** [comment]
@EvgenyKarkan this was fixed in 1.3.1.1. Are you still seeing it?

**Comment by EvgenyKarkan** [comment]
> Are you still seeing it?
On iOS 10 chat looks nice, no issues. Thanks.
