### ISSUE TITLE
creation of multiple chat windows

### ISSUE THREAD

**Issue by krgulshan** [zendesk/zendesk_sdk_chat_ios#126]
- SDK version:
- Xcode version: 8.0
- iOS or Simulator: 9+ 
- iOS Version: 9+
- Swift version: 3.0

Steps to Reproduce:

1.  I am using a side menu from where i am going to open the chat view controller. Then i specify the navigation controller and source view controller in a method for entering the chat screen . after all the required steps the chat screen opens . Everything works correctly till this step but after that when i go to my home screen from side menu and i try to open the chat screen, a new window of chat screen is opened i.e multiple windows for chat screen are getting created . i don,t want this functionality to happen . please help
![screen shot 2016-11-22 at 7 21 15 pm](https://cloud.githubusercontent.com/assets/23658302/20526172/ee353f16-b0e8-11e6-8cd9-4ea8198a49e9.png)

**Comment by tecknut** [comment]
@krgulshan thanks for reaching out to us. Can you give us a bit more information please?

The code snippet image is incomplete, and it's hard to determine what exactly is going on. 

What is `FSChatViewController`? 
Is this a subclass of `ZDCChatViewController` which you've created?

Thanks

**Comment by krgulshan** [comment]
@tecknut yes ,it is a subclass of ZDCChatViewController.

**Comment by tecknut** [comment]
Could you share this subclass? There may be something in this subclass which is causing this issue.

**Comment by krgulshan** [comment]
[FSChatViewStyling.swift.zip](https://github.com/zendesk/zendesk_sdk_chat_ios/files/608547/FSChatViewStyling.swift.zip)

**Comment by krgulshan** [comment]
[FSChatViewController.swift.zip](https://github.com/zendesk/zendesk_sdk_chat_ios/files/608551/FSChatViewController.swift.zip)

**Comment by tecknut** [comment]
The `FSChatViewController` is overriding these methods without calling super: 

```
override func viewWillAppear(_ animated: Bool) 
override func viewDidDisappear(_ animated: Bool) 
override func viewWillDisappear(_ animated: Bool)
```

This may be causing the issue you're seeing, but I can't be sure just yet. 

Can you try out something?

Could you try set up a new black view controller object in your storyboard and set the class type to `ZDCChatViewController`? Give that an identifier and try to instantiate it from your slider menu. 

If you're able to do this and the issue still persists, then the issue is has nothing to do with your subclass. And at that point we can start looking at some other possible causes.

**Comment by krgulshan** [comment]
okay i will try this and tell you if something happens.

thanks

**Comment by krgulshan** [comment]
@tecknut thanks for your help. i have fixed the issue and i got to know that issue was in creating multiple objects from my side-menu. That was why multiple windows were getting created.

Thanks again for being concerned with me .

**Comment by tecknut** [comment]
No problem! Thanks for reaching out to us, we're glad you've managed to get it working. 

Let us know if you encounter any further issues.
