### ISSUE TITLE
Hide "Leve a message " Button !

### ISSUE THREAD

**Issue by AhmedShammala** [zendesk/zendesk_sdk_chat_ios#127]
i Search a lot to find this , Can you help me ?

**Comment by mathewcropper** [comment]
Hi. Is this what you're looking for? https://help.zendesk.com/hc/en-us/articles/229137567-Hide-the-Leave-a-message-button-in-the-Chat-SDK

**Comment by AhmedShammala** [comment]
Yes , Exactly Thanks man

**Comment by AhmedShammala** [comment]
@mathewcropper  This works fine until i tested in ios 10

`[[UIButton appearanceWhenContainedIn:[ZDCLoadingErrorView class], nil] setHidden:YES];`

this line make app Crashing in iOS 10  there is any another solution ?
Thanks

**Comment by StevenDiviney** [comment]
@AhmedShammala I am unable to replicate this, could you please show us the crash logs?

**Comment by tecknut** [comment]
Hey @AhmedShammala, we haven't heard back from you. 

Are you still having this issue?

**Comment by AhmedShammala** [comment]
Yes , Still Make Crash and not Detected in Simulator

**Comment by tecknut** [comment]
Can you provide us with some crash logs?

**Comment by oarrabi** [comment]
@AhmedShammala I will be closing this one now. Please feel free to reopen it if it still persists.
