### ISSUE TITLE
ZDK Add Attachment Simulator Crash

### ISSUE THREAD

**Issue by dmiluski** [zendesk/zendesk_sdk_chat_ios#128]
- SDK version: Zendesk Mobile SDK for iOS 1.7.6.1
- Xcode version: Xcode 8.2 Beta
- iOS or Simulator: Simulator
- iOS Version: iOS10
- Swift version: 2.3

Steps to Reproduce:

1. While in simulator, attempt to TakePhoto -> Crash

![screen shot 2016-12-01 at 5 27 31 pm](https://cloud.githubusercontent.com/assets/5083390/20819802/a1622c76-b7eb-11e6-807a-4c5ba47ec621.png)
![screen shot 2016-12-01 at 5 27 34 pm](https://cloud.githubusercontent.com/assets/5083390/20819818/be51d35e-b7eb-11e6-8d3a-86314a1efa3a.png)

Expectation:
Either don't show the photo option, or handle gracefully.

**Comment by tecknut** [comment]
Hi @dmiluski, this is the repo for our Chat SDK. 

However this is something we're aware of on our Mobile SDK. 

Thanks
