### ISSUE TITLE
Chat Queueing Status Updates?

### ISSUE THREAD

**Issue by dmiluski** [zendesk/zendesk_sdk_chat_ios#129]
- SDK version:
Zendesk Mobile SDK for iOS 1.7.6.1
Zendesk SDK Chat for iOS 1.3.2.1

- Xcode version:
Xcode 8.1

- iOS or Simulator:
Both

- iOS Version:
iOS 10

- Swift version:
2.3
Steps to Reproduce:

1. Visit Chat
2. Note estimate provided
3. Information is never updated between entry and first contact

Expectation:
A user should continuously get feedback  of their place/wait in line.

![screen shot 2016-12-06 at 10 44 43 am](https://cloud.githubusercontent.com/assets/5083390/20939105/5f34ee78-bba2-11e6-945d-25d564854b5a.png)

**Comment by mathewcropper** [comment]
Hey @dmiluski. This is a feature of the Chat product itself, and the Chat SDK simply displays it. The SDK doesn't control the logic, I'm afraid, so this is working as expected. There's a thread [here](https://chat.zendesk.com/hc/en-us/community/posts/218565348-Queue-doesn-t-update) talking about this exact feature request, where Ramin, the Product Manager, commented. I'd suggest adding your voice to that thread and going from there.

For now, I'll close this issue as a feature request.
