### ISSUE TITLE
Can't submit to AppStore when building with Xcode 7

### ISSUE THREAD

**Issue by amykhajlyshyn** [zendesk/zendesk_sdk_chat_ios#13]
ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/XXX.app/ZDCChat.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/XXX.app/ZDCChatStrings.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

ERROR ITMS-90542: "Invalid CFBundleSupportedPlatforms value. The key 'CFBundleSupportedPlatforms' in the Info.plist file in bundle 'Payload/XXX.app/ZDCChat.bundle' contains an invalid value '( "iPhoneSimulator" )'. Consider removing the CFBundleSupportedPlatforms key from the Info.plist. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

ERROR ITMS-90542: "Invalid CFBundleSupportedPlatforms value. The key 'CFBundleSupportedPlatforms' in the Info.plist file in bundle 'Payload/XXX.app/ZDCChatStrings.bundle' contains an invalid value '( "iPhoneSimulator" )'. Consider removing the CFBundleSupportedPlatforms key from the Info.plist. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

**Comment by erdincakkaya** [comment]
any updates? I have the same issue.

**Comment by iurichiba** [comment]
I encountered this error on Friday.
I just removed the keys, as the error says, and it worked just fine!

**Comment by amykhajlyshyn** [comment]
Yes, I removed these keys too, but I use CocoaPods, and it would be great to have this issue fixed in repo :)

**Comment by iurichiba** [comment]
I agree, hope they work this out soon! It's an easy fix.

**Comment by erdincakkaya** [comment]
it worked, thank you guys.

**Comment by ttime0227** [comment]
I'm new to xcode. Could someone explain how I remove these keys. Any help would be greatly appreciated! Screen shots would be great.

**Comment by grahamcruse** [comment]
Hi all,

Apologies for the delay; we were preparing the latest version of the SDK in which you should find this issue resolved. (1.1).

Thanks

Graham

**Comment by mishug** [comment]
ERROR ITMS-90542: "Invalid CFBundleSupportedPlatforms value

I am trying to upload a .ipa file to app store and I was getting the error 'CFBundleSupportedPlatforms' in the Info.plist iPhoneSimulator.

I have resolve this error. You need to update the GoogleMaps.bundle and GMSCoreResources.bundle info.plist. 

CFBundleSupportedPlatforms = {
    "iPhoneSimulator"
},

Replace with iPhoneSimulator to iPhoneOS

CFBundleSupportedPlatforms = {
    "iPhoneOS"
},

**Comment by khasimsk** [comment]
its worked . Thank you :)

**Comment by fulldecent** [comment]
Has anybody reported this issue upstream?
