### ISSUE TITLE
Change navigation bar tint doesn't change the navigation controller title color

### ISSUE THREAD

**Issue by jackalcool** [zendesk/zendesk_sdk_chat_ios#130]
- SDK version: 1.3.2.1
- Xcode version: 8.0
- iOS or Simulator: iOS 10
- iOS Version: 10
- Swift version: 2.3

I'm changing the navigationBar appearance using this code

      let navigationBar = self.navigationController?.navigationBar
      navigationBar?.barTintColor = UIColor.greenColor()
      navigationBar?.translucent = false
      navigationBar?.tintColor = UIColor.whiteColor()

And it's working for all the elements except for the title that still remains black. How the title color of a navigation controller can be changed overriding the default ZDCChat behaviour?

![bartint](https://cloud.githubusercontent.com/assets/23527242/21347323/63f62bf0-c6a8-11e6-80a5-e314f10f0173.jpg)

**Comment by RonanMcH** [comment]
HI @jackalcool ,
You should be able to change the appearance attributes of the navigation bar using the standard appearance selectors. Here are some examples:
```
UINavigationBar.appearance().backgroundColor = UIColor.green
UINavigationBar.appearance().tintColor = UIColor.red
let attrs = [
      NSForegroundColorAttributeName: UIColor.red
]
UINavigationBar.appearance().titleTextAttributes = attrs
```
Hope this helps,
Ronan.

**Comment by jackalcool** [comment]
My bad, I was missing the titleTextAttributes property! It worked indeed

**Comment by User2004** [comment]
[Click here](https://webappcodes.com/set-navigation-bar-theme-in-objective-c) for set navigation bar tint color, background color, font family, font color etc.
