### ISSUE TITLE
Change color of rating buttons UIImageViews

### ISSUE THREAD

**Issue by loryhuz** [zendesk/zendesk_sdk_chat_ios#136]
Actually I didn't see a possibility to change color of images contained in ratings buttons.

It's seems that we can recreate the buttons from scratch with these properties:
```swift
    /**
     * Button for sendiung a bad chat rating.
     */
    open var badRatingButton: UIButton!

    
    /**
     * Button for sendiung a good chat rating.
     */
    open var goodRatingButton: UIButton!
```

But the current buttons are cool, would be nice to allow color customization on them.

I tried the following but it had no effects:
```swift
ZDCRatingCell.appearance().tintColor = UIColor.white
```

**Comment by mathewcropper** [comment]
Hi @loryhuz. Thanks for the feedback! The best place to post feature requests is in the [Zendesk SDKs community](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs), as it gives your idea a wider audience and generally has a more interesting discussion. I'd recommend posting there, and I'll close this issue.
