### ISSUE TITLE
Crashing while try to send a photo.

### ISSUE THREAD

**Issue by ajumalebrahim** [zendesk/zendesk_sdk_chat_ios#139]
- SDK version:1.3.2.1
- Xcode version:8
- iOS or Simulator:iOS
- iOS Version:10
- Swift version:NA

Steps to Reproduce:

1. Open chat.
2. Click on camera icon.
3. Click "Take photo".

**Comment by RonanMcH** [comment]
Hi @ajumalebrahim ,
Have you added the `NSCameraUsageDescription` key to your applications `info.plist`? This is a new rule brought in by apple that you must have this key in your application to allow it to access the camera. Let me know if this fixes your issue!
Thanks,
Ronan.

**Comment by oarrabi** [comment]
Hello @ajumalebrahim we haven't heard from you in a while. Can you please let us know if you tried the suggestion above?
