### ISSUE TITLE
Issue adding Note to chat or visitor +  adding email to visitor

### ISSUE THREAD

**Issue by jregnauld** [zendesk/zendesk_sdk_chat_ios#140]
Hi,

I found an issue with your SDK :( and it would be lovely if you could fix it! :D

If we try to add a note like "blablabla Jon's Doe issue" or "blabla\\\\blabla", nothing goes wrong with the iOS SDK, but the note is never added to the chat...  but it would be great if the SDK returns an error.

ZDCChatAPI: 

- setNote
- appendNote

ZDCVisitorInfo:

- addNote

About ZDCVisitorInfo.email, if I set a string which is not an email. It doesn't go to the chat and it makes sense, but it would be great if the SDK returns an error.

- SDK version: 1.3.2.1
- Xcode version:8
- iOS or Simulator:iOS
- iOS Version:10
- Swift version: 3

Thanks!

**Comment by mathewcropper** [comment]
Hi @jregnauld. Thanks for reporting this!

Are you using [this](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/chat#adding-a-note-to-a-chat) to set the note?

ZDCChat.updateVisitor { user in
    user?.phone = "0123456789"
    user?.name = "Jane Doe"
    user?.email = "jdoe@example.com"
    user?.addNote("This is a Swift note")
}

If so, would you mind enabling logging and sharing the output with us? Instructions on how to enable the Chat SDK's logging are [here](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/advancedtopics#logging).

**Comment by jregnauld** [comment]
Hi @mathewcropper, 
Thanks for your quickly reply!

So I tried with : 

```
- ZDCChatAPI.instance().setNote
- ZDCChatAPI.instance().appendNote
- ZDCChatAPI.instance().visitorInfo. addNote
```
but also with: 
```
ZDCChat.updateVisitor { user in
    user?.phone = "0123456789"
    user?.name = "Jane Doe"
    user?.email = "jdoe@example.com"
    user?.addNote(#my_note_to_the_agent)
}
```
name and email are ok, but still missing the note. :(

I setup the log since the beginning: in debug, verbose and error , but I got nothing in the console :(
The note  has "\n", "'", "£", "/" characters if it helps.

**Comment by oarrabi** [comment]
Hello @jregnauld,

At the moment its not possible to use `\n` `"` and `'` as a note string.
I created an issue locally in our bug tracking system to fix this issue. I will keep this GitHub issue open and will update you when this has been fixed.

Sorry for the inconvenience.

Thanks,

**Comment by jregnauld** [comment]
Hi @oarrabi,

Thank you for letting me know!

No worries, I hope that's not too hard to fix ;)

Cheers

**Comment by jregnauld** [comment]
Quick question @oarrabi,

Is there any work around with note to work with these characters by any chance?

Also I would like to know if I use appendNote to for every '\n". Is there is a "queue concept" or would it be a API call every time that I use appendNote?
example: 5 "\n" will create . 5 API call or just one?

Cheers!

**Comment by StevenDiviney** [comment]
@jregnauld there is no concept of a request queue in the SDK, API calls are made immediately. 

We have fixed the issue but I can't give a timeline for a release at the moment, sorry.

**Comment by StevenDiviney** [comment]
@jregnauld We have released a new version of the Chat SDK. Can you confirm it fixes your issue?

**Comment by jregnauld** [comment]
@StevenDiviney I just tested and it works like a charm!
Good job!
Thanks :)

**Comment by schlan** [comment]
Hi @jregnauld , I'll tentatively close this issue. If you run into any more issues, feel free to let us know in an new issue.

**Comment by jregnauld** [comment]
@schlan yes I will do! Thanks again for your help!
