### ISSUE TITLE
linker warning when building with XCode8.0 or greater

### ISSUE THREAD

**Issue by jaz-ah** [zendesk/zendesk_sdk_chat_ios#142]
SDK version: - ZDCChat (1.3.2.1):
ZDCChat/API (= 1.3.2.1)
ZDCChat/Localization (= 1.3.2.1)
ZDCChat/UI (= 1.3.2.1)
ZDCChat/API (1.3.2.1)
ZDCChat/Localization (1.3.2.1)
ZDCChat/UI (1.3.2.1):
ZDCChat/API
Xcode version: 8.0, 8.1 or 8.2 (Beta)
iOS or Simulator: 10.0 / 10.1 / 10.2 simulator
iOS Version: 10.0 / 10.1 / 10.2 simulator
Swift version: 3.0
Steps to Reproduce:

Just build an application with the zendesk sdk using cocoapods with the above versions, will get the linker warning:
ld: warning: Some object files have incompatible Objective-C category definitions. Some category metadata may be lost. All files containing Objective-C categories should be built using the same compiler.
I have broken this down and limited it to a test application with just the zendesk sdk. It looks like the zendesk sdk is probably built w/ XCode7.x and we are getting this compatibility warning.

This was fixed recently in the zendesk sdk - see issue: https://github.com/zendesk/zendesk_sdk_ios/issues/256#issuecomment-282493473

**Comment by baz8080** [comment]
@jaz-ah Thanks for the report. I have created an issue on our side for this. We don't have a release planned at the moment, but we'll consider this issue when we do.

**Comment by jaz-ah** [comment]
np - any chance you could produce a beta release for this one?  doesn't have to be official but unfortunately this linker warning throws our stats in our Xcode bot off so i'm looking for some way around this other than disabling the chat sdk

**Comment by StevenDiviney** [comment]
@jaz-ah We are planning to release Chat SDK by the end of the month. Hopefully this will solve your issue.

However, I am unable to replicate this locally. Can you attach the test application you mentioned?

**Comment by StevenDiviney** [comment]
@jaz-ah We have released a new version of Chat SDK. Can you confirm it fixes you issue please?

**Comment by jaz-ah** [comment]
yes confirmed fixes the issue - thanks!
