### ISSUE TITLE
Links on system triggered messages is not clickable.

### ISSUE THREAD

**Issue by capecrawler** [zendesk/zendesk_sdk_chat_ios#145]
- SDK version: 1.3.3.1
- Xcode version: 8.2.1
- iOS or Simulator: Device
- iOS Version: 10.2.1
- Swift version:

Steps to Reproduce:

1. Create a system triggered message with a link from the zendesk/zopim account.
2. When the system message with a link was triggered and received in the app, the link is not clickable.

* Through some digging, system triggered messages uses `ZDCSystemTriggerCell` and contains UIlabel for rendering the message. It would be better to use `ZDUTextView` instead to support links.

**Comment by StevenDiviney** [comment]
@capecrawler 

Thanks for the suggestion. I have added it to our backlog.

**Comment by baz8080** [comment]
I'm going to close this one for now. We have this tracked internally. We now take [feature requests in our forum](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs) rather than on Github.
