### ISSUE TITLE
Message EditText/TextField to far from keyboard

### ISSUE THREAD

**Issue by fenli** [zendesk/zendesk_sdk_chat_ios#147]
Message EditText/TextField to far from keyboard (keyboard pushed up message list)
(see attached for details)

- SDK version: 1.3.4.1
- Xcode version: 8.2.1
- iOS or Simulator: iPhone 6Plus
- iOS Version: 10.2.1
- Swift version: 2.3

Steps to Reproduce:

1. Launch chat forms (fill in email, name, dept, etc)
2. Click next and go to chat message page
3. tap Message Edittext

![img_0016](https://cloud.githubusercontent.com/assets/5110285/25078984/72255cfc-2362-11e7-8ea9-5f22c127b171.png)

**Comment by StevenDiviney** [comment]
@fenli I am unable to replicate this. 

What is that accessory view you have above the keyboard? Is it a framework or your own code? It is more than likely responsible for the behaviour you are seeing.

**Comment by niwinnm** [comment]
@fenli - I guess you're using IQKeyboardManager in your project. You need to add selector to receive notification for Chat loaded & unloaded and activate & deactivate `[IQKeyboardManager sharedManager].enable` and `[IQKeyboardManager sharedManager].enableAutoToolbar`accordingly.

@StevenDiviney - Try installing IQKeyboardManager pod in your sample project and try it out. It would be great if you could add support for it by default.

**Comment by tecknut** [comment]
@niwinnm Thanks for your suggestion, this is probably the best option at the moment. 

We've installed IQKeyboardManager in our sample apps and are aware of the issue. We can't commit to making IQKeyboardManager supported by default. But it's on our radar.

@fenli Can you try @niwinnm suggestion and get back to us?

**Comment by niwinnm** [comment]
Sure. Do keep this thread posted if you add this option in future.

**Comment by baz8080** [comment]
I'm going to close this one for now. We have this tracked internally. We now take [feature requests in our forum](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs) rather than on GitHub.
