### ISSUE TITLE
Repeatedly submit offline messages, name \ email is not updated

### ISSUE THREAD

**Issue by heyanyan** [zendesk/zendesk_sdk_chat_ios#148]
- SDK version:1.3.4.1
- Xcode version:8.0
- iOS or Simulator:iPhone 6s
- iOS Version:10.0
- Swift version:objective-c
Steps to Reproduce:

1. Send an offline message
2.Enter name\ email \ offline message
3.submit 
4.Submit offline again
5.Input different  name\ email \ offline message
6. Submitted successfully
7.View ticket customer service system to view user information
8.The name and email
<img width="487" alt="2017-05-04 5 51 32" src="https://cloud.githubusercontent.com/assets/7297266/25698730/a21b4d20-30f2-11e7-8b4e-deae2b80e3ca.png">
<img width="487" alt="2017-05-04 5 49 46" src="https://cloud.githubusercontent.com/assets/7297266/25698748/b12f33f8-30f2-11e7-874f-f53d53783340.png">
<img width="834" alt="2017-05-04 5 53 06" src="https://cloud.githubusercontent.com/assets/7297266/25698749/b13dbd1a-30f2-11e7-84ae-f7674b996b53.png">

 are the first to submit

**Comment by schlan** [comment]
Hey @heyanyan thanks for reporting this issue. I'm gonna mark this issue as duplicate as it was already reported in https://github.com/zendesk/zendesk_sdk_chat_ios/issues/118.
