### ISSUE TITLE
Widget button not showing

### ISSUE THREAD

**Issue by ibankstory** [zendesk/zendesk_sdk_chat_ios#149]
- SDK version: 1.3.4.1
- Xcode version: 8.2
- iOS or Simulator: iPhone and Simulator
- iOS Version: iOS9, iOS10
- Swift version: 3.0

Steps to Reproduce:

1. Open Chat
2. press back button

the widget button should be appear on the screen if haven't end chat yet

**Comment by tecknut** [comment]
@ibankstory I've just tried this with our Sample app and I'm unable to replicate the issue. Can you provide more context please?

**Comment by baz8080** [comment]
I'm closing this for now. If you still need help, then please reopen the issue.
