### ISSUE TITLE
Dismissing full screen image in chat pops to pre-chat controller

### ISSUE THREAD

**Issue by kyleh415** [zendesk/zendesk_sdk_chat_ios#150]
If you have a chat open as a user and are sent an image and tap that image to open it in full screen, tapping the image again to dismiss it pops you back to the pre-chat view controller instead of the chat view controller.

- SDK version: 1.3.4.1
- Xcode version: 8.3.3
- iOS or Simulator: iOS
- iOS Version: iOS 9, 10
- Swift version: 3.1

Steps to Reproduce:

1. Open a chat
2. Receive an image
3. Open the image
4. Tap the image to dismiss

**Comment by danthedrummer** [comment]
Hi @kyleh415,

I can't seem to reproduce this issue on a test device. Can you provide us with the code you are using to start the chat and the logs for when the bug happens. 

This page explains how to enable logging: https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/advancedtopics 

Cheers,
Dan

**Comment by kyleh415** [comment]
Hi Dan, 

I turned on logging -- I'll paste the log here, but there doesn't seem to be any logs relevant to the issue (nothing like, 'Opening image' or something like that. It was just simply:

2017-06-27 17:19:17.622971+0200 Brok Debug[10008:4942279] [INFO]: Sending chat message
2017-06-27 17:20:13.859671+0200 Brok Debug[10008:4942279] [DEBUG]: File download completed
2017-06-27 17:20:31.526158+0200 Brok Debug[10008:4942279] [INFO]: Sending chat message

During these logs, I was repeatedly opening the image and tapping it and then pressing 'Start chat' again and pushing to the chat, over and over. Each time the full-size image viewController is tapped to dismiss, it seems the navigationController has popped to root. Here's the relevant code to starting a chat, from a viewController inside of a navigationController inside of a tab bar:

@IBAction func buttonPressed(_ sender: Any) {
        ZDCChat.start(in: self.navigationController, withConfig: nil)
    }

Thanks,
Kyle

**Comment by tecknut** [comment]
Hi @kyleh415, we're going to look further into this. In the mean time can you try to reproduce this in our sample app, so far we've been unable to. 

Thanks

**Comment by kyleh415** [comment]
I admit that it works in the sample application. However, in my app I'm not doing anything strange -- I'm using normal UIViewControllers and a vanilla UINavigationController. The only difference I can see is that everything in mine is embedded in a TabBarController as well as I'm hiding the chat overlay in my ChatStying file. If I start the chat modally instead of in a navigation controller, everything works as expected. I'm at a real loss here.

Thanks,
Kyle

**Comment by divo** [comment]
@kyleh415 

I cannot reproduce this issue. Would you be able to re-create the issue in a sample project and send it to us?

Thanks

**Comment by kyleh415** [comment]
Try this: https://github.com/kyleh415/zenTest

-Kyle

**Comment by divo** [comment]
@kyleh415 Thank you for sending us the sample project, it explains the issue very succinctly. 
The issue is the way we present and dismiss the image view (i.e. incorrectly, we use the view controller at the top of the navigation hierarchy instead of the chat view controller)

I have opened an issue for us to track this internally.

In the mean time can you try `ZDCChat.start()`? This will present the Chat modally. It does not seem to be affected by this issue.

**Comment by kyleh415** [comment]
Sorry guys, I figured out the issue and it wasn't your fault at all. You can see that I'm setting up everything in the tabBarController in viewWillAppear instead of viewDidLoad for some reason -- so whenever the tabBar appears, everything gets reset. Good news is, my boss says I'm only going to get 10 lashes.
