### ISSUE TITLE
ZDChat user identity persists between logins 

### ISSUE THREAD

**Issue by acoroian** [zendesk/zendesk_sdk_chat_ios#151]
- SDK version: 10.3
- Xcode version: 8.3
- iOS or Simulator: both
- iOS Version: 10.3
- Swift version: 3.1

Steps to Reproduce:

1. ZDChat.updateVisitor 
2. Chat
3. Notice chat started with new user
4 On same device ZDChat.udpateVIsitor with a new user
5 Notice chat name, email was changed for the old chat instead of creating a new chat.

Maybe this is more of a feature request then an issue?
I want to be able to reset the device identity if i log in with a different user to the app.

**Comment by danthedrummer** [comment]
Hi @acoroian. 

This is a known issue with how we integrate with Chat. Unfortunately we don't have a timeline for when this issue will be resolved. I'm going to close this issue as it is the same issue as https://github.com/zendesk/zendesk_sdk_chat_ios/issues/131.

Cheers,
Dan.
