### ISSUE TITLE
Navigation issue

### ISSUE THREAD

**Issue by rsahu34** [zendesk/zendesk_sdk_chat_ios#153]
- SDK version: 1.3.4.1
- Xcode version: 8.2.1
- iOS or Simulator: Both
- iOS Version: 10.2.1
- Swift version: 2.3

Steps to Reproduce:

1. When clicked back button from Chat screen its back to previous screen and automatically present the chat ViewController again.

**Comment by nsomar** [comment]
Hello @rsahu34,

Can you please share the snippet of code you are using to present the chat screen?

**Comment by baz8080** [comment]
I'm closing this for now. If you still need help, then please reopen the issue.
