### ISSUE TITLE
setNote() doesn't appear to be working

### ISSUE THREAD

**Issue by HaikuOezu** [zendesk/zendesk_sdk_chat_ios#154]
Hi,
I'm trying to re-assign the notes for the user every time a chat starts but I'm not being very successful at it.

I tried using the following
```
ZDCChat.instance().api.setNote("Test note 2")
ZDCChatAPI.instance().setNote("Test note")
```

They sometimes seem to work, so I figured it's because I'm calling it before the chat is done proper, so I added an observer as such

```
ZDCChatAPI.instance().addObserver(self, forConnectionEvents: #selector(TransactionsViewController.chatConnected))
ZDCChat.start(in: self.navigationController, withConfig: nil)
```

And put the previous code inside chatConnected, but unfortunately my observer only gets called once when the chat in in its uninitialized phase (very much like in in issue #105 

Of course doing

```
ZDCChat.updateVisitor { user in
    user?.addNote("Prova \(arc4random())")
}
```
It actually works, but it keeps adding onto the notes in the Dashboard and I'd like to only have the one note all the time, generated automatically from the app.
How can I properly figure out when a ZDCChat is connected and set the note then without having to roll out my own chat with ZDCChatAPI calls?

**Comment by nsomar** [comment]
Hello @HaikuOezu,

Calling `ZDCChat.instance().api.setNote` inside the connection callback works correctly. This is what I'm doing.

I am calling `addObserver` from a button event
```swift
ZDCChatAPI.instance().addObserver(self, forConnectionEvents: #selector(chatConnected(sender:)))
````

I then set the note using the following code

```swift
  @objc func chatConnected(sender: AnyObject) {
    ZDCChat.instance().api.setNote("XXXX")
  }
```

Is this not working in your case?

**Comment by HaikuOezu** [comment]
Hi @nsomar !
Unfortunately like I mentioned in the OP my connection callback gets called only once and returns the chat state to be "uninitialized" and is never called again...
I tried having setNote in the block anyway but it doesn't work (probably because the chat session is not connected yet.

Right now I'm using a terrible workaround where I wait one second before calling setNote but of course that's bound to fail if the connection isn't established quickly.

**Comment by divo** [comment]
@HaikuOezu We are unable to replicate this issue, connection events arrive correctly for the entire life of a chat.

Would you be able to reproduce the issue in a sample project and send it to us?

Is TransactionsViewController the view controller you are presenting the chat from?

**Comment by HaikuOezu** [comment]
@divo that's correct, TransactionsViewController is the UIViewController doing the calls
I whipped up a test project and I'm not seeing the issue either but I'm still getting it on the proper app, I thought it could maybe be because I'm calling it from a GCD async block but I moved the code to a simple IBAction for UIBarButtonItem and I'm still seeing the same behavior.

**Comment by tecknut** [comment]
@HaikuOezu have you been able to pinpoint the difference between your sample and main app?

**Comment by HaikuOezu** [comment]
@tecknut unfortunately I have no clue as to what's different between the two apps :(
I guess the only thing that comes to mind is that while the sample app is just a simple UIViewController the actual app is a UIViewController inside a UINavigationController inside a UItabBarController, I will maybe try to replicate this condition in the sample app to see wether that has something to do with it or not
