### ISSUE TITLE
outbound messages appear in a white blank box

### ISSUE THREAD

**Issue by chrischen-melb** [zendesk/zendesk_sdk_chat_ios#155]
- SDK version: 1.3.4.1
- Xcode version: 8.3.3
- iOS or Simulator: iPhone 6s, as well as Simulator
- iOS Version: 10.3.2
- Swift version: Objective-C

Steps to Reproduce:

1. follow the integration guide
2. start chat without config
3. incoming messages are okay, but outbound messages look like this
[screenshot](https://d26dzxoao6i3hh.cloudfront.net/items/0n1Y3z3M3Q0a392n2C28/IMG_1153.PNG?v=b1d2cdf4)

**Comment by nsomar** [comment]
Hello @chrischen-melb,

It appears that the text color of the `ZDCVisitorChatCell` is set to white.
Can you please try to change to any other color by adding this line

```swift
ZDCVisitorChatCell.appearance().textColor = UIColor.red
```

Let me know if that solves the issue

**Comment by chrischen-melb** [comment]
@nsomar thanks, customizing ZDCVisitorChatCell UIApperance solves the issue.
