### ISSUE TITLE
trackEvent only work at first time @ iPhone 5 10.2.1 (14D27)

### ISSUE THREAD

**Issue by pts011080** [zendesk/zendesk_sdk_chat_ios#158]
- SDK version: 1.3.2.1  & 1.3.4.1
- Xcode version: 8.3.2 (8E2002)
- iOS or Simulator: iPhone 5 (Device & Simulator)
- iOS Version: 10.2.1 (14D27)
- Swift version: -

Steps to Reproduce:
1. Start the chat when user press customised chat button.
[ZDCChat startChatIn:self.navigationController withConfig:nil];

2. Would like to send some detail data for agent to read.
[[ZDCChat instance].api trackEvent:@"User call at - Page 1"];
and the agent can read the message "User call at - Page 1" at the conversation panel and "Visitor Path" section

3. User leave conversation page with back button at top left.

4. User press the chat button again. The Chat  was start, but no any message was appear at agent's conversation panel and "Visitor Path" section.
Not only get in and out at same page, even user go to other pages, the conversation panel and "Visitor Path" can only show the first "trackEvent" message.

Note: it works from iPhone 5S or above devices

**Comment by RonanMcH** [comment]
Hi @pts011080 ,
We have been able to reproduce this locally.
Thanks for reporting it,
Ronan.

**Comment by baz8080** [comment]
Hi @pts011080 
I wanted to give you an update on this. We’re working on other bug reports based on their priority, so can’t give an ETA on a resolution for this specific issue.

**Comment by baz8080** [comment]
Hi @pts011080 We're not going to patch this in V1 of the SDK, but we do have the issue tracked internally, and we'll ensure that it works in Chat SDK V2, which is in active development. Closing the issue.
