### ISSUE TITLE
Observer when unreadMessagesCount is updated

### ISSUE THREAD

**Issue by lucianocn** [zendesk/zendesk_sdk_chat_ios#159]
What's the observer to watch unreadMessagesCount?

```objective-c
- (void)viewDidLoad
{
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(updateUnreadCount) name:UnreadConversationCountDidChangeNotification** object:nil];

    [self updateUnreadCount];
}

- (void)updateUnreadCount
{
    NSInteger unreadConversationCount = [[ZDCChat instance] unreadMessagesCount];
    NSLog(@"%ld", (long)unreadConversationCount);
}
```

**Comment by tecknut** [comment]
Hi @lucianocn our docs describe a number of events which are sent during chats, [this may be what you're looking for](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/sessionapi#chat-log-events). 

Can you describe the use case your trying to solve for?

**Comment by lucianocn** [comment]
I'm implementing Zopim iOS SDK and I need to catch unread messages count outside the chat.
If the user is using my app and receive a message I would like to alert him (and it is also good to send a push when he is answered).

Is there any way to do this?

**Comment by nsomar** [comment]
Hello @lucianocn,

In order to get the chat events (and the updated number of unread messages) you need to register to the chat log events by using:

```
ZDCChatAPI.instance().addObserver(self, forChatLogEvents: #selector(chatEvent(_:)))

// and remember to remove the observers before object deallocation
ZDCChatAPI.instance().removeObserver(forChatLogEvents: self)
```
You can read more about it here https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/sessionapi#chat-log-events

As for the push notification, sadly we don't support that in the Chat SDK yet.

Can you try the to use the snippet above please?

Thanks...

**Comment by baz8080** [comment]
I'm going to close this one for now, let us know if you'd like more help!

**Comment by hinduasish** [comment]
Hello,

I have looked through the api and Chat event for seeing the unread messages. Could any help me with this? I would like to capture the unread messages count.

Thanks
