### ISSUE TITLE
[Bug] Layout

### ISSUE THREAD

**Issue by lucianocn** [zendesk/zendesk_sdk_chat_ios#160]
- SDK version: 1.3.5.1
- Xcode version: 8.3.2 (8E2002)
- iOS or Simulator: iPhone 7 (real device)
- iOS Version: 10.3.3

1. Open Chat
```objective-c
#import <ZendeskSDK/ZendeskSDK.h>

@interface ViewController () <ZDKHelpCenterConversationsUIDelegate>
@end

@implementation ViewController

- (IBAction)btnChat:(id)sender
{
    [ZDCChat startChat:^(ZDCConfig *config) {
        config.emailTranscriptAction = ZDCEmailTranscriptActionNeverSend;
    }];
}

#pragma mark - ZDKHelpCenterConversationsUIDelegate
- (ZDKNavBarConversationsUIType)navBarConversationsUIType
{
    return ZDKNavBarConversationsUITypeNone;
}

- (ZDKContactUsVisibility)active
{
    return ZDKContactUsVisibilityOff;
}

- (UIImage *)conversationsBarButtonImage
{
    return [UIImage imageNamed:@"conversations_image"];
}

@end

```

---------------------

![2](https://user-images.githubusercontent.com/3828136/29140651-9e868438-7d21-11e7-8fc1-1efa5d032e3d.jpg)  ![1](https://user-images.githubusercontent.com/3828136/29140656-a19b2106-7d21-11e7-8551-c91c74685c86.jpg)

**Comment by tecknut** [comment]
@lucianocn Did you mean to open this on the chat repo? The code snippet you sent is from the support SDK.

**Comment by baz8080** [comment]
I'm going to close this for now as we haven't heard back. If the issue is persisting, then please open an issue on the [Support repo](https://github.com/zendesk/zendesk_sdk_ios/issues/new). Thanks!
