### ISSUE TITLE
Tapping the attachment button in Zendesk grays out the screen and does not prompt you to attach anything if the keyboard is displayed.

### ISSUE THREAD

**Issue by rhaining** [zendesk/zendesk_sdk_chat_ios#162]
- SDK version: 1.3.2.1
- Xcode version: Xcode 8.3
- iOS or Simulator: iOS
- iOS Version: iOS 11
- Swift version: 3.1

Steps to Reproduce:

1. Tap: New 
2. Enter some description text. 
3. Tap the paper-clip icon to attach something.
4. You are not prompted to attach anything because the prompt is covered by the keyboard.

![img_19cf7a3ff7bc-1](https://user-images.githubusercontent.com/462870/29338164-104886ec-81e2-11e7-838f-00168704a1fb.jpeg)

**Comment by rhaining** [comment]
@baz8080 thanks! do you have an ETA on the iOS 11 patch?

**Comment by brendan-fahy** [comment]
@rhaining No ETA just yet. We're working on it, and we'll have it released as soon as we can.

**Comment by rhaining** [comment]
thanks @brendan-fahy!

**Comment by rhaining** [comment]
@brendan-fahy is there any update on this? thanks!

**Comment by RonanMcH** [comment]
Hi @rhaining, 
This issue is fixed in the Zendesk SupportSDK with our new release version 1.11.0.1, which your screenshot is showing. This is the repo for the Zendesk ChatSDK which has not yet had a release for updates and bugs in iOS 11.  Which are you asking about?
Thanks,
Ronan.

**Comment by baz8080** [comment]
@rhaining I'm going to close this one as it was a support sdk issue that was fixed in a recent patch
