### ISSUE TITLE
Template images are not being tinted

### ISSUE THREAD

**Issue by matmartinez** [zendesk/zendesk_sdk_chat_ios#164]
Hey there,

We're trying to customize some buttons in the chat UI. We're using plain and simple **template images**  from an asset catalog. They actually show up on the interface, but with **no tint color**. 

Images are set to "Render As: Template Image" on the asset catalog.

Just for the record, image names are provided with an appearance proxy for the `ZDCChatUI` and `ZDCTextEntryView` classes, as **unfortunately there's not an option** to just pass `UIImage` objects with an `.alwaysTemplate` rendering mode.

*Pardon my ~~French~~ Objective-C:*

```
ZDCChatUI *chatUI = [ZDCChatUI appearance];
chatUI.backChatButtonImage = @"MinimizeBarButton";
chatUI.endChatButtonImage = @"EndConversationBarButton";
        
ZDCTextEntryView *textEntry = [ZDCTextEntryView appearance];
textEntry.sendButtonImage = @"SendBarButton";
```

- SDK version: ZDCChat (1.3.6.1)
- Xcode version: Version 8.3.3 (8E3004b)
- iOS or Simulator: iOS 10.3 Simulator and device
- iOS Version: iOS 10.3
- Swift version: N/A

Steps to Reproduce:

1. Set custom image names from an asset catalog using an appearance proxy for the `ZDCChatUI` and `ZDCTextEntryView` classes.
2. Images are not tinted in any way.

**Comment by RonanMcH** [comment]
Hi @matmartinez ,
I am afraid this is how we handle images in the ChatSDK and we have no plans to change it currently on our roadmap. We have a [SDK product feedback forum](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-Developer-Mobile-SDKs) where customers can post feature requests and vote on them. Our product manager keeps a regular eye on this and takes it into account for our roadmap. 
Thanks,
Ronan.

**Comment by matmartinez** [comment]
Hi @RonanMcH !

Well, that sucks. I really thought it was a bug. We've been tinting images for how many years now? iOS 7 has been around forever, and it's *so common* to use template images for buttons, bar buttons, etc. Anyways, I made a post [here](https://support.zendesk.com/hc/en-us/community/posts/115008774728-Template-images-are-not-being-tinted).

*"We have no plans to change it currently on our roadmap"* doesn't work for us, and probably doesn't work for many of your clients running into the same issue.


## Workaround:

Here's a simple category that solves this issue with swizzling:

```
@interface ZDCChatViewController (ZDCChatViewControllerPrivateBarButtons)

- (UIBarButtonItem *)backButton;
- (UIBarButtonItem *)endButton;

@end

@implementation ZDCChatViewController (SPAppearanceWorkaroundForWeHaveNoPlansToChangeItCurrentlyOnOurRoadmapAnswer)

+ (void)load
{
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        SPSwizzleInstanceMethod(self, @selector(viewDidLoad), @selector(SP_viewDidLoad));
    });
}

- (void)SP_applyWorkaroundForBarButton:(UIBarButtonItem *)barButton
{
    if ([barButton isKindOfClass:[UIBarButtonItem class]]) {
        barButton.image = [barButton.image imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate];
    }
}

- (void)SP_viewDidLoad
{
    [self SP_viewDidLoad];
    
    if ([self respondsToSelector:@selector(backButton)]) {
        [self SP_applyWorkaroundForBarButton:[self backButton]];
    }
    
    if ([self respondsToSelector:@selector(endButton)]) {
        [self SP_applyWorkaroundForBarButton:[self endButton]];
    }
}

@end
```

Hope this helps,
Matías.

_PS: Really, really dissatisfied with this Zendesk._
