### ISSUE TITLE
Can we have the floating widget for Zendesk Chat IOS SDK by default

### ISSUE THREAD

**Issue by hinduasish** [zendesk/zendesk_sdk_chat_ios#166]
Hello,

Maybe this is more of a feature request rather than an issue, sorry if this is the wrong place I apologize but I was wondering if it is possible to have the Zendesk floating widget that occurs after you send a message to an agent to be there by default. We want to have the widget for support always floating on the app, rather then them select it from a menu or button. Please let me know

**Comment by schlan** [comment]
Hi @hinduasish at the moment the floating widget of the Chat SDK doesn't support that. 
We collect feature requests in the [Zendesk SDKs community](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs) 

I can't give you any promises if and when it will be implemented. There's also the option of reimplementing the widget with the features you want. For integrating it with Chat SDK have a look at our APIs ([documentation](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/sessionapi)).

I'm gonna close this issue, feel free to re-open or creating a new one if you have any further questions. Thanks,
Sebastian
