### ISSUE TITLE
iOS UI Issue: TEXT scrolls and not fit in the container

### ISSUE THREAD

**Issue by iossolutions** [zendesk/zendesk_sdk_chat_ios#167]
I am facing a issue with the text view height, when user scrolls up or down then the text scrolls up and down in the container and text seems cut from above or down.
<img width="375" alt="img_841d7887e49a-2" src="https://user-images.githubusercontent.com/5277297/31122444-8678d3d8-a859-11e7-9034-09e395173a95.png">

- SDK version: 1.3.6.1
- Xcode version: Version 9.0 (9A235)
- iOS or Simulator: iPhone 6
- iOS Version: 11
- Swift version: objective c

Steps to Reproduce:

1.  chat with any guy and scrolls up and down
2.
How can I fix this any suggestion?

**Comment by baz8080** [comment]
@iossolutions I can't replicate this with our sample application. Can you share any more information, such as any styling code that you have specified?

**Comment by RonanMcH** [comment]
Hi @iossolutions ,
Since we haven't heard from you in a while, I am going to tentatively close this issue. Feel free to reopen if this is still an issue for you!
Thanks,
Ronan.
