### ISSUE TITLE
Get UnreadMessageCount when ChatOverlay is disabled

### ISSUE THREAD

**Issue by hinduasish** [zendesk/zendesk_sdk_chat_ios#168]
Hello,

I am trying to get the unread message count because I am not using the ChatOverlay but am using my own custom widget. I have gone through the documentation for the API usage but do not understand how to track when the messages come in are unread. I have read some things about tracking when the Chat Overlay opens and closes but I cannot find any more information on this and am having trouble incorporating this. Any help on this would be greatly appreciated. BTW I am using swift 3.

Thanks,
Asish Mehta

**Comment by RonanMcH** [comment]
HI @hinduasish ,
you can register for chat events using the code [here](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/sessionapi#chat-log-events) and listen for `ZDCChatEventTypeAgentMessage` events. If the user is not on the `ZDCChatViewController`, then these would be unread messages and you could increment your unread message count.
Hope this helps,
Ronan.

**Comment by hinduasish** [comment]
okay, i am going to try to implement this and tell you how it goes

**Comment by RonanMcH** [comment]
Hi @hinduasish ,
Did this solution work for you?
Thanks,
Ronan.

**Comment by hinduasish** [comment]
Yes it did, thank you for your help. Much appreciated

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
