### ISSUE TITLE
UI issue- iOS 11 Chat Table view leaves some space at the beginning and starting the chat

### ISSUE THREAD

**Issue by christiygag** [zendesk/zendesk_sdk_chat_ios#169]
- SDK version:1.3.6.1
- Xcode version:9.0
- iOS or Simulator:iOS
- iOS Version:11
- Swift version:Objective C

Steps to Reproduce:

1. Show chat UI using present view controller. When we start a new chat the cells are not starting from the top of the screen. Working fine in iOS10 and below.

![img_bc4831d25ec0-1](https://user-images.githubusercontent.com/20677361/31170913-f5fe98c2-a90e-11e7-9bc2-50e4b1274556.jpeg)
![img_4692](https://user-images.githubusercontent.com/20677361/31170918-fa543ff8-a90e-11e7-95a7-8d025b5595ff.PNG)

**Comment by RonanMcH** [comment]
Hi @christiygag ,
I have been able to reproduce this issue in our sample app. I have created an internal ticket to track this issue.
Thanks for reporting it,
Ronan.

**Comment by divo** [comment]
@christiygag we just released 1.3.7.1. It should fix this issue

**Comment by divo** [comment]
@christiygag did the release fix your issue?

**Comment by christiygag** [comment]
Yes..issue got fixed in 1.3.7.1
