### ISSUE TITLE
Crashing on iOS 9 when pressing/holding on link in chat

### ISSUE THREAD

**Issue by dangochi** [zendesk/zendesk_sdk_chat_ios#17]
If I simply tap on a link in a chat bubble, it seems to do the expected behavior (link opens), but if I press and hold on the link, I get the below stack trace. 

It seems to work fine on iOS 8, but it crashes on iOS 9 on both device and simulator. I get this error in both 1.0 and 1.1 versions of the SDK.

	2015-10-07 15:13:32.998 Schnettgoecke_Dev[15040:4144864] *** Assertion failure in -[UITextView startInteractionWithLinkAtPoint:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3505.16/UITextView_LinkInteraction.m:377
	2015-10-07 15:13:33.003 Schnettgoecke_Dev[15040:4144864] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: ''
	*** First throw call stack:
	(
		0   CoreFoundation                      0x0000000109fb4f65 __exceptionPreprocess + 165
		1   libobjc.A.dylib                     0x00000001097b4deb objc_exception_throw + 48
		2   CoreFoundation                      0x0000000109fb4dca +[NSException raise:format:arguments:] + 106
		3   Foundation                          0x000000010665fae2 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
		4   UIKit                               0x00000001078e3af0 -[UITextView(LinkInteraction) startInteractionWithLinkAtPoint:] + 204
		5   UIKit                               0x00000001073cf2dd -[UITextInteractionAssistant(UITextInteractionAssistant_Internal) smallDelayRecognizer:] + 580
		6   UIKit                               0x00000001073bdb40 _UIGestureRecognizerSendTargetActions + 153
		7   UIKit                               0x00000001073ba6af _UIGestureRecognizerSendActions + 162
		8   UIKit                               0x00000001073b8f01 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 822
		9   UIKit                               0x00000001073c03f3 ___UIGestureRecognizerUpdate_block_invoke809 + 79
		10  UIKit                               0x00000001073c0291 _UIGestureRecognizerRemoveObjectsFromArrayAndApplyBlocks + 342
		11  UIKit                               0x00000001073b1eb4 _UIGestureRecognizerUpdate + 2624
		12  CoreFoundation                      0x0000000109ee09d7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
		13  CoreFoundation                      0x0000000109ee0947 __CFRunLoopDoObservers + 391
		14  CoreFoundation                      0x0000000109ed659b __CFRunLoopRun + 1147
		15  CoreFoundation                      0x0000000109ed5e98 CFRunLoopRunSpecific + 488
		16  GraphicsServices                    0x000000010bb64ad2 GSEventRunModal + 161
		17  UIKit                               0x0000000106f01676 UIApplicationMain + 171
		18  Schnettgoecke_Dev                       0x0000000104ddf3af main + 111
		19  libdyld.dylib                       0x000000010a7f292d start + 1

**Comment by dangochi** [comment]
I tried running this on the sample application and ran into the issue there as well. I attached a gif that hopefully clearly shows the steps to reproduce.

![zopim crasher](https://cloud.githubusercontent.com/assets/1784093/10354305/b4a1cbbc-6d13-11e5-81b1-70a70873aa48.gif)

**Comment by grahamcruse** [comment]
@dangochi thanks for reporting this. On research it looks like this is a fundamental iOS 9 bug and as yet we have found no real options to correct this behaviour. There are a number of posts around this issue:

http://stackoverflow.com/questions/32653268/error-on-textview-with-detection-phone-number-ios-9
https://forums.developer.apple.com/thread/19480
https://plus.google.com/113638495836374068475/posts/VcXcN4C534f

and I have narrowed down some of the details:

 - only occurs when the view controller is presented modally
 - after the first long press if the screen is then rotated then the modal view controller vanishes and the expected alert view appears, after this the entire navigation structure has been damaged and can result in some very unpredictable results including http://cl.ly/image/282l0B0o0d2a and an effective zombie of the vanished modal view controller running around which is not deallocated

It appears that while the rest of the view/navigation controller hierarchy is solid, when the OS attempts to present the alert view for the UITextView url options from a modal view it actively breaks something resulting in an inconsistent navigation state.

**Comment by dangochi** [comment]
Thanks @grahamcruse, I found some of that same information after logging this issue. 

I was using ```[ZDCChat startChat]```, but it turns out I don't need to have this presented modally, so I've since switched to ```[ZDCChat startChatIn:self.navigationController withConfig:nil]``` which solves this issue for me.

Thanks again!

**Comment by grahamcruse** [comment]
@dangochi that does solve the initial presentation, though I'm afraid it will still be an issue if the visitor minimises the chat and resumes it since that defaults to modal presentation. I'll be leaving this issue open to track where we are with Apple pushing a fix, lets hope it's not one of those bugs they decide isn't important and hangs around for 2 major versions...

**Comment by dangochi** [comment]
After starting the chat, I do ```[[ZDCChat instance].overlay setEnabled:NO]``` to get around the issue of being able to present modally. I know that's not ideal for everyone, but I just wanted to throw that out there in case anyone else comes across this issue and doesn't need the minimized chat overlay.

**Comment by baz8080** [comment]
@dangochi I'm going to close this one for now, but thanks for reporting the issue.
