### ISSUE TITLE
Don't display Connection lost alert if ZDChat wasn't started

### ISSUE THREAD

**Issue by matibzurovski** [zendesk/zendesk_sdk_chat_ios#170]
- SDK version: 1.3.2.1
- Xcode version: 9
- iOS or Simulator: iPhone 6 Simulator
- iOS Version: 11
- Swift version: 3.2

Steps to Reproduce:

1. Open the app (without starting a Zendesk chat)
2. Loose connection
3. I get the following alert displayed:
![screen shot 2017-10-06 at 11 37 50](https://user-images.githubusercontent.com/9628833/31273346-7ea75ed6-aa8e-11e7-9cb8-6a529e005d8a.png)

*******

I am getting this alert displayed out of nowhere on my app, even though a chat has never been started. This is pretty annoying, as I handle the no connection scenario myself, so showing this alert breaks such flow.

I can confirm that the alert is displayed even without calling `ZDCChat.start(in:withConfig:)`. However, I am calling the following method when the app starts (as I set up the appearance of the chat in case its gets displayed), which may be related with the issue:
```Swift
ZDCChat.instance().overlay.setEnabled(false)
```

I would like to know if there is a way of disabling this alert being shown. If my guess is correct (and the alert is only displayed because I call `ZDCChat.instance()` before opening a chat), I could execute this logic only if a chat is started. However, I haven't find any documentation confirming my hypothesis.

**Comment by tecknut** [comment]
Hi @matibzurovski 

You should be able to set appearance properties with out calling `ZDCChat.instance().overlay.setEnabled(false)` 

[See our docs](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/customization#styling-your-chat-ui) which describe how to do this. 

For the alert that is getting displayed. It is presented by `ZDCChatUI`. Do you have any code referencing this?

Could you share some code snippets of your integration? Your styling, and any other preamble code would be helpful. Additionally any code you use to display any UI component would be great. 

Thank you,
Alan

**Comment by matibzurovski** [comment]
Hi @tecknut, sorry for my late response, I was out for vacations.

I don't really get how we can hide the chat overlay without calling that precise line. It is in fact the one described in the [docs](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/customization#hiding-the-chat-overlay)

**Comment by matibzurovski** [comment]
Regarding my integration code, this is how set up and show the chat on our app.

```Swift
// AppDelegate.swift

func application(_ application: UIApplication,
                     didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {

    // Initialize chat
    ZDCChat.initialize(withAccountKey: "OUR_ACCOUNT_KEY")
    ZDCChat.start({ (config) in
        config?.emailTranscriptAction = ZDCEmailTranscriptAction.neverSend
    })

    // Style the chat appearence
    ZDCChatView.appearance().chatBackgroundColor = ColorPalette.baseWhite
    
    // Style visitor chat cell
    ZDCVisitorChatCell.appearance().bubbleBorderColor = ColorPalette.actionBlue
    ZDCVisitorChatCell.appearance().bubbleColor = ColorPalette.actionBlue
    ZDCVisitorChatCell.appearance().bubbleCornerRadius = 10
    ZDCVisitorChatCell.appearance().textColor = ColorPalette.baseWhite

    // Hide overlay
    ZDCChat.instance().overlay.setEnabled(false)

}

// HelpViewController.swift

func openZendeskChat() {
    // Start the chat 
    ZDCChat.start(in: navigationController, withConfig: nil)
}
```

The `HelpViewController` is a class of our project that has a button which triggers the action of opening the chat. We don't want the chat to be displayed and started until the user taps such button. 

However, I am guessing the line to hide the overlay (which is always run as it is part of the `AppDelegate`)  is the one that somehow starts the chat. Then, if the user looses connection, he gets the alert displayed even if he never tapped the button to open a chat.

If my assumption is correct, we can move the styling code to the `HelpViewController`, so the chat is only styled if it will be open. But as I mention on my first post, I have no guaranty that this will fix the issue, so I wanted to ask you first.

**Comment by divo** [comment]
@matibzurovski It looks like you are starting a chat inside your app delegate. Can you remove this and instead configure the chat inside `HelpViewController`?

**Comment by matibzurovski** [comment]
@divo I cannot believe I didn't notice the `ZDChat.start` invoked on the `AppDelegate` 🤦‍♂️ 

I am not sure though if I should now call the `startChat:` and `startChatIn:withConfig:` methods on the `HelpViewController`, or only with the second one would work. In other words, which of the following options should I follow.

**Option A**
```Swift
// AppDelegate.swift
func application(_ application: UIApplication,
                     didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {

    // Initialize chat
    ZDCChat.initialize(withAccountKey: "OUR_ACCOUNT_KEY")
    
    // Hide overlay
    ZDCChat.instance().overlay.setEnabled(false)

}

// HelpViewController.swift
func openZendeskChat() {
    // Start the chat 
    ZDCChat.start({ (config) in
        config?.emailTranscriptAction = ZDCEmailTranscriptAction.neverSend
    })
    ZDCChat.start(in: navigationController, withConfig: nil)
}
```

**Option B**
```Swift
// AppDelegate.swift
func application(_ application: UIApplication,
                     didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {

    // Initialize chat
    ZDCChat.initialize(withAccountKey: "OUR_ACCOUNT_KEY")
    
    // Hide overlay
    ZDCChat.instance().overlay.setEnabled(false)

}

// HelpViewController.swift
func openZendeskChat() {
    // Start the chat 
    ZDCChat.start(in: navigationController, withConfig: { config in
        config?.emailTranscriptAction = ZDCEmailTranscriptAction.neverSend
    })
}
```

**Comment by baz8080** [comment]
@matibzurovski Option B is what you need. Option A is starting the chat twice, which will not do what you need. Thanks!
