### ISSUE TITLE
User cannot open pdf attachment sent by agent

### ISSUE THREAD

**Issue by zaitsevyan** [zendesk/zendesk_sdk_chat_ios#171]
- SDK version: 1.3.6.1
- Xcode version: 8
- iOS or Simulator: Both
- iOS Version: 10.3 & iOS 11 
- Swift version: Objective C

Steps to Reproduce:

1. Agent send pdf attachment
2. User see message with attachment but cannot open it

![simulator screen shot 10 oct 2017 at 18 43 35](https://user-images.githubusercontent.com/498965/31399026-2e204f08-adeb-11e7-9323-8771c70238c6.png)

![simulator screen shot 10 oct 2017 at 18 19 12](https://user-images.githubusercontent.com/498965/31399055-3fc6ad2e-adeb-11e7-9b6f-74933848449a.png)

How I can solve this issue?

**Comment by divo** [comment]
@zaitsevyan PDFs are simply opened inside a webview. Can you confirm if you can read the same documents outside of the SDK?

**Comment by zaitsevyan** [comment]
@divo Yes, I can open pdf on my device.
Additional information: ZDChatViewController is embedded in my custom view controller to add this custom header and another things, so ZDChatViewController does not have access to self.navigationController (it is always nil). How do you present webview? 
![zendesk chat-trim](https://user-images.githubusercontent.com/498965/31582900-4044765c-b190-11e7-936c-651af06ed17e.gif)

**Comment by zaitsevyan** [comment]
I have disassemble and debug your library. Why do you looking for navigationController using this strange flow?
You are calling method [ZDCChatUI viewDocumentForEvent:], which calling for ZDCChatViewController.topViewController
This helper method ZDUViewController.topViewController calling [UIApplication sharedApplication].keyWindow.rootViewController.navigationController
Why do you think, that rootViewController is always embedded by UINavigationController?
I swizzle few methods to solve my problem with attachment...

**Comment by RonanMcH** [comment]
Hi @zaitsevyan ,
I have clarified this as a bug and I have a filed an internal ticket to keep track of it.   
Thanks,
Ronan.

**Comment by divo** [comment]
Closing this as it's tracked in a ticket and is not an issue within the SDK.
