### ISSUE TITLE
Apple Match-O Linker Error ___isOSVersionAtLeast

### ISSUE THREAD

**Issue by Samback** [zendesk/zendesk_sdk_chat_ios#174]
- SDK version:
1.3.7.1
- Xcode version:
8.3.3
- iOS or Simulator:
10.3
- Swift version:
3

Steps to Reproduce:
After update to the latest version from 
`1.3.6.1` to `1.3.7.1` I've faced with an issue

http://prntscr.com/h4t9fg

**Comment by divo** [comment]
@Samback can you try using XCode 9? In order to support iOS 11 and the iPhone X fully we need to use the latest version of the iOS SDK. This is why you are getting an undefined symbol in XCode 8.

**Comment by divo** [comment]
@Samback did this fix your issue?

**Comment by Samback** [comment]
@divo  Yes, I change my version back to `1.3.6.1` and now it works. For this moment I can't use Xcode 9 that's why I downgrade to the previous version. Probably you can mention this fact at rede me and it will help other users.

Regards,
Max

**Comment by baz8080** [comment]
@Samback We've added this information to our [release notes](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/releasenotes#version-1.3.7.1), which is linked to from the README. Thanks for your feedback!
