### ISSUE TITLE
iOS chat offset fix for iOS 11 causes prior iOS versions to have first message be under navigation bar.

### ISSUE THREAD

**Issue by Genhain** [zendesk/zendesk_sdk_chat_ios#175]
- SDK version: 1.3.7.1
- Xcode version: ~> 9.0
- iOS or Simulator: both
- iOS Version: 9.3
- Swift version: 4

Steps to Reproduce:

1. Start a chat
2. Send a message
3. Can't see first message if its only one line, if it's long enough you will see it under than navigation bar

I believe the fix for #169 has produced this issue.

**Comment by baz8080** [comment]
@Genhain I wasn't able to reproduce this using our Sample application. Can you elaborate on how you're seeing this issue please?

![screen shot 2017-11-06 at 15 13 04](https://user-images.githubusercontent.com/1534413/32447850-2523d6ca-c305-11e7-9194-e8ee084e897b.png)

**Comment by baz8080** [comment]
I'm going to close the issue as we haven't heard back. Feel free to reopen if you're having the issue still.

**Comment by Genhain** [comment]
@baz8080 I may do, unfortunately been working on urgent hotfixes and havent had time to revisit this issue, but thanks for taking the time.

**Comment by Genhain** [comment]
@baz8080 Here Are some screens of what i was talking about iOS 11 seems fine, anything else...not so much. on the first screen the first field for the name is behind the nav bar and in the chat itself my first message of hello is again under the nav bar.

[here is how i initialise it](https://gist.github.com/Genhain/0a24345237820535c585a1da3849ed31)

![When first starting a chat](https://user-images.githubusercontent.com/2082208/33054372-cc808710-ceb3-11e7-8dda-e105e57b8bb5.png)

<img width="477" alt="screen shot 2017-11-21 at 12 01 27 pm" src="https://user-images.githubusercontent.com/2082208/33054392-dee5012e-ceb3-11e7-8c34-03df719df2bb.png">
