### ISSUE TITLE
Background Colour Doesn't Extend Fully To Bottom

### ISSUE THREAD

**Issue by jstheoriginal** [zendesk/zendesk_sdk_chat_ios#180]
- SDK version: 1.3.7.1
- Xcode version: 9.1
- iOS or Simulator: iPhone X
- iOS Version: 11.1
- Swift version: 3.2

On iPhone X, the appearance background colours on the offline message view and loading view are not currently extending all of the way down to the safe area view/bottom layout guide.

Steps to Reproduce:

1. Have Zendesk Chat embedded in a navigation controller that is inside a custom tab bar controller or not inside of a custom tab bar controller.
2. Customize the background colour appearance of the offline message view and loading view. The colour doesn't extend all the way down like it should. The other screens seem to work as expected. 

![simulator screen shot - iphone x - 2017-12-03 at 21 37 20](https://user-images.githubusercontent.com/5117473/33535633-57b12690-d874-11e7-8545-eb4f7acf36f8.png)
![simulator screen shot - iphone x - 2017-12-03 at 21 03 28](https://user-images.githubusercontent.com/5117473/33535634-58fc5b32-d874-11e7-8012-4c5ccd91c0a4.png)

**Comment by jstheoriginal** [comment]
This is also an issue on an iPhone 5s running iOS 9.3. So not isolated to iPhone X.

**Comment by jstheoriginal** [comment]
Perhaps there is a way to apply a colour to the root view controller’s view? I checked in reveal and the zen desk VC does extend all the way down to the bottom like it should...it’s the subviews that are inserting and those are what I’ve added the background colour to via the appearance API.

**Comment by divo** [comment]
@jstheoriginal Have you tried `[[ZDCChatUI appearance] setChatBackgroundColor:];`?

**Comment by jstheoriginal** [comment]
@divo yes that's set 

ZDCChatUI.appearance().backgroundColor = .offWhite

**Comment by divo** [comment]
@jstheoriginal 'setChatBackgroundColor' is a different call. In Swift I guess it would be `chatBackgroundColor'

**Comment by jstheoriginal** [comment]
These are the only available colors:

<img width="343" alt="screen shot 2017-12-07 at 10 52 44 am" src="https://user-images.githubusercontent.com/5117473/33727141-d35af170-db3c-11e7-8602-8cd70efa9a82.png">

**Comment by divo** [comment]
https://github.com/zendesk/zendesk_sdk_chat_ios/blob/master/ZDCChat.framework/Headers/ZDCChatUI.h#L113

`ZDCChatUI.appearance().chatBackgroundColor = UIColor.red` is working for me in a Sample integration.

**Comment by jstheoriginal** [comment]
That's really strange. Swift doesn't think it's exposed properly, but if I use it still, it does build and fixes the issue.

Perhaps those properties aren't being exposed correctly to the appearance() instance? None of the ones in the linked file are showing up as accessible.

<img width="517" alt="screen shot 2017-12-07 at 11 19 48 am" src="https://user-images.githubusercontent.com/5117473/33728730-f08a73a2-db40-11e7-894e-2bd4be29d676.png">

**Comment by divo** [comment]
I'm seeing that too. CodeSense won't pick them up but I can CMD click and see them in the headers just fine.

I'll leave this issue open for now.

**Comment by divo** [comment]
Quick update, I'm also seeing this when setting the appearance of UIKit components. Fairly sure it's a bug in XCode.

**Comment by jstheoriginal** [comment]
Since there's a solution, I'll close this.
