### ISSUE TITLE
avatarUrl always nil for AgentEventType

### ISSUE THREAD

**Issue by TanelTeemusk** [zendesk/zendesk_sdk_chat_ios#183]
- SDK version:
1.3.7.1
- Xcode version: 9.2
- iOS or Simulator: iOS 10.0, simulator and device
- iOS Version: 10.0
- Swift version: 4

Steps to Reproduce:

1. make instance of ZendeskChatAPIClient 
2. define client.eventUpdated and client.eventReceived blocks
3. add this in each block:
`if let event = event as? AgentEventType {
                print("event url: \(event.avatarURL)")
            }`
4. Whenever agent sends a message it prints: "event url: nil" in the console
Tried to set avatar repeatedly in the browser zendesk dashboard but this variable still nil

**Comment by RonanMcH** [comment]
Hi @TanelTeemusk ,
I wasn't able to reproduce your issue. I was able to retrieve the `avatarUrl` using the following code:
```
 ZDCChatAPI.instance().addObserver(self, forAgentEvents: #selector(onAgentEvent))
    @objc func onAgentEvent() {
        let agents = ZDCChatAPI.instance().agents
        guard let agent = agents?.first?.value else {
            return
        }
        let avatarUrl = agent.avatarURL
    }
```
Let us know if this solves your issue. 
Thanks,
Ronan.

**Comment by TanelTeemusk** [comment]
Yup it did solve the problem for me too, but this does not populate AgentEventType with this url. 
I think it should also populate the struct conforming to this protocol, as it's somewhat misleading to have avatarURL in the AgentEventType and always nil. This struct is the most logical place where developers would be looking it for. Don't you think?

**Comment by eepDev** [comment]
Hi @TanelTeemusk,

You're right, a nil avatar in an event is misleading and causes confusion.
We're planning on doing work on Chat later this year and will ensure to address this inconsistency. Until then, I'm afraid you're stuck with the solution Ronan suggested above.

Thanks for reporting this.
Elvis

**Comment by baz8080** [comment]
I'm going to close this issue. We have this tracked internally for regression testing when we're doing Chat SDK V2.
