### ISSUE TITLE
Need to add ZDCChat into private pod project

### ISSUE THREAD

**Issue by Barbatosso** [zendesk/zendesk_sdk_chat_ios#185]
- Xcode version: 9.2
- iOS Version:  11.0
- Swift version: 4.0

Hello, we need to add your framework into our private pod project. But when we trying to add as dependency we have an error: 
`target has transitive dependencies that include static binaries: (.../Example/Pods/ZDCChat/ZDCChatAPI.framework and .../Example/Pods/ZDCChat/ZDCChat.framework)`. 
And Xcode doesn't allow directly adding framework into project.

Can you help us to resolve this problem?

**Comment by tecknut** [comment]
@Barbatosso what version of cocoapods are you using?

**Comment by Barbatosso** [comment]
1.4.0

**Comment by divo** [comment]
@Barbatosso this seems to be a Cocoapods issue. Can you try the workaround [posted here](https://github.com/CocoaPods/CocoaPods/issues/3289#issuecomment-313726321) ?

**Comment by baz8080** [comment]
@Barbatosso I'm going to close the issue. If the workaround in the link Divo provided does not work, then please get back in touch.
