### ISSUE TITLE
Not able to change the navigation bar title.

### ISSUE THREAD

**Issue by selvaraj-t2s** [zendesk/zendesk_sdk_chat_ios#186]
SDK version: ZDCChat (1.3.7.1)
Xcode version: Xcode9
iOS or Simulator: Device
iOS Version: 11
Swift version: 3

Doubt:
Is it possible to change the navigation bar title on the chat page?

**Comment by tecknut** [comment]
Hi @selvaraj-t2s thanks for your question. Generally these issues are intended for raising bugs/crashes and general issues with the SDK. We have a [community forum](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-Developer-Mobile-SDKs) which can be a good place to get answers on general questions. 
We also have documentation which outlines most of the integration details needed for basic and custom integrations.

[This might be what you're looking for.](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/customization#strings-and-localization) 

Thanks
