### ISSUE TITLE
Attachment action sheet hidden behind keyboard in iOS 9

### ISSUE THREAD

**Issue by dangochi** [zendesk/zendesk_sdk_chat_ios#19]
If the keyboard is shown in the chat view controller and you tap the photo attachment button, the action sheet for the photo options is hidden behind the keyboard. If the keyboard is hidden/dismissed and you tap the photo button, you can see the action sheet just fine.

This seems to work on iOS 8, so I'm guessing this is another thing Apple broke with 9. I'm curious if dismissing the keyboard before presenting the action sheet would be a viable solution, though?

Below are some screenshots from the sample app, one with the keyboard hidden and another with the keyboard shown.

![action sheet hidden](https://cloud.githubusercontent.com/assets/1784093/10405408/89bc2c46-6e8d-11e5-86b9-e34cd84bf8ea.png)
![keyboard dismissed](https://cloud.githubusercontent.com/assets/1784093/10405407/89bc3c9a-6e8d-11e5-9886-30f6e52131e4.png)

**Comment by grahamcruse** [comment]
@dangochi yep also spotted this today, and the simple solution is to resign the keyboard when the attach button is tapped. This will go out in the next patch.

**Comment by tecknut** [comment]
@dangochi Just checking in. Has this issue been solved for you?

**Comment by dangochi** [comment]
@tecknut I can't get this to work in my app due to the issue I'm seeing in #35, but I tested this in the sample app and it's resigning the keyboard when tapping the attach button now, so I think this can be closed.

**Comment by syshen** [comment]
@grahamcruse how do I hook on the event when attachment button is tapped?   Do you have any update to this issue?

**Comment by oarrabi** [comment]
@dangochi we identified and fix issue #35 and will release a patch soon.

**Comment by oarrabi** [comment]
@syshen As stated above we are preparing a release soon.
When you tap on an attachment, the image will be attached to the chat. 

Why would you need to get informed when the image is uploaded?

**Comment by ndobri** [comment]
@dangochi Chat SDK release [1.1.3](https://github.com/zendesk/zendesk_sdk_chat_ios/releases/tag/1.1.3) should fix this. Would you mind verifying the fix? Feel free to reopen if this is still not working for you. Thanks. Closing.

**Comment by dangochi** [comment]
Thanks! This is working for me now
