### ISSUE TITLE
Attachment button (attachButton) not visible on chat 

### ISSUE THREAD

**Issue by danielCarlosCE** [zendesk/zendesk_sdk_chat_ios#190]
- SDK version:  v1.3.6.1
- Xcode version: Xcode 7.3.1
- iOS or Simulator: (Simulator) iphone 6s
- iOS Version:  9.1
- Swift version: 2.3

<img width="347" alt="screen shot 2018-04-27 at 9 43 41 am" src="https://user-images.githubusercontent.com/1819682/39363225-ec9787a2-49ff-11e8-9704-03ad69a126e1.png">

**Comment by danielCarlosCE** [comment]
https://support.zendesk.com/hc/en-us/articles/115009438848-Mobile-Chat-SDK-How-to-fix-the-attachment-icon-not-showing-in-your-mobile-app
```
Turn off File Sending and Save Changes.
Turn File Sending back on and Save Changes.
Run your project again.
```

**Comment by patrick-doyle** [comment]
Hi Daniel

Did the article you linked to help with the issue? If so I will close this issue.

**Comment by RonanMcH** [comment]
Hi @danielCarlosCE ,
Thanks for your input,
Ronan.
