### ISSUE TITLE
Build time error when importing header from ZDCChatAPI installed via cocoapods

### ISSUE THREAD

**Issue by dragomir-ivanov-212** [zendesk/zendesk_sdk_chat_ios#191]
- SDK version: 1.3.7.1
- Xcode version: 9.3
- iOS or Simulator: Both
- iOS Version: Any
- Swift version: N/A

Steps to Reproduce:

1. Create a project or use an existing project without 'ZDCChat' pod installed
2. Install pod 'ZDCChat/API' via cocoapods
3. Use "#import <ZDCChatAPI/ZDCAPIConfig+Timeout.h>" anywhere

Current behaviour:

Build time error - 'ZDCAPIConfig.h' file not found

Expected behaviour:

No build time errors are expected

@divo You can see it reproduced in this [sample project](https://github.com/dragomir-ivanov-212/ZDCBuildIssue).

See #187 for a proposed fix

**Comment by baz8080** [comment]
Thanks @dragomir-ivanov-212 
I checked out your project and saw the issue. We do developer support on a rotation so I'm going to leave it to one of our iOS devs to discuss the way forward with the PR and issue. It's a public holiday in Ireland on Monday so it might be Tuesday or Wednesday when we let you know. Thanks!

**Comment by baz8080** [comment]
Hi, I'm going to close this issue. I have tracked it for regression for when we release chat SDK V2.
