### ISSUE TITLE
Localization & Support Right to Left languages 

### ISSUE THREAD

**Issue by christiygag** [zendesk/zendesk_sdk_chat_ios#192]
- SDK version: 1.3.7.1
- Xcode version: 9.2
- iOS or Simulator: iPhone 7
- iOS Version: iOS 11.3
- Swift version: 4

I have added Arabic localization into my app. But Zendesk chat SDK is not working as expected. Some labels are overlapped and some are misplaced. Totally weird behaviour. PFA the screenshot.
You can find Message placeholder and send icon overlapped at the bottom right. Also the agent name is misplaced.

![img_03661fd75c4a-1](https://user-images.githubusercontent.com/20677361/40278102-f9f86c6a-5c3b-11e8-84ba-66d4638b3684.jpeg)

**Comment by divo** [comment]
@christiygag thank you for bringing this to our attention. I have added it to our backlog but am unable to give a date for the next patch release.

**Comment by omar-dev** [comment]
any updates on this @divo ?

**Comment by HamstringAssassin** [comment]
Hi @omar-dev. I'm afraid we don't have any update on this yet. We'll let you know as soon as we do though. 

Cheers for getting in touch.

**Comment by NermeenMohamed** [comment]
@HamstringAssassin  @divo  Please Let me Know if it Will Support Arabic Language or not ?

**Comment by KillianSmith0** [comment]
Hi @NermeenMohamed, there is a plan to support all RTL languages (including Arabic) in the next release, however we're unable to put a time-frame when the next release will be. Sorry for the inconvenience

**Comment by darshandixit** [comment]
Any New Update For Localization Issues?

**Comment by HamstringAssassin** [comment]
Hi @darshandixit, 

We're currently working on an update to the Chat SDK and localization should be included. Unfortunately, I don't have a date that I can give you. 

Cheers, 
Al

**Comment by baz8080** [comment]
Hi All, I'm closing the issue. RTL is a must-have and will be in Chat SDK 2.0. As @HamstringAssassin we don't have any dates to share at the moment.
