### ISSUE TITLE
Notes are not being added to Zoplin

### ISSUE THREAD

**Issue by danielCarlosCE** [zendesk/zendesk_sdk_chat_ios#194]
- ZDCChat/API 1.3.7.1
- Xcode version: 9.4
- iOS or Simulator: Simulator
- iOS Version: 11.4
- Swift version: Objective-C

Steps to Reproduce:

ZDCVisitorInfo *visitorInfo = [[ZDCVisitorInfo alloc] init];
visitorInfo.phone = phone;
visitorInfo.name = name;
visitorInfo.email = email;
[visitorInfo addNote: [NSString stringWithFormat:@"CPF = %@", cpf]];

[chatApi setVisitorInfo: visitorInfo];

I receive all the info at Zoplin, except the added note.

**Comment by patrick-doyle** [comment]
@danielCarlosCE Can you add some logs to the issue to help us debug this?
Thanks

**Comment by baz8080** [comment]
@danielCarlosCE as Patrick mentioned, logs would be great. I was able to add a note using the latest version of the SDK.

<img width="296" alt="screen shot 2018-06-20 at 11 56 04" src="https://user-images.githubusercontent.com/1534413/41654341-0bc184c4-7481-11e8-974c-42f2e108e84c.png">

**Comment by danielCarlosCE** [comment]
Hey guys! Thanks for the answer. 
Well, I used the exactly code I showed above before calling `[chatApi startChatWithAccountKey:(accountKey)];` The whole code was:
```
   ZDCChatAPI *chatApi = [ZDCChatAPI instance];

    ZDCVisitorInfo *visitorInfo = [[ZDCVisitorInfo alloc] init];
    visitorInfo.phone = phone;
    visitorInfo.name = name;
    visitorInfo.email = email;

    [chatApi setVisitorInfo: visitorInfo];
    [chatApi startChatWithAccountKey:(accountKey)];
```

I ended up calling `[chatApi setNote:[NSString stringWithFormat:@"CPF = %@", cpf]];` after the `connectionStatus` was `ZDCConnectionStatusConnected` and that's what worked for me.

**Comment by divo** [comment]
![](https://media.giphy.com/media/pyl1E9trnmwdW/giphy-downsized-large.gif)
@danielCarlosCE Please post logs. We can do nothing without logs.

**Comment by tecknut** [comment]
We're glad you managed to get this working @danielCarlosCE. 

Thanks for letting us know
