### ISSUE TITLE
Swift 4 examples of chat styling customization?

### ISSUE THREAD

**Issue by dhsu210** [zendesk/zendesk_sdk_chat_ios#195]
- SDK version: 1.3.7.1
- Xcode version: 9.4.1
- iOS or Simulator: Simulator
- iOS Version:
- Swift version: 4.1

In the [documentation](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/customization), there's examples for customizing the styling in Obj-C, but does anyone have examples of styling using Swift? Not all of the appearance properties show up for Swift in the latest Xcode + latest release.

**Comment by patrick-doyle** [comment]
Hi,

Can you specify which properties are missing in swift 4?. We have an example in the docs you linked for Swift 3 if that helps.

Thanks

**Comment by dhsu210** [comment]
I was hoping the Swift 3 examples were a bit more specific besides `appearance()...`

I've been looking at the full Obj-C examples from [the reference below the Swift 3 section in the documentation](https://github.com/zendesk/zendesk_sdk_chat_ios/blob/master/ZopimChatSample/ZopimChatSample/ChatStyling.m). 

If I wanted to change the color of the navBar text in the chat, I'm currently attempting `ZDCChatUI.appearance.tintColor = UIColor`...but it doesn't seem to affect the UI at all. I have the line of code before `ZDCChat.start`

Ideally would like to change the color of that Back button text.
![simulator screen shot - iphone 8 plus - 2018-06-19 at 14 15 50](https://user-images.githubusercontent.com/10564231/41624747-6e19429e-73cb-11e8-8d2a-07e147384b92.png)

**Comment by divo** [comment]
@dhsu210 The file you linked is the most complete Chat SDK styling reference. We don't have a Swift example but it shouldn't be too tricky to work them out from the ObjC.

The Chat SDK doesn't modify the UINavigationBar. If you want to style it you can use its appearance proxy.

**Comment by dhsu210** [comment]
@divo What do you mean by the appearance proxy of the UINavigationBar? It appears as if the ChatSDK view pops up embedded in a NavigationController, but how do I access this?

**Comment by tecknut** [comment]
Hi @dhsu210, 

UIAppearance is an [Apple API](https://developer.apple.com/documentation/uikit/uiappearance) for global styling of UI elements in iOS. 

```
var navigationBarAppearace = UINavigationBar.appearance()

navigationBarAppearace.tintColor = .red
navigationBarAppearace.barTintColor = .red
```

Does this help you?

**Comment by dhsu210** [comment]
@tecknut Yes this is exactly what I was looking for! Thanks so much!

**Comment by blyscuit** [comment]
Hi, I am trying to set the bubble color of ZDCVisitorChatCell the obj-c code is 
`[[ZDCVisitorChatCell appearance] setBubbleColor:[ChatStyling navBarTintColor]];`
but I can't find swift equivalent.
