### ISSUE TITLE
How to disable LoadingErrorView?

### ISSUE THREAD

**Issue by hungcao2112** [zendesk/zendesk_sdk_chat_ios#196]
- SDK version: 1.3.7.1
- Xcode version: 9.4.1
- iOS Version: 11.4
- Swift version: 4

Steps to Reproduce:

1. Check for agents status, if no agent online still show the chatview (disable loadingErrorView) and set the label "No agent online" on top or something like that,is there any solution? 

2. Other solution is adding uiview subclass  ZDCChatView in other ViewController. I tried `chatView.activate()` but it still show blank view. 

Hope to see your answer soon !

**Comment by HamstringAssassin** [comment]
Hi @hungcao2112, 

Thanks for getting in touch. Unfortunately, the functionality you are looking for isn't available through the UI provided with the SDK. 

What might be of some use is the Chat API available through the SDK.
 
https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/sessionapi

Here you could build a custom UI to suit your needs. 

We also have a forum / community page where you can request new features. 

https://develop.zendesk.com/hc/en-us/community/topics/360000018828-Mobile-SDKs

Hope this is of some help to you. 

Thanks again, 
Al
