### ISSUE TITLE
In Leave a Message page, UITextField as UIResponder do not resign.

### ISSUE THREAD

**Issue by eliakorkmaz** [zendesk/zendesk_sdk_chat_ios#197]
- SDK version: 1.3.7.1
- Xcode version: Version 9.2 (9C40b)
- iOS or Simulator: İOS 10 
- iOS Version: iPhone 5 (Real Device)
- Swift version: 4

Steps to Reproduce:

1.  When you navigated to Leave a Message page then enter something to textfield for leave message and finally send the message, one of the three textfield still holds responder, the keyboard is still awaken. So its free to enter something when sending message process. It's not a bug i think, but it must be improved. I can handle it, if its fit for you? 

Best

**Comment by HamstringAssassin** [comment]
Hi @eliakorkmaz - Thanks for raising it with us. 

Just so I'm clear, is this the screen you are talking about when you say "Leave a message" page? 

![img_0124](https://user-images.githubusercontent.com/6310250/42935067-a23f0568-8b40-11e8-8e15-7508cb9095d1.PNG)

I dont think its a bug. The subsequent screen presented to the user is the chat screen and should have the keyboard active. 

Thanks for bringing it to our attention and getting in touch. 

Cheers, 
Al
