### ISSUE TITLE
Cannot change ZDCChatCells UI components

### ISSUE THREAD

**Issue by eliakorkmaz** [zendesk/zendesk_sdk_chat_ios#199]
- SDK version: 1.3.7.1
- Xcode version: 9.2 (9C40b)
- iOS or Simulator: iOS 10 
- iOS Version: iPhone 5 (Real Device)
- Swift version:  4 

Steps to Reproduce:

1.  Hi, I've downloaded your `zendesk_chat_ios_sdk` for a `Swift` project and integrate successfully in to the app. But when I try to change some UI elements such as `BubbleView`(ChatView) of the `AgentCell` or `VisitorCell` it can not be changed. I looked up the Zopim App that helps me a lot and I learned how to change a element but when I try in Swift app it can not be changed with using `appearance()`. Additionally I can not reach any element such as bubbleView or textView in Swift app. Where am I doing wrong? In the below, there are some code blocks that I've used.
``` swift
ZDCVisitorChatCell.appearance().backgroundColor = UIColor.geScheme
ZDCAgentChatCell.appearance().backgroundColor = UIColor.geScheme
        
ZDCChat.initialize(withAccountKey: myAccountKey)
```

Also started zendesk chat with,

```swift
ZDCChat.start(in: UIApplication.shared.keyWindow?.rootViewController?.navigationController, withConfig: nil)
```

**Comment by patrick-doyle** [comment]
Hi @eliakorkmaz 

Here is the list of appearance properties that are supported in the SDK.

https://github.com/zendesk/zendesk_sdk_chat_ios/blob/master/ZopimChatSample/ZopimChatSample/ChatStyling.m

If you want to change the background colour you need to use `ZDCAgentChatCell.appearance().bubbleColor` instead of background colour.

Lets us know if that helped
Patrick

**Comment by eliakorkmaz** [comment]
Hi @patrick-doyle 

Thanks for help, it worked. The mistake is Xcode is not showing the appearance properties when you write for example `ZDCAgentChatCell.appearance().` . I do not know why its not showing but maybe cause from the SDK written in OBJC. 

Thanks
Emrah

**Comment by HamstringAssassin** [comment]
Hi @eliakorkmaz, 

That sometimes happens - I find restarting Xcode can help. I'll close this ticket as the original issue has been solved. If there's anything else feel free to get in contact. 

Cheers, 
Al

**Comment by eliakorkmaz** [comment]
@HamstringAssassin  Thanks for advise. :)

Additionally I want to ask something with `ZDCVisitorChatCell`.

There are just one avatar for the `Agent`, I did not found any avatar for `Visitor`.  Can we edit or do something for `Visitor`?

**Comment by HamstringAssassin** [comment]
No, I'm afraid they are different cells - one of which has an avatar. 

There is always an option of rolling your own UI. Can read more about that here https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/sessionapi if you like. 

If there are features that you want to request, you can log them here - https://develop.zendesk.com/hc/en-us/community/topics.

Thanks, 
Al

**Comment by eliakorkmaz** [comment]
Thanks for help. I will looking at these documents.
