### ISSUE TITLE
symlinks wrong

### ISSUE THREAD

**Issue by oleksiivinogradov** [zendesk/zendesk_sdk_chat_ios#2]
MacBook-Pro-Oleksii-2:Frameworks alex$ cd ZDCChat.framework/
MacBook-Pro-Oleksii-2:ZDCChat.framework alex$ ls -la
total 24
drwxr-xr-x@ 6 alex  staff  204 Apr 24 09:33 .
drwxr-xr-x@ 7 alex  staff  238 Apr 24 10:01 ..
lrwxr-xr-x@ 1 alex  staff  113 Apr 24 09:33 Headers -> /Users/gcruse/mobile/chat/zendesk_chat_sdk_ios/ZDChat/../build/Release/ZDCChat.framework/Versions/Current/Headers
lrwxr-xr-x@ 1 alex  staff  115 Apr 24 09:33 Resources -> /Users/gcruse/mobile/chat/zendesk_chat_sdk_ios/ZDChat/../build/Release/ZDCChat.framework/Versions/Current/Resources
drwxr-xr-x@ 4 alex  staff  136 Apr 24 09:33 Versions
lrwxr-xr-x@ 1 alex  staff  113 Apr 24 09:33 ZDCChat -> /Users/gcruse/mobile/chat/zendesk_chat_sdk_ios/ZDChat/../build/Release/ZDCChat.framework/Versions/Current/ZDCChat

i don't think so it can be work anywhere....

**Comment by grahamcruse** [comment]
Quite right and thanks for reporting, this should now be fixed in master.
