### ISSUE TITLE
Text entry box hidden behind UITabBarController

### ISSUE THREAD

**Issue by dangochi** [zendesk/zendesk_sdk_chat_ios#20]
If my app uses a UITabBarController and I push the chat controller onto a navigation controller's stack, it seems I can get stuck in a state where the chat text entry bar will be hidden behind the tab bar once the keyboard is dismissed. Once this happens, I haven't found a way to access the text entry box within that session.

Is there an issue where the navigation controller's bottomLayoutGuide isn't being propagated down to the chat view controller (and the scroll view's content insets aren't adjusted accordingly)?

I've been able to hack around this for now by hiding my tab bar when pushing the chat VC. However, this is a hack, so I'm nervous that it'll have unintended side effects:

    UINavigationController *bogusChatNC = [UINavigationController new];
    [ZDCChat startChatIn:bogusChatNC withConfig:nil];

    ZDCChatViewController *chatViewController = [ZDCChat instance].chatViewController;
    if (chatViewController != nil) {
        chatViewController.hidesBottomBarWhenPushed = YES;
        [self.navigationController pushViewController:chatViewController animated:YES];
    }

The above code starts the chat in a blank UINavigationController that's not presented anywhere; this is simply to initialize the chat view controller. After it's been initialized, I set ```hidesBottomBarWhenPushed = YES``` and then push the chat view controller onto my real navigation controller stack.

If there's something I can do using the current SDK that's not as hacky, please let me know. I included a short gif below to show how the tab bar hides the text entry bar.

![zopim tab bar controller](https://cloud.githubusercontent.com/assets/1784093/10406226/5c98eda2-6e93-11e5-94e7-df6a409b8ecb.gif)

**Comment by grahamcruse** [comment]
@dangochi thanks for the detailed report, we have located the problem and the fix along with the ability to specify whether the chat should hide the bottom bar will be in the next patch.

**Comment by dangochi** [comment]
@grahamcruse that sounds great; thank you! Do you have a rough idea about when you plan on releasing the next patch? I'm really looking forward to fixes for this and https://github.com/zendesk/zendesk_sdk_chat_ios/issues/19.

**Comment by tecknut** [comment]
@dangochi Hi again, has our latest update solved this for you?

**Comment by dangochi** [comment]
@tecknut the new ```hidesBottomBarWhenPushed``` property works and provides me of a way to hide the tab bar in a way that doesn't involve the hack I mentioned above. Thanks for that!

I can use that for now, but hiding the tab bar was already a workaround for the original issue of having the chat bar hidden behind the tab bar. I'd like to not have to hide the tab bar if possible and I'm sure others would like that feature as well.

When testing chat with the update to 1.1.2, however, it seems the chat bar is hidden all the time now (which is worse than this original issue), so I'm keeping our apps on 1.1.1 for now. I logged #35 for the new issue.

**Comment by oarrabi** [comment]
@dangochi Sorry for this issue, we are currently working on a fix and should update the SDK soon.

**Comment by ndobri** [comment]
@dangochi could you please test against [1.1.3](https://github.com/zendesk/zendesk_sdk_chat_ios/releases/tag/1.1.3) and let us know if that worked for you. Thank you.

**Comment by baz8080** [comment]
Closing this issue as we haven't heard back. Please reopen if you have more questions on this issue.

**Comment by dangochi** [comment]
This appears to be fixed indeed, thank you!
