### ISSUE TITLE
Chat background image in Swift 4

### ISSUE THREAD

**Issue by rpelorosso** [zendesk/zendesk_sdk_chat_ios#200]
- Xcode version: 9.4.1
- iOS Version: 11.0
- Swift version: 4.1

Hi! 

I can set the Chat's background color with 

```
ZDCChatView.appearance().chatBackgroundColor = UIColor.red
```

But how do I set an image as background?

thank you!

**Comment by HamstringAssassin** [comment]
Hi @rpelorosso,

I'm afraid that functionality isn't available. If you want, you can log a feature request here https://develop.zendesk.com/hc/en-us/community/topics. 

All available chat stylings can be found here: https://github.com/zendesk/zendesk_sdk_chat_ios/blob/master/ZopimChatSample/ZopimChatSample/ChatStyling.m

Thanks for getting in contact, 

Cheers, 
Al

**Comment by rpelorosso** [comment]
Hi @HamstringAssassin, thank you for your answer,

I've gone through that document and have found

```
[[ZDCChatUI appearance] setChatBackgroundImage:@"SampleBackground"];
```

what does this function do? I couldn't find it in Swift, though, why is it?

thanks!
Rodrigo

**Comment by HamstringAssassin** [comment]
Ah, I was mistaken. Sorry about that. 

I was able to do it here using the following in a sample app.

``` 
ZDCChatUI.appearance().backgroundImageView = UIImageView(image: image)
ZDCChatView.appearance().chatBackgroundColor = .clear
```

Let me know how that goes.

**Comment by KillianSmith0** [comment]
Hi @rpelorosso,

Just a quick bump to see if Alan's solution worked for you? If not let us know, otherwise we can close the issue!

**Comment by rpelorosso** [comment]
Thank you @HamstringAssassin  and @KillianSmith0 ! I had missed your new messages. Indeed that worked, but I had to set the frame for the backgroundImageView in order for it to work. Thank you!
