### ISSUE TITLE
Embedding the chat in a UIView

### ISSUE THREAD

**Issue by rpelorosso** [zendesk/zendesk_sdk_chat_ios#201]
Hi!

I see the Android counterpart of this SDK has a way to init a chat as a fragment. Is there any way in the iOS version to create the Chat's view controller and add its view as a subview to a container UIView?

Thank you! 
Rodrigo

**Comment by HamstringAssassin** [comment]
Hi @rpelorosso,
Unfortunately that functionality isn't available in the iOS SDK. 

if you want though, you could log a feature request here https://develop.zendesk.com/hc/en-us/community/topics. 

Cheers,
Al
