### ISSUE TITLE
Change the color of the statusBar

### ISSUE THREAD

**Issue by ahmed-khalil** [zendesk/zendesk_sdk_chat_ios#202]
- SDK version: 1.3.7.1
- Xcode version: 9.2
- iOS or Simulator: both
- iOS Version: 11
- Swift version: 4

So I am presenting the Zendesk Chat module by:

ZDCChat.start(in: nil, withConfig: nil)

I am having a hard time changing the statusBar color to light color. How would you be able to do that?

**Comment by divo** [comment]
@ahmed-khalil Can you provide a bit more information please? Is the problem the status bar changes appearance when you launch the chat?

**Comment by HamstringAssassin** [comment]
Hi @ahmed-khalil,

If I present the chatUI with a basic navigationContoller it respects the statusBar style. 

Are you doing anything to the status bar style in the presenting ViewController? If i have `View controller-based status bar appearance` set to `NO` in my info.plist i need to manage the statusBar style after i present the ChatUI.

**Comment by ahmed-khalil** [comment]
Well, we override the status bar appearance in some of our view controllers, so the default is dark, but sometimes (as in the case in the chat) we need it to be white.

**Comment by brendan-fahy** [comment]
Can you share with us what you've tried so far to manage the statusBar style?

**Comment by divo** [comment]
@ahmed-khalil the Chat SDK is setting the statusbar style to dark. I will add a story to out backlog to review this (and probably remove it, the reason for it is lost).

I can't say when we will release a fix though.

**Comment by baz8080** [comment]
Hi, We're actively working on V2 of the Chat SDK, and I'll add this bug to our list of things to check for regression. We're not going to patch this in V1.
