### ISSUE TITLE
Create a custom UINavigationController for specific customisations

### ISSUE THREAD

**Issue by txaiwieser** [zendesk/zendesk_sdk_chat_ios#203]
Hey, today if you need to customize the UINavigationBar you can do something like this:

        UINavigationBar.appearance().tintColor = .black
        UINavigationBar.appearance().barTintColor = .white

But this changes the appearance of every bar in the app. Ideally you should not use a plain `UINavigationController` when presenting the `ZDCChatViewController` modally, instead use a `ZDCChatNavigationController`.

This is a pretty straight forward change and then we'll be able to customize the UI specifically for the Chat NavigationBar.

        UINavigationBar.appearance(whenContainedInInstancesOf: [ZDCChatNavigationController.self]).tintColor = .black
        UINavigationBar.appearance(whenContainedInInstancesOf: [ZDCChatNavigationController.self]).barTintColor = .white

**Comment by HamstringAssassin** [comment]
Hi @txaiwieser, 

Thanks for getting in contact. If you want a new feature added - its best to add them here: https://support.zendesk.com/hc/en-us/community/topics

Cheers, 
Al

**Comment by txaiwieser** [comment]
This customisation is important so we can start using in all of our apps. 

https://support.zendesk.com/hc/en-us/community/posts/360004243348-Create-a-custom-UINavigationController-for-specific-customisations

**Comment by divo** [comment]
@txaiwieser we do have `+ (void) startChatIn:(UINavigationController*)navController withConfig:(ZDCConfigBlock)config`. Can you try creating your own navController, style that instance, and start chat in it. You can then present that navController modally and it will be styled.

Does that work for you?

**Comment by txaiwieser** [comment]
Unfortunately it doesn't, We're using this for starting our chat, but if the users returns to the chat (via the floating button) it starts modally with its own UINavigationController

**Comment by divo** [comment]
@txaiwieser fair enough. I have added this to our backlog but we don't have a release planned in the immediate future.

**Comment by baz8080** [comment]
Hi! We're currently working on Chat V2, and this is a great idea, and we'll have it, or similar there in V2. We went with a strategy of vending viewcontrollers in Support V2, and what we do in Chat V2 will be similar.

I'm going to close this issue, and track it in our V2 roadmap internally. we're not going to address this in the V1, sorry!
