### ISSUE TITLE
Change the translations for certain messages

### ISSUE THREAD

**Issue by ahmed-khalil** [zendesk/zendesk_sdk_chat_ios#204]
Hey, is it possible to change some texts/translations for the chat SDK?

**Comment by HamstringAssassin** [comment]
Hi @ahmed-khalil, 

The strings in the app can be changed. YOu can read more about it here:  https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/customization#strings-and-localization

Cheers, 
Al
