### ISSUE TITLE
Please update the SDK Docs for 1.4v

### ISSUE THREAD

**Issue by Spr-Luis** [zendesk/zendesk_sdk_chat_ios#206]
Please update the SDK Docs, the [changelog in cocoapods](https://cocoapods.org/pods/ZDCChat#changelog) say:

> Add support for push notifications

Please add more information in Github or your official web site. :(

**Comment by brendan-fahy** [comment]
Hi @Spr-Luis,
Our SDK docs have already been updated with more detail about 1.4. In particular, see [Push Notifications](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/push_notifications) and [Session Duration](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/chat#session-duration). Is there something else you were looking for?

**Comment by Spr-Luis** [comment]
👍 Thanks!
