### ISSUE TITLE
Unable to change enableOfflineMessageSendButton

### ISSUE THREAD

**Issue by ridvank** [zendesk/zendesk_sdk_chat_ios#207]
- SDK version: 1.3.7.1
- Xcode version: 9.4.1
- iOS or Simulator: Simulator
- iOS Version: 11.4
- Swift version: 4.1.2

Hi, I am unable to change enableOfflineMessageSendButton status. Trying to disable it such as:
`ZDCChat.instance().chatViewController.enableOfflineMessageSendButton(false)`
Any help would be appreciated.

**Comment by tecknut** [comment]
Hey @ridvank, 

Can you do some checking for me while we look into this? 

Is `ZDCChat.instance().chatViewController` non nil for you when you try to call this?

**Comment by ridvank** [comment]
Sure it is not nil :)

**Comment by KillianSmith0** [comment]
@ridvank 

Although the chatViewController is initialised, the sendButton is not initialised until the ViewController is sure that there is no Agents, therefore calling this won't work unfortunately, this is a timing issue. I will create a ticket in our backlog and keep you posted.

**Comment by baz8080** [comment]
Hi @ridvank 
This is captured in our internal roadmap and we'll make sure that it is addressed in v2 of the Chat SDK. We're not going to be able to patch it in V1, so I'm going to close this issue.
