### ISSUE TITLE
Setup department

### ISSUE THREAD

**Issue by MarkJoyful** [zendesk/zendesk_sdk_chat_ios#210]
- SDK version: 1.4.0
- Xcode version: 9.3
- iOS or Simulator: iOS
- iOS Version: 11.
- Swift version: 

how do i setup department before start a session , i just import ZDCChatApi,

**Comment by eepDev** [comment]
Closing an issue as already answered in our community post; https://develop.zendesk.com/hc/en-us/community/posts/360004329147-iOS-ChatApi-After-startsession-how-do-i-setup-department-?page=1#community_comment_360002109528
