### ISSUE TITLE
TexteField for imput message under keyboard and view not cover all space in container view

### ISSUE THREAD

**Issue by blackfoxik** [zendesk/zendesk_sdk_chat_ios#213]
- SDK version:1.4.0
- Xcode version:9.4.1
- iOS or Simulator: iPhone 8 plus simulator
- iOS Version:11
- Swift version:4

Steps to Reproduce:

1. I have tabbar view controller in one tab I have container view in which I try to add ViewController with zenchat programmatically
2.
I use the following code to add chat programmatically in the container view

 ```
      @IBOutlet weak var bodyView: UIView!
     ....
      let zdchat = ZDChatViewController.instantiateFrom(appStoryboard: .Main)!
            
            navVC = UINavigationController(rootViewController: zdchat)
            navVC.setNavigationBarHidden(true, animated: false)
           
        self.addChildViewController(navVC)
        navVC.view.frame =  CGRect(x: 0, y: 0, width: self.bodyView.frame.width, height: self.bodyView.frame.height)
        
        bodyView.addSubview((navVC.view)!)
        navVC.didMove(toParentViewController: self)
```

![issues](https://user-images.githubusercontent.com/4916875/46362316-9ac86680-c678-11e8-9155-e67879e9543e.jpg)

**Comment by blackfoxik** [comment]
I've tried to make my container view smaller by applying bottom constraint when keyboard appears and bigger when keyboard disappears. So I can see message input TextField, but if I put just one sign - textField moves under the keyboard. if I then resign input and start again typing - textfield not moves under the keyboard. It seems that when the first sign appears in textField "relayout" process under the hood moves textField. 
<img width="386" alt="2018-10-03 15 32 52" src="https://user-images.githubusercontent.com/4916875/46410522-c5bac500-c721-11e8-9132-bb5e163c0cf9.png">
<img width="385" alt="2018-10-03 15 39 27" src="https://user-images.githubusercontent.com/4916875/46410530-ce130000-c721-11e8-8fab-ff3bbfa3a3c9.png">

**Comment by juanlabela** [comment]
I have a similar issue with this screen but in my case, when the keyboard opens, the textfield goes twice up(like two times the height of the keyboard). Are you experiencing this issue too?

**Comment by bielikb** [comment]
Hi guys,

I filed this as a bug. Will close this issue, once it's resolved

**Comment by baz8080** [comment]
Hi @blackfoxik 
This is tracked internally. We're actively working on V2 at the moment, and we're building it in such a way that these kinds of issues won't happen. We won't be patching it in V1, so I'm going to close this issue.
