### ISSUE TITLE
Incompatibility with IQKeyboardManager

### ISSUE THREAD

**Issue by RodrigoLGuimaraes** [zendesk/zendesk_sdk_chat_ios#214]
- SDK version: 1.3.7.1

Don't think those really matter, but those were the condition in which I tested:
- Xcode version: Version 10.0 (10A255)
- iOS or Simulator: iPhone X 11.2
- iOS Version: 11.2
- Swift version: 4

Steps to Reproduce:

1. Add IQKeyboardManager or IQKeyboardManagerSwift to your project. I used Cocoapods and I have IQKeyboardManagerSwift (6.0.2) installed.
2. Add ZDCChat to your project, I used Cocoapods and I have ZDCChat (1.3.7.1) installed.
3. Push a ZDCChatViewController inside a navigation bar
4. When the keyboard appears, since both IQKeyboardManager and ZDCChatViewController have implemented the logic to offset the view in order for the keyboard not to hide the textfield, the textfield goes up more that it should.
5. When the keyboard is hidden, the textfield does not goes down all the way of the bottom of the screen and a black bar is visible below the textfield.

Example of textfield misalignment (tabbar content was edited out):
<img width="329" alt="screen shot 2018-10-08 at 09 24 55" src="https://user-images.githubusercontent.com/9063119/46608871-82bf6f80-cadc-11e8-8c27-207a1456f356.png">

**Comment by HamstringAssassin** [comment]
HI @RodrigoLGuimaraes, 

Thanks for getting in contact. 

We do not support IQKeyboardManager in the SDK. As you’ve correctly pointed out, its taking control of the layout when we are also handling showing the keyboard. 

I would try disabling IQKeyboardManager when showing Chat. See here for more info. https://github.com/hackiftekhar/IQKeyboardManager#warning

Cheers, 
Al

**Comment by HamstringAssassin** [comment]
Thanks @RodrigoLGuimaraes. 

Any more issues feel free to get in contact.

**Comment by apascual** [comment]
Hi,

I found a better way, add these lines to your IQKeyboardManager setup:

   ```
[[IQKeyboardManager sharedManager].disabledDistanceHandlingClasses addObject:[ZDCChatViewController class]];
[[IQKeyboardManager sharedManager].disabledTouchResignedClasses addObject:[ZDCChatViewController class]];
```

Cheers.
