### ISSUE TITLE
First send message doesn't show in chat

### ISSUE THREAD

**Issue by RonanMcH** [zendesk/zendesk_sdk_chat_ios#215]
@aravika08 , moving this issue to the correct repo.
Original issue: https://github.com/zendesk/zendesk_sdk_ios/issues/454

- SDK version: 2.2.0
- Xcode version: 10.0
- iOS or Simulator: iPhone X
- iOS Version: 12.1
- Swift version: 4.2

Steps to Reproduce:

1. Start ZDCChat:
`ZDCChat.start(in: self.navigationController) { config in
                config?.emailTranscriptAction = .neverSend
                self.navigationController?.navigationBar.isHidden = false
            }
            ZDCChat.updateVisitor { user in
                user?.addNote("chat-not-autorization")
            }
            ZDCChat.instance().overlay.setEnabled(false)`
2. First send message doesn't show in chat

**Comment by RonanMcH** [comment]
@aravika08 , looking into this now and will get back to you on this thread soon.

**Comment by RonanMcH** [comment]
Hi @aravika08 , 
I am unable to reproduce this issue you are having. I have tested on xcode 10 (iOS 12) and xcode 10.1 beta (iOS 12.1 beta) using iPhone X. I used the code you provided. 
Could you perhaps post a screenshot of the issue so we could see what is happening with the UI? There is no version 2.2.0 of the Chat SDK, could you clarify what version you are using?
Thanks,
Ronan.

**Comment by aravika08** [comment]
Sorry, version was wrong.

Current ZDC version:
#define ZDC_CHAT_SDK_VERSION @"1.4.0"

**Comment by RonanMcH** [comment]
Hi @aravika08 ,
Thanks for clearing that up. I tried again to recreate this issue just now and still no luck. There must be some differences in our set up. Could you post a small video so that we could see what is happening with the UI?
Thanks,
Ronan.

**Comment by aravika08** [comment]
Yes, sure:

https://drive.google.com/file/d/1NkxUHrCw6vT1orqmtRYy9a0UWjoWh7da/view?usp=sharing

**Comment by Blankz** [comment]
in my case
1. Agent online 
2. yes
3 when end chat and start new chat found bug sometime

**Comment by HamstringAssassin** [comment]
Hi @Blankz, 

Ah i see. We've heard of some people having issues with IQKeyboardManager before.

https://github.com/zendesk/zendesk_sdk_chat_ios/issues/214 - Heres a previous issue where a solution was found. 

Let us know if that works and we'll close the issue. 

Thanks, 
Al

**Comment by Blankz** [comment]
@HamstringAssassin 
it work now

Thanks

**Comment by baz8080** [comment]
Thanks, I'll close the issue.
