### ISSUE TITLE
How can I get End chat button action while leaving chat?

### ISSUE THREAD

**Issue by bhautikmobileappdev** [zendesk/zendesk_sdk_chat_ios#217]
- Xcode version: 9.2
- iOS or Simulator: ALL
- iOS Version: ALL

I am not finding a way to get End chat button event, Can we do it? Please help...

**Comment by RonanMcH** [comment]
Hi @bhautikmobileappdev ,
You can subscribe to chat connection events. This is detailed in our documentation [here](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/sessionapi#connection-events). Let us know if this helps.
Thanks,
Ronan

**Comment by HamstringAssassin** [comment]
Hi @bhautikmobileappdev, 

If there are no more questions I might go ahead and close this issue. 

Feel free to get in contact again. 

Cheers, 
Al
