### ISSUE TITLE
Missing authentication functionality

### ISSUE THREAD

**Issue by meros** [zendesk/zendesk_sdk_chat_ios#218]
- SDK version:
1.4

The Web SDK has authentication support and functionality to fetch history. This functionality is missing in 1.4 of the ios sdk. Is adding this on the agenda?

**Comment by baz8080** [comment]
Hi @meros 

Yes, it's on our longer term agenda. We are currently working on a version 2.0 of the Chat SDK, and this is one of the features that's in scope.

**Comment by meros** [comment]
That sounds promising! Is there any ballpark estimate on when that will
arrive?

**Comment by baz8080** [comment]
@meros We cannot give ETAs for this, sorry. What I can tell you is that we're working on building version 2.0 in such a way as to make new features of this quicker to implement, but that does mean there's a lot of groundwork to do first.

**Comment by HamstringAssassin** [comment]
Hi @meros, I'm going to close this issue. Feel free to ping us again if you have any other questions for us. 

thanks a mil,
Al
