### ISSUE TITLE
ios 9 iphone 6s Crashing when minimizing app during chat

### ISSUE THREAD

**Issue by felixdkatt** [zendesk/zendesk_sdk_chat_ios#22]
When I was in mid-chat i wanted to minimize the app and look for something on the phone. During which I asked the tester to send me more messages. I had the phone connected to xCode 7 and it crashed. The crash related something to a UITableViewCell that was not in the storyboard. Maybe some table that lets the other person know I was minimized. I'll try to get more data on the crash ASAP.

**Comment by felixdkatt** [comment]
Here is a log of the crash

[UITableView dequeueReusableCellWithIdentifier:forIndexPath:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3505.17/UITableView.m:6540
2015-10-16 17:57:01.937 MYAPP[1175:532746] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'unable to dequeue a cell with identifier (null) - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'
*** First throw call stack:
(0x18380cf5c 0x198cfbf80 0x18380ce2c 0x1846fbf3c 0x188ee6448 0x10080f1b4 0x1890a5660 0x1890a57b8 0x1890953b8 0x188e96420 0x10080fff0 0x1837b26ac 0x1837b1ecc 0x1837b1c4c 0x183817434 0x1836f2834 0x18465e2fc 0x1007e5fb4 0x102e01d70 0x102e01d30 0x102e07780 0x1837c4258 0x1837c20c0 0x1836f0dc0 0x18eb8c088 0x188dcaf44 0x1002194bc 0x19951a8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

![zdcchat_tableviewcrash](https://cloud.githubusercontent.com/assets/364910/10556110/00f5cc7a-7430-11e5-85c9-181e0f0139cf.jpg)

**Comment by dangochi** [comment]
@grahamcruse FWIW, I've seen the same issue here on iPhone 6s Plus running iOS 9.1.

**Comment by grahamcruse** [comment]
@felixdkatt @dangochi thanks for the report. We've got an update ready to prevent the crash at least; this is likely to be a transitional issue while moving between states so should be invisible but if you see any table cells that are obviously out of place let us know and we'll investigate further. I'll update this to let you know when we release the new version (shouldn't be too long now).

**Comment by felixdkatt** [comment]
thanks!

**Comment by jcosgriff** [comment]
Any updates? seeing we're experiencing the same thing .. seems to be affecting 8.x and 9.1

**Comment by tecknut** [comment]
@felixdkatt @jcosgriff We've released version 1.1.2 which should fix this issue. Can you let us know if 1.1.2 solves this for you? 

Thanks

**Comment by jcosgriff** [comment]
@tecknut will do

**Comment by schlan** [comment]
Hi @jcosgriff we haven't heard anything from you in a while. I'll close this issue now, if you run into any Chat SDK specific issues feel free to let us know.
