### ISSUE TITLE
Pushing the same view controller instance more than once is not supported (<ZDCChatViewController: 0x10f7191f0>)

### ISSUE THREAD

**Issue by megataps** [zendesk/zendesk_sdk_chat_ios#220]
- SDK version: 1.4.0
- Xcode version: 10.1
- iOS or Simulator: ip7 plus
- iOS Version: 12.1
- Swift version: 3.0

I can not reproduce it but i got report from Fabric notification we have 20 crashes with this info:

> 0  CoreFoundation                 0x1879a3ef8 __exceptionPreprocess
> 1  libobjc.A.dylib                0x186b71a40 objc_exception_throw
> 2  UIKitCore                      0x1b41561d0 __71-[UINavigationController pushViewController:transition:forceImmediate:]_block_invoke
> 3  UIKitCore                      0x1b47b4800 _runAfterCACommitDeferredBlocks
> 4  UIKitCore                      0x1b47a2840 _cleanUpAfterCAFlushAndRunDeferredBlocks
> 5  UIKitCore                      0x1b47d1b78 _afterCACommitHandler
> 6  CoreFoundation                 0x187931b94 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
> 7  CoreFoundation                 0x18792c828 __CFRunLoopDoObservers
> 8  CoreFoundation                 0x18792cdc8 __CFRunLoopRun
> 9  CoreFoundation                 0x18792c5b8 CFRunLoopRunSpecific
> 10 GraphicsServices               0x189ba0584 GSEventRunModal
> 11 UIKitCore                      0x1b47a8bc8 UIApplicationMain

**Comment by schlan** [comment]
Hi @megataps , thanks for reporting this issue. Sadly, we haven't been able to reproduce it either. Can you share with us the code that you're using to start the Chat SDK?
- Sebastian

**Comment by RonanMcH** [comment]
Hi @megataps ,
Could you please provide with some context as to the percentage of users this crash is happening to? This would give us a better insight as to the magnitude of the issue.
Thanks,
Ronan.

**Comment by HamstringAssassin** [comment]
Hi @megataps, 

I'm going to close this issue. If you are still having issues or if its severity increases please feel free to give us a shout. 

Thanks, 
Al
