### ISSUE TITLE
How to remove back button from navigation bar?

### ISSUE THREAD

**Issue by emresorbaci** [zendesk/zendesk_sdk_chat_ios#222]
- SDK version:1.4.0
- Xcode version:9.3 (9E145)
- iOS or Simulator:simulator
- iOS Version:11.3
- Swift version: objective-c latest

I want to remove ChatView back button. (Left Bar Button)

![screen shot 2018-12-06 at 19 56 23](https://user-images.githubusercontent.com/11772054/49599063-156f7400-f991-11e8-9875-7f099e5bd615.png)

**Comment by danthedrummer** [comment]
Hi, the SDK doesn't provide an API to remove the back button

**Comment by emresorbaci** [comment]
I don't want user to leave without close the chat and I don't want it in my UI.

**Comment by HamstringAssassin** [comment]
Hi @emresorbaci, 

Unfortunately, this is not a feature offered by the SDK. if you'd like to request the feature, feel free to create a post in our community for it. 

https://develop.zendesk.com/hc/en-us/community/topics

Thanks, 
Al

**Comment by RonanMcH** [comment]
Hi @emresorbaci ,
I am going to close this issue as feature requests are handled via the community forum as pointed out above.
Regards,
Ronan.
