### ISSUE TITLE
Restore chat session after app kill

### ISSUE THREAD

**Issue by yan-zaitsev** [zendesk/zendesk_sdk_chat_ios#223]
- SDK version: 1.4.0
- Xcode version: 10.1
- iOS or Simulator: Device
- iOS Version: 12.1
- Swift version: 4.2

Steps to Reproduce:

1. Start chat session
2. Switch to another app (app with chat will be in background)
3. Wait until system kill app / user kill app
4. Start app, open chat

**Expected:**
I see previous chat session. I can finish it by "End chat" button
**Actual:**
New chat session is started

**Question:
Is it possible to restore previous chat session?**

My start chat session code:
```swift
func showChat(preFilledMessage: String?) {
    guard self.navigationController.topViewController?.presentedViewController == nil else {
        self.navigationController.topViewController?.dismiss(animated: false, completion: {
            self.showChat()
        })
        return
    }
    IQKeyboardManager.shared().disabledDistanceHandlingClasses.add(ZDCChatViewController.classForCoder())
    IQKeyboardManager.shared().disabledDistanceHandlingClasses.add(ZDCChatViewController.self)

    ZDCChat.initialize(withAccountKey: VFQUtils.confZopimKey())
    ZDCChat.instance().overlay = nil
    ZDCChat.start(in: self.navigationController) { (defaults: ZDCConfig!) in
        defaults.sessionTimeoutInterval = 20 * 60
        defaults.preChatDataRequirements.name = .required
        defaults.preChatDataRequirements.email = .required
        defaults.preChatDataRequirements.phone = .required
        defaults.preChatDataRequirements.department = .requiredEditable
        defaults.preChatDataRequirements.message = .required
        defaults.tags = ["AppChat"]
        }
    ZDCChat.instance().overlay = VFQZDCChatOverlay()
    if let message = preFilledMessage {
        DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(1)) {
            ZDCChat.instance().chatViewController?.chatUI?.formView?.messageText = message
            ZDCChat.instance().chatViewController?.chatUI?.formView.formTable.reloadData()
        }
    }

}
```

**Comment by danthedrummer** [comment]
From my sample app I can kill the app and when I reopen the app the chat session is still active. It sounds like you're running into the session duration running out which will end the chat entirely based on these constraints: 
https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/chat#session-duration

**Comment by yan-zaitsev** [comment]
> From my sample app I can kill the app and when I reopen the app the chat session is still active. It sounds like you're running into the session duration running out which will end the chat entirely based on these constraints:
> https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/chat#session-duration

Hi, I got video from tester and replicate it on simulator. It looks like session is not finished, but messages are not visible + user is connected to another agent (simulator chat.mp4 new agent name reply).
[Simulator video](https://www.dropbox.com/s/fnyo1gbjgq3yze0/simulator%20chat.mp4?dl=0)
[Device video](https://www.dropbox.com/s/ppmiahq0pe4hg6b/device%20chat.mp4?dl=0)

**Comment by HamstringAssassin** [comment]
Hi @yan-zaitsev, 

Sorry about the delay getting back. I think I've managed to reproduce the issue. Once I killed the app, I needed to wait to see a message in the chat dashboard that `<user> has left.` Once I was able to see that, I was able to repo the issue. 

I'm pretty sure this is a bug. I've added it to our backlog. I'll keep this ticket open in the mean time until its resolved. 

Thanks, 
Al

**Comment by baz8080** [comment]
hi @yan-zaitsev Thanks for the issue and all of the supporting materials. This is tracked internally, and we'll use that issue to ensure that Chat SDK V2 doesn't have the same issue. It's in active development at the moment. We won't be able to patch this issue in V1, so I'll close this issue for now.
