### ISSUE TITLE
Dismiss modally presented chat

### ISSUE THREAD

**Issue by eirikvaa** [zendesk/zendesk_sdk_chat_ios#226]
- SDK version: 1.4.0
- Xcode version: 10.1
- iOS or Simulator: Simulator
- iOS Version: 12.1
- Swift version: 4.2

Is there any way of dismissing a modally presented chat? As of now you can, obviously, navigate back from a chat which is pushed on the navigation stack, but not able to dismiss a modally presented chat. This is limiting because sometimes it's better in regards to the context to present the chat modally.

**Comment by KillianSmith0** [comment]
Hi @eirikvaa 

We allow you to present a modal chat with the `ZDCChat.start(sessionConfig: ZDCConfigBlock)` api, like so in swift

```swift
        ZDCChat.start {
            $0?.department = "Dev"
            $0?.emailTranscriptAction = .prompt
        }
```

This will present a screen, embedded in a navigation controller, which allows the end user to dismiss or end the chat.. is this the functionality you are trying to describe?

Regards,
Killian

**Comment by eirikvaa** [comment]
I managed to dismiss the chat by tapping in the upper-left corner of the chat (which is the navigation bar, but that was actually hard to tell since it's white), which triggered the tap of an invisible dismiss button. This seems like a bug, but if not, how can it be made visible?

**Comment by KillianSmith0** [comment]
Hi @eirikvaa 

Do you customise your `UINavigationBar.appearance()` at all? The `dismiss` and `endButton` chat buttons are the system default blue by default.

If you want to change the colour of the labels' use
```swift
UINavigationBar.appearance().tintColor = desiredColour
```

Hope this helps!

**Comment by KillianSmith0** [comment]
Hi @eirikvaa did this solution resolve your issues?

**Comment by eirikvaa** [comment]
Hey! Sorry, I totally forgot to answer you. I haven't found out why the button isn't disabled. All our other navigation bar buttons are dark, so one would think that the chat dismiss button would be too. I'm guessing we're doing something else that causes the disappearance of the dismiss button. But I now know the button _is_ there, so I guess my question has been answered.

**Comment by KillianSmith0** [comment]
Ok @eirikvaa, I hope you figure out where your app is changing the UIButtons. I will close this issue for now, but if you find any other issue, or a reason relating to the SDK feel free to let us know!

Thanks,
Killian
