### ISSUE TITLE
How do I add text over the button ?

### ISSUE THREAD

**Issue by joelgeorgy** [zendesk/zendesk_sdk_chat_ios#25]
![test](https://cloud.githubusercontent.com/assets/15084436/10715753/1723506e-7b22-11e5-9dd8-d05423b0fe30.png)
How do I add text like this in the code? and where do i put the code?

**Comment by ndobri** [comment]
Hey @joelgeorgy, I am glad that you're ready to try out the Chat SDK. In this particular case it's totally up to you how you want to design your chat home screen as this is completely independent of the chat SDK.  I can advise you to have a look at out getting started docs for iOS and Android where you should find almost everything you need for it. 

https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/introduction

I'll close this ticket now but if you run into any Chat SDK specific issues feel free to let us know.
