### ISSUE TITLE
Bitcode support

### ISSUE THREAD

**Issue by gravera** [zendesk/zendesk_sdk_chat_ios#26]
When i try to archive my application i get the following error:
ld: bitcode bundle could not be generated because '../Pods/ZDCChat/ZDCChat.framework/ZDCChat(ZDCJSWidgetIO.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

**Comment by tecknut** [comment]
@gravera Our latest release was built with bitcode support. Can you provider some more information? What version are you using?

**Comment by RonanMcH** [comment]
Hi @gravera ,
we have recently discovered that you were correct and that our release with bitcode enabled that was previously done has a bug and was not built properly with full bitcode support. We are currently working to provide a version with bitcode enabled properly and we will release it soon.
Thanks for bringing it to our attention,
Ronan.

**Comment by gravera** [comment]
Awesome, thank you!

**Comment by tecknut** [comment]
@gravera Hey we've just released an update which should fix this for you. Can you let us know if things are working for you now?

Thanks

**Comment by schlan** [comment]
Hi @gravera, 
we haven't heard from you in a while. I'll close this issue now but if you run into any Chat SDK specific issues feel free to let us know.
