### ISSUE TITLE
Email Transcript Alert

### ISSUE THREAD

**Issue by canozkan** [zendesk/zendesk_sdk_chat_ios#27]
I want to disable "Email Chat Transcript" alert. But i can't find any option for it.

**Comment by tecknut** [comment]
Hi @canozkan, can you clarify? Do you want to disable the email chat transcript alert only but still send out a transcript?

**Comment by canozkan** [comment]
Hi @tecknut , i want to disable both alert and sending transcript.

**Comment by tecknut** [comment]
Ok, this is currently not configureable but this has been requested by other people so we have added it as a feature request and included it in our road map for upcoming releases.

There is probably a way to achieve what you want, but it would require modifying the chat view controller at in a way that we wouldn't really support. If you're happy to try this I can outline some steps. 

Again, this is something which you would have to be happy with putting in your app for release as it's not something that we officially support.

**Comment by tecknut** [comment]
Hey @canozkan is this issue still affecting you?

**Comment by canozkan** [comment]
Hi @tecknut , i read new release notes but still cant find a way to disable this alert

**Comment by tecknut** [comment]
@canozkan an update for you. We have added this as a feature and are in the process of QA'ing. There will be a release soon (one or two weeks).

**Comment by ndobri** [comment]
@canozkan with the new [1.1.3](https://github.com/zendesk/zendesk_sdk_chat_ios/releases/tag/1.1.3) release of the chat sdk you should be able to disable the email transcript alert. Closing.

**Comment by canozkan** [comment]
It works thank you !
