### ISSUE TITLE
Wrap up a React Native Component

### ISSUE THREAD

**Issue by cancan101** [zendesk/zendesk_sdk_chat_ios#32]
Would be cool if this were wrapped up as a react native component.

For an similar effort see: https://github.com/auth0/Lock.ReactNative

Related: https://github.com/zendesk/zendesk_sdk_ios/issues/105

**Comment by RonanMcH** [comment]
@cancan101 Thanks for your input.  We don't have any plans to implement this, on our roadmap as of now, but it looks cool.

**Comment by alidawud** [comment]
+1

**Comment by rturk** [comment]
Hi all any updates?

**Comment by baz8080** [comment]
Hi @rturk 

Sorry, there are no updates right now.

**Comment by mathewcropper** [comment]
Hi. I'm Mat, the Product Manager for our SDKs. The best place for SDK feature requests is the [Zendesk SDK community](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs), or the [Product Feedback community](https://support.zendesk.com/hc/en-us/community/topics/200132066-Product-feedback) for more general Zendesk ideas. This allows your idea to have a broader reach and discussion. We don't manage feature requests via Github, I'm afraid.

I looked, and there isn't anything in there at the moment for this particular idea. If you'd like to add it, I'm sure the community would be interested in your thoughts.
