### ISSUE TITLE
Chat bar hidden in apps that use UITabBarController?

### ISSUE THREAD

**Issue by dangochi** [zendesk/zendesk_sdk_chat_ios#35]
@tecknut after updating to version 1.1.2 of the SDK, I started noticing this bug where the chat bar is hidden in my app. When the chat view controller is pushed, the keyboard will be presented, but the chat bar isn't there. If I dismiss the keyboard by tapping somewhere else in the chat window, I can't get the keyboard back because there's no chat bar to show it. In order to get the keyboard back, I have to dismiss chat and re-open it.

The chat bar is hidden if I push the chat view controller with the following code:

    [ZDCChat instance].hidesBottomBarWhenPushed = YES;
    [ZDCChat startChatIn:self.navigationController withConfig:nil];

It also happens if I try to present the chat view controller modally doing simply this:

    [ZDCChat startChat:nil];

I wonder if this is an issue with apps that use UITabBarController as I couldn't reproduce this problem with the sample chat app. I caught it while trying to test #20. When I reverted our app back to 1.1.1, this issue went away.

Screenshots below with version 1.1.1 (working as expected), then with the keyboard shown/dismissed in 1.1.2 with no chat bar accessible.

===

**1.1.1**
![working as expected in 1 1 1](https://cloud.githubusercontent.com/assets/1784093/11412792/c214519a-9395-11e5-9ce1-248e38464bbd.png)

===

**1.1.2** keyboard shown
![chat bar not showing on not dismiss](https://cloud.githubusercontent.com/assets/1784093/11412795/cdbf4432-9395-11e5-8d4e-719669b0502a.png)

===

**1.1.2** keyboard dismissed
![chat bar gone on dismiss](https://cloud.githubusercontent.com/assets/1784093/11412796/d6fef8b2-9395-11e5-8bc7-124cd1458a39.png)

**Comment by oarrabi** [comment]
@dangochi Thank you for bringing this up and for the detailed issue description. We are currently working on this issue and should have an update soon.

**Comment by jcosgriff** [comment]
encountering the same issue here.

**Comment by oarrabi** [comment]
Hello @jcosgriff and @dangochi we have fixed this issue and will be releasing it in our next patch. 
Thank you for your patience.

**Comment by ndobri** [comment]
Release [1.1.3](https://github.com/zendesk/zendesk_sdk_chat_ios/releases/tag/1.1.3) should resolve this issue. Closing.

**Comment by dangochi** [comment]
I know I'm late to respond, but I updated and tested and this is no longer an issue for me. Thanks!
