### ISSUE TITLE
Please add Carthage support

### ISSUE THREAD

**Issue by degterev** [zendesk/zendesk_sdk_chat_ios#37]
Please add Carthage support

**Comment by schlan** [comment]
Hi @degterev
I added your feature request to our backlog. We'll notify you, as soon as we have any updates on it.
Sebastian

**Comment by Dodig** [comment]
@degterev :+1:

**Comment by oarrabi** [comment]
Hello @Dodig,

Sure, we will update this GitHub issue when we have that implemented.

**Comment by TofPlay** [comment]
@oarrabi any news about Carthage support?

**Comment by TofPlay** [comment]
@oarrabi for Carthage if it's can help take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://realm.io/news/swift-dependency-management-with-carthage/)
- [Carthage Tutorial: Getting Started](https://www.raywenderlich.com/109330/carthage-tutorial-getting-started)
- [Making Carthage-compatible Frameworks with Swift](http://blog.mat.tc/how-to-make-a-carthage-compatible-framework/)
- [Creating Cross-Platform Swift Frameworks for iOS, watchOS, and tvOS via Carthage and CocoaPods] (http://basememara.com/creating-cross-platform-swift-frameworks-ios-watchos-tvos-via-carthage-cocoapods/)

**Comment by guillaumemaiano** [comment]
@schlan Just wanted to register that we also are interested in Carthage support.

**Comment by TofPlay** [comment]
Any news about Carthage support?

**Comment by TofPlay** [comment]
Any news about Carthage support? (bis)

**Comment by oarrabi** [comment]
Hello @TofPlay 

We would love to support Carthage distribution too. However, that is something that we won't be focusing on this year.

I will keep this issue open and update it when we have more capacity to take this on.

Thanks,
Omar...

**Comment by mathewcropper** [comment]
Hi. I'm Mat, the Product Manager for our SDKs. The best place for SDK feature requests is the [Zendesk SDK community](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs), or the [Product Feedback community](https://support.zendesk.com/hc/en-us/community/topics/200132066-Product-feedback) for more general Zendesk ideas. This allows your idea to have a broader reach and discussion. We don't manage feature requests via Github, I'm afraid.

I looked, and there isn't anything in there at the moment for this particular idea. If you'd like to add it, I'm sure the community would be interested in your thoughts.

**Comment by irodrigo17** [comment]
@mathewcropper @schlan Any updates on this? Is there a link to the backlog item where I can subscribe to get updates?
