### ISSUE TITLE
Add title to chat navbar?

### ISSUE THREAD

**Issue by emjoseph** [zendesk/zendesk_sdk_chat_ios#38]
How do I add a title to the navbar of the chat view. I'm currently using the ZDCChat.startChatIn method

**Comment by schlan** [comment]
Hi @emjoseph, thank you for your input, I'll add it to our backlog. At the moment Chat SDK doesn't support adding a title to the navbar.

**Comment by ZachJiroun** [comment]
Upvoting this. Would it be possible to mark in the documentation this is not currently possible? I just spend an hour figuring out I can't add a title.

**Comment by RIAlizer** [comment]
+1

**Comment by oarrabi** [comment]
Hello,

This has been fixed and planned for next release. I will update this issue when the release is shipped.

**Comment by oarrabi** [comment]
Hello

We just released `ZDCChat` version 1.2.0.1 which has a fix to this issue.
Please check it out and let us know.

Thanks!

**Comment by ZachJiroun** [comment]
@oarrabi could you point me to the fix? I looked through the changes and couldn't find how to set the nav bar title.

**Comment by RonanMcH** [comment]
Hi @ZachJiroun , @RIAlizer and, @emjoseph ,
this was actually added as a customizable string. The key for the string you are referring to is "ios.ZDCChat.title" which you can customize from within the `ZDCChatStrings.bundle`. 
Thanks,
Ronan.

**Comment by ZachJiroun** [comment]
Thanks @RonanMcH!

**Comment by pankajfoodpanda** [comment]
I am using ZDCChat, Navigation bar center title is coming as "Chat" but text comes in black color, How can I change text color.

**Comment by DevCoding226** [comment]
@RonanMcH 

I installed iOS ZDCChat SDK using CocoaPod.

Then, I tried to customize the strings following your guide: by creating ZDCChatStrings.bundle file.

But it is not working.

Can I know how I can do that?
