### ISSUE TITLE
Change podspec source

### ISSUE THREAD

**Issue by billyto** [zendesk/zendesk_sdk_chat_ios#41]
Right now this SDK is sourced at source 'https://github.com/zendesk/Specs.git', which also includes ZendeskSDK, what generate a warning running any pod [install | update | outdated] command, because ZendeskSDK is also indexed at https://github.com/CocoaPods/Specs

```
[!] Found multiple specifications for `ZendeskSDK (1.5.3.1)`:
- /Users/user/.cocoapods/repos/master/Specs/ZendeskSDK/1.5.3.1/ZendeskSDK.podspec.json
- /Users/user/.cocoapods/repos/zendesk/ZendeskSDK/1.5.3.1/ZendeskSDK.podspec
```

Can ZDCChat also be added to CocoaPods/Specs? This will clear the issue and also save you an additional git repo.

**Comment by schlan** [comment]
Hi @billyto , thank you for reporting that problem. For now, I'm not able to give you a workaround. I'll put it into our backlog and we keep you updated on that.

**Comment by billyto** [comment]
:+1:

**Comment by oarrabi** [comment]
Hello @billyto,

I apologize for being so late at updating this issue. We did push ZDCChat to the Pod trunk a while ago. 

We did try this and it resolves this, I will go ahead and close this issue for now. Please feel free to reopen in case its does not solve your problem.

Thanks :)
