### ISSUE TITLE
Chat UI has space above the content.

### ISSUE THREAD

**Issue by capecrawler** [zendesk/zendesk_sdk_chat_ios#42]
When starting the chat UI, there is a space above the content.

![simulator screen shot dec 12 2015 9 42 18 am](https://cloud.githubusercontent.com/assets/1147223/11759430/1c307222-a0b5-11e5-8d80-544ec125eab0.png)
![simulator screen shot dec 12 2015 9 41 59 am](https://cloud.githubusercontent.com/assets/1147223/11759429/1c2edff2-a0b5-11e5-999e-74f05cde4730.png)
![simulator screen shot dec 12 2015 9 41 47 am](https://cloud.githubusercontent.com/assets/1147223/11759428/1c2cef8a-a0b5-11e5-9334-9ec94fb815a8.png)

**Comment by oarrabi** [comment]
@capecrawler Thank you for reporting this issue. I think that your issue is related to issue #35.
We already have a fix in place and will be releasing a patch soon. Thanks for your patience.

**Comment by oarrabi** [comment]
Hello @capecrawler we release chat sdk 1.1.3 with a fix for this issue, I will be closing this issue, but feel free to reopen it if the issue is not solved.
