### ISSUE TITLE
How to determing unread messages by not using the ZDCChatOverlay?

### ISSUE THREAD

**Issue by capecrawler** [zendesk/zendesk_sdk_chat_ios#43]
Is there another way to determine the number of unread messages aside from showing the ZDCChatOverlay? Its gonna be useful for creating custom indicator like a UIBarButtonItem with badge number showing the unread messages count.

**Comment by baz8080** [comment]
@capecrawler can you try:

```objective-c
[[[ZDCChat instance].session dataSource] agentMessageCount]
```

**Comment by capecrawler** [comment]
It will return the total number of messages sent by the agent whether it has already been read by the user or not.

**Comment by RonanMcH** [comment]
Hi @capecrawler ,
I don't believe this is possible at the moment. It has been added to our backlog as a feature request so that we can get it to be seen by our product manager. If you had any more ideas about how you would like this to work, please let us know. We will keep you updated on its progress.

**Comment by ndobri** [comment]
@capecrawler, apologies for bit of confusion here. Recently we've added a notification event that boardcasts Chat UI LOADED/UNLOADED events. If you listen for those you should know exactly when to start counting the incoming agent messages as unread messages. 

```
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(backgroundEvent:) name:ZDC_CHAT_UI_WILL_UNLOAD object:nil];

[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(backgroundEvent:) name:ZDC_CHAT_UI_DID_LOAD object:nil];
```

And then count incoming agent messages `ZDCChatEventTypeAgentMessage ` as per our [docs](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/sessionapi#chat-events):

```
[[ZDCChat instance].session.dataSource addObserver:self forChatLogEvents:@selector(chatEvent:)];
```

Can you please let us know if this works for you so we can close the issue. Thank you.

**Comment by capecrawler** [comment]
This event is not being called if the chat UI is presented. Only works when pushed to a viewcontroller.

`
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(backgroundEvent:) name:ZDC_CHAT_UI_WILL_UNLOAD object:nil];
`

**Comment by oarrabi** [comment]
@capecrawler we noticed that we have an issue of net sending `ZDC_CHAT_UI_WILL_UNLOAD` when chat view is started in a modal way. I created a bug in our internal bug tracker and will update this issue when we have a solution for it.

**Comment by oarrabi** [comment]
Hello @capecrawler,

We just released `ZDCChat` version 1.2.0.1 which has a fix to this issue.
Please check it out and let us know.

Thanks!

**Comment by oarrabi** [comment]
I will close this issue now, if it stills persist, please don't hesitate to reopen it.

**Comment by riksof-abdulrauf** [comment]
![screen shot 2016-07-29 at 9 07 05 pm](https://cloud.githubusercontent.com/assets/5626513/17257188/670fe356-55da-11e6-91dd-4600a960ce76.png)
Getting this error can any one help

**Comment by tecknut** [comment]
Hey @riksof-abdulrauf we have a new version which has removed `session`. We have a [migration guide](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/migration#accessing-chat-api-from-zdcchat) which describes the change. You just need to change `session` to `api`. Read the docs in the link for more detail.

**Comment by riksof-abdulrauf** [comment]
@tecknut: thanks for your reply
I will update my code according your your suggestion, will inform you about status
InshaAllah
