### ISSUE TITLE
How to customize the rightBarButtonItem of the Navigation Bar?

### ISSUE THREAD

**Issue by capecrawler** [zendesk/zendesk_sdk_chat_ios#45]
Is it possible to remove the "End Chat" button and shows a custom UIBarButtonItem? Will this affect when displaying the no agent form since it shows also a rightBarButtonItem?

**Comment by tecknut** [comment]
@capecrawler Can you explain further? Do you want to remove the `End Chat` button completely?

**Comment by capecrawler** [comment]
Actually, I want to replace it with another button. I did some workaround by changing its properties.
```
        rightBarButtonItem.title = @"";
        rightBarButtonItem.action = @selector(someFunction);
        rightBarButtonItem.target = self;
        rightBarButtonItem.tintColor = [UIColor whiteColor];
        rightBarButtonItem.image = [[UIImage imageNamed:@"ic_image"] imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate];

```

**Comment by oarrabi** [comment]
In order to set an image for the right bar button, you can use the appearance method on `ZDCChatUI`
```
[ZDCChatUI appearance].endChatButtonImage = @"SampleBackground";
```

However, there is a bug at the moment that prevent image to be set for the right button icon. We logged the issue internally and will update you when we have a fix for it. Sorry for the inconvenience.

**Comment by capecrawler** [comment]
also can you look at this one, I think this is also not working.
```
    [ZDCChatUI appearance].backChatButtonImage
```

**Comment by capecrawler** [comment]
And, is there a way to change the test of the barbuttonitems? like change "End Chat" to "End" or "Back" to "Close"

**Comment by StevenDiviney** [comment]
Hi @capecrawler,

We have fixed the image not being set with endChatButtonImage. It will be out in the next release.

I also had a look at backChatButtonImage and it appears to be working if the view has been presented modally. If the view has been pushed the back button takes it's title from the previous screen, with no image, as would be expected.

I have created another issue in our backlog to define the behavior and fix it if we do decide the image should show in every case.

Thanks.

**Comment by marcoscurvello** [comment]
Has this issue been solved? I can't seem to change the "end chat" button image :/

**Comment by oarrabi** [comment]
Hello @marcoscurvello,

The `endChatButtonImage` has been fixed, however, we still didnt ship the fix in a release. 
This will go in the next ZDCChat release soon.

**Comment by oarrabi** [comment]
Hello,

We just released `ZDCChat` version 1.2.0.1 which has a fix to this issue.
Please check it out and let us know.

Thanks!

**Comment by oarrabi** [comment]
I will close this issue now, if it stills persist, please don't hesitate to reopen it.

**Comment by rsahu34** [comment]
i am unable change the chat viewcontroller navigation bar back button image

**Comment by rsahu34** [comment]
how to change the end chat button text colour ?

**Comment by eirikvaa** [comment]
I'm wondering about the same thing as @rsahu34. Is there a way to do this?
