### ISSUE TITLE
TextView doesn't resize when setting the text programmatically.

### ISSUE THREAD

**Issue by capecrawler** [zendesk/zendesk_sdk_chat_ios#46]
Hi, I have tried setting the text of the textEntryView thru code but it doesn't resize automatically when the text is long.
Also the send button is still disabled.
```
    ZDCChatViewController *chatController = [ZDCChat instance].chatViewController;
    ZDCChatUI *chatUI = chatController.chatUI;
    [chatUI.chatView.textEntryView.textView setText:@"Lorem Ipsum is simply dummy text of the printing and typesetting industry."];
```
<img width="321" alt="screen shot 2015-12-17 at 12 14 32 pm" src="https://cloud.githubusercontent.com/assets/1147223/11861105/ccc9f97c-a4b7-11e5-9e2f-2f89eb505f6d.png">

**Comment by tecknut** [comment]
@capecrawler this is probably due to textview delegate methods not getting called when setting the text programmatically. 

What is the reason for setting the text programmatically? Maybe we can find a workaround.

Thanks.

**Comment by capecrawler** [comment]
For example, I have this list of predefined questions that the user can select one and will be set in that textview.

**Comment by oarrabi** [comment]
Unfortunately, there is no way of pre filling the chat field text. 

However, you might be able to achieve the same effect by sending a message directly to the customer. To do that add this after `ZDCChat startChatIn ...`

```
[[ZDCChat instance].session addObserver:self forConnectionEvents:@selector(connectionStateUpdated)];
```
And in `connectionStateUpdated` method:

```
- (void)connectionStateUpdated {
    ZDCConnectionStatus status = [[ZDCChat instance].session connectionStatus];
    if (status == ZDCConnectionStatusConnected) {
        [[ZDCChat instance].session sendChatMessage:@"A message"];
    }
}
```

You can also have the agent sends the user a list of questions to select from. This can be done using Zopim Shortcuts that are described here https://zopim.zendesk.com/entries/23821837-Shortcuts.

**Comment by baz8080** [comment]
Closing this issue as we haven't heard back. Please reopen if you have more questions on this issue.
