### ISSUE TITLE
How to customize background and corner radius for rating and question?

### ISSUE THREAD

**Issue by capecrawler** [zendesk/zendesk_sdk_chat_ios#48]
Is there a way to customize the corner radius for rating and question cell?

And also how to change the background color of the question and options cell.

<img width="377" alt="screen shot 2015-12-29 at 6 48 00 pm" src="https://cloud.githubusercontent.com/assets/1147223/12033367/36ce0c9c-ae5d-11e5-9fc7-00a0d9e33783.png">

**Comment by schlan** [comment]
Hi @capecrawler 

You can do the following to add a custom border radius and background color:

```
// Rating cell
[[ZDCRatingCell appearance] setBubbleCornerRadius:@(10.0f)];
[[ZDCRatingCell appearance] setBubbleColor:[UIColor colorWithRed:0.471 green:0.639 blue:0 alpha:1]];
    
// Options cell
[[ZDCAgentOptionsCell appearance] setBubbleCornerRadius:@(10.0f)];
[[ZDCAgentOptionsCell appearance] setBubbleColor:[UIColor colorWithRed:0.471 green:0.639 blue:0 alpha:1]];
```

**Comment by baz8080** [comment]
Closing this issue as we haven't heard back. Please reopen if you have more questions on this issue.
