### ISSUE TITLE
Is there a way to change the "Leave a message" button action?

### ISSUE THREAD

**Issue by capecrawler** [zendesk/zendesk_sdk_chat_ios#49]
When there are no agents available, the no agents screen is shown right. Now, is there a way to override the button's action like call a different function instead of sending offline message? Also change the text and appearance of the button.

**Comment by oarrabi** [comment]
Hello @capecrawler.

Currently there is no way to call a custom function when tapping the "Leave a message".

You can indeed style the button using the following snippet:

```
    [[ZDCLoadingErrorView appearance] setButtonFont:[UIFont boldSystemFontOfSize:15.0f]];
    [[ZDCLoadingErrorView appearance] setButtonTitleColor:[UIColor redColor]];
    [[ZDCLoadingErrorView appearance] setButtonBackgroundColor:[UIColor greenColor]];
    [[ZDCLoadingErrorView appearance] setButtonImage:nil]; // provide an image name to override default image
```

Please let me know if this answers your question

**Comment by baz8080** [comment]
Closing this issue as we haven't heard back. Please reopen if you have more questions on this issue.
