### ISSUE TITLE
can't close alert bcs keyboard hide part

### ISSUE THREAD

**Issue by oleksiivinogradov** [zendesk/zendesk_sdk_chat_ios#5]
https://www.dropbox.com/s/n5zkxk0w6391flh/iOS%20Simulator%20Screen%20Shot%20Apr%2028%2C%202015%2C%206.16.27%20AM.png?dl=0

**Comment by grahamcruse** [comment]
Hi Oleksii,

We have identified and fixed this problem for the next release, I'll close this issue once that release is out.

Thanks

Graham

**Comment by grahamcruse** [comment]
Fixed in 0.9.2.
