### ISSUE TITLE
Any way to force localization?

### ISSUE THREAD

**Issue by iurichiba** [zendesk/zendesk_sdk_chat_ios#50]
Hi! Can anyone help me with this?

I'm using ZDCChat like this:
```
[ZDCChat updateVisitor:^(ZDCVisitorInfo *visitor) {
        // set user info
    }]; [ZDCChat startChatIn:self.navigationController withConfig:^(ZDCSessionConfig *config) {
        // set department
    }];
```

Is there any way to force localization? Our app isn't localized yet, it's completely in pt_br; and it's a bit strange to open the chat view or ticket form view and see it in english. Not to mention that it's really awful for some of our users that don't know english very well :\

PS: We're planning localization sometime in the future, but that's not the focus atm.

**Comment by baz8080** [comment]
Hi @iurichiba 

The SDK picks up the locale of the device and we have strings for [pt-BR](https://github.com/zendesk/zendesk_sdk_chat_ios/blob/master/ZDCChatStrings.bundle/pt-BR.lproj/Localizable.strings). If your application is in pt-BR then it would work if it was _technically_ localised but just with that one language. If you have pt-BR strings hardcoded in your app and the device is set to English this will not pick up our strings.

Thanks,
Barry.

**Comment by iurichiba** [comment]
Hi @baz8080! Thanks for the answer!

I thought so, but I guess something's wrong (maybe on my part) - I tried setting the device's language to portuguese and it didn't affect the SDK's language, that's why I wanted to *force* localization.

Any idea why?

**Comment by brendan-fahy** [comment]
Hi iurichiba,

Forcing localisation like this isn't something we really support. 

_But_ if you do want to force pt-BR in the app every time, you could remove all the other languages (except for "pt.lproj") from the Zendesk SDK bundle, and rename the "pt.lproj" directory to "en.lproj". This change would be overwritten every time you pulled down a new version of the pod, and you would have to do this step again (deleting the folders, renaming the pt folder to "en"). 

This would obviously mean that Portuguese is the only language available. Please note this is a bit of a hack, but it will work.

Regards,
Brendan

**Comment by iurichiba** [comment]
Hi, @brendan-fahy,

I realize that's it's not ideal, and it's a bit of a hack, but I guess I'll do something like this while we don't localize the app. Hopefully, we'll do it soon, but in the meanwhile I guess it'd be better for us to keep everything in portuguese, preserving consistency in the app.

Thanks for the answer and for the suggestion :)

Best regards,
Iuri Chiba.
