### ISSUE TITLE
How to change visitor Avatar?

### ISSUE THREAD

**Issue by orbita256** [zendesk/zendesk_sdk_chat_ios#51]
Hi!
 // To override the default avatar uncomment and complete the image name
 [[ZDCChatAvatar appearance] setDefaultAvatar:@"your_avatar_name_here"];

Not work!!!

**Comment by RonanMcH** [comment]
Hi @orbita256 ,
Thanks for bringing this to our attention. This should be fixed in the next release.  If you want to set an avatar currently, you can set it in the Zopim dashboard. We'll update you when this is fixed.
Thanks again,
Ronan.

**Comment by oarrabi** [comment]
Hello @orbita256 

We just released `ZDCChat` version 1.2.0.1 which has a fix to this issue.
Please check it out and let us know.

Thanks!

**Comment by oarrabi** [comment]
I will close this issue now, if it stills persist, please don't hesitate to reopen it.
