### ISSUE TITLE
How to close keyboard?

### ISSUE THREAD

**Issue by orbita256** [zendesk/zendesk_sdk_chat_ios#52]
For what you adding return key?

**Comment by RonanMcH** [comment]
Hi @orbita256 ,
The keyboard closes when the "send" button is pressed in the user interface.  The return key is for skipping to a new line in the textfield. Are you looking for an alternative way to close the keyboard than the "send" button?

**Comment by baz8080** [comment]
@orbita256 I'm going to close this as we haven't heard back from you in a while. Please reopen if the issue is persisting.
