### ISSUE TITLE
How send message not from UITextField in chat?

### ISSUE THREAD

**Issue by orbita256** [zendesk/zendesk_sdk_chat_ios#53]
How send message not from UITextField?
Where i can use [[ZDCChat instance].session sendChatMessage:@"A message"];
in sample project?

**Comment by tecknut** [comment]
Hey @orbita256 can you expand on that please? 

What is the use case you had in mind?

Thanks

**Comment by baz8080** [comment]
@orbita256 I'm going to close this as we haven't heard back from you in a while. Please reopen if the issue is persisting.

**Comment by ajumalebrahim** [comment]
Hello @baz8080 and @tecknut , Am having same issue. I am using Version 1.3.2.1 SDK.
I need to send a predefined message to the agent for an identification purpose so agent will get to know easily and reply with predefined message. I tried to use` [[ZDCChatAPI instance] sendChatMessage:@"A message"];` for sending a message inside` [ZDCChat startChat:^(ZDCConfig *config) {}` block. But unfortunately that message is not showing on my chat UI. Can you help me. Thank you.

**Comment by mathewcropper** [comment]
Hi @ajumalebrahim. Before you try to send the message, are you checking the status of the connection to make sure it's fully established? It's mentioned [briefly in the docs](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/sessionapi#sending-a-message) that this will only work when the connection is in place. You can find out more about the various events you can listen for [here](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/sessionapi#events).

Does that help solve this for you, or is there something more to it?

**Comment by ajumalebrahim** [comment]
@mathewcropper  thank you.
I added `[[ZDCChatAPI instance] addObserver:self forConnectionEvents:@selector(connectionStateUpdated)];` and  in my connectionstateupdated method, i am checking the status of connection and if connects i send the message like this 
`+ (void)connectionStateUpdated {
    ZDCConnectionStatus status = [[ZDCChatAPI instance] connectionStatus];
    if (status == ZDCConnectionStatusConnected) {
        [[ZDCChatAPI instance] sendChatMessage:@"A test message 0"];
    }
}`

And it works. many thanks.

**Comment by mathewcropper** [comment]
Fantastic! Glad I could help.
