### ISSUE TITLE
Email transcript is missing subject noun

### ISSUE THREAD

**Issue by seansu4you87** [zendesk/zendesk_sdk_chat_ios#54]
When the emailed transcript is sent, it has a subject line of `Your chat transcript with` and cuts off the actual company name.  I'm expecting something like `Your chat transcript with [COMPANY NAME]`.

**Comment by tecknut** [comment]
@seansu4you87 The subject of the email transcript is not set on the client. The transcript is sent from the Zopim back end. 

Can you try testing with a chat on the web client and see if the email transcript sent by that is also missing the company name?

Thanks

**Comment by baz8080** [comment]
@seansu4you87 I'm going to close this as we haven't heard back from you in a while. Please reopen if the issue is persisting.
