### ISSUE TITLE
Push versions to CocoaPods

### ISSUE THREAD

**Issue by rsaunders100** [zendesk/zendesk_sdk_chat_ios#55]
This is essentially a duplicate of this issue for the chat SDK.
https://github.com/zendesk/zendesk_sdk_ios/issues/61

I could not see a listing of this pod on cocopods.org

https://cocoapods.org/?q=chat

Every other library pushes to the Cocoapods Trunk.  It would be easier to use your library if you did the same.

**Comment by RonanMcH** [comment]
Hi @rsaunders100 ,
The Zendesk Chat SDK has now been pushed to the cocoapods trunk. It is listed under ZDCChat.
Thanks for bringing it to our attention,
Ronan

**Comment by brendan-fahy** [comment]
Closing this ticket as the SDK has been pushed to CocoaPods.
