### ISSUE TITLE
How many MB does this add to the overall IPA size?

### ISSUE THREAD

**Issue by rsaunders100** [zendesk/zendesk_sdk_chat_ios#56]
Since this is not listed on https://cocoapods.org its is not easy to tell how big your SDK is.  Can you please list it in the documentation (if it is not already there?)

**Comment by RonanMcH** [comment]
Hi @rsaunders100,
The Chat SDK is now push to the cocoapods trunk which lists how big the SDK is.
Thanks,
Ronan.

**Comment by RonanMcH** [comment]
Hi @rsaunders100,
The footprint of the Zendesk Chat SDK compared to application without the SDK is 304KB, when archived for the iPhone 6s. We will be updating our docs once we have done a more comprehensive sweep of the impact on different devices.
Ronan,
