### ISSUE TITLE
Help please!!!

### ISSUE THREAD

**Issue by orbita256** [zendesk/zendesk_sdk_chat_ios#57]
Hello!
How to send image?
I'm use [[ZDCChat instance].session uploadFileWithData:imageData name:@"imageUpload.png"];
But nothing happens
[[ZDCChat instance].session.dataSource lastChatMessage]; returns nothing
What i'm doing wrong?

AND when i'm send message   [[ZDCChat instance].session sendChatMessage:msg];
in  [[ZDCChat instance].session.dataSource lastChatMessage];
I get two of the same event with two identical messages

**Comment by baz8080** [comment]
@orbita256 sorry for the delay - we missed this one.

1) Which plan are you on. We don't support file sending on the Lite plan. We're currently working on handling that better

2) `[[ZDCChat instance].session.dataSource lastChatMessage]; ` will return a message if one has already been sent. Can you share the code snippet where you're using it please?

3) Could you share some code snippets which illustrates the issue please?

**Comment by baz8080** [comment]
@orbita256 I'm going to close this, but please reopen if you would like to work on it further.
