### ISSUE TITLE
iOS App crashes when chat operator has "invisible" status and starts to write any message to user

### ISSUE THREAD

**Issue by piotr-dudek** [zendesk/zendesk_sdk_chat_ios#58]
Hi.
I'm using current version of Zopim Mobile SDK and I ran into following issue:

Step to reproduce situation:
1. As Chat Operator set "Online" status
2. As user enter the chat and send any message
3. As Chat Operator read the message and then change your status to "Invisible"
4. As Chat Operator send any message to the user 
5. As user wait for "There are no agents currently online" information
6. As Chat Operator start typing

Result: App crashes

`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (3) must be equal to the number of rows contained in that section before the update (3), plus or minus the number of rows inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).'`

This issue looks similar to [#40](https://github.com/zendesk/zendesk_sdk_chat_ios/issues/40)
Scenario might not be common but I can imagine where chat operator forgets to switch his status back to "Online" and starts typing in the message window.

I'm able to reproduce this issue in a clean xcode project containing only the ZDCChat.

**Comment by RonanMcH** [comment]
Hi @piotr-dudek ,
Thanks for making us aware of this bug. We have been able to reproduce it and we are currently working on a fix for it.
Ronan.

**Comment by oarrabi** [comment]
Hello @piotr-dudek 

We just released `ZDCChat` version 1.2.0.1 which has a fix to this issue.
Please check it out and let us know.

Thanks!

**Comment by oarrabi** [comment]
I will close this issue now, if it stills persist, please don't hesitate to reopen it.
