### ISSUE TITLE
Any notification about new message

### ISSUE THREAD

**Issue by stephenkopylov** [zendesk/zendesk_sdk_chat_ios#59]
Hello, our company use your support platform and ZDCChat framework in our ios app. 
So, we need to notify user when support guy write something to him.
Do you have any NSNotification or block that calls when user received incoming message?

**Comment by tecknut** [comment]
He @stephenkopylov, you can register for chat events with the following method.

https://github.com/zendesk/zendesk_sdk_chat_ios/blob/master/ZDCChat.framework/Versions/A/Headers/ZDCChatSession.h#L228

Let us know if this works for you.

Thanks,

Alan

**Comment by stephenkopylov** [comment]
Hello again. 
So, I tried to observe Connection Events with adding this code:
`[self.currentChat.session addObserver:self forConnectionEvents:@selector(onConnectionEvent:)];`

In onConnectionEvent method I wrote this code:
`- (void)onConnectionEvent:(NSNotification *)event
{    
    NSLog(@"event name = %@", event.name);
}`

Then, I started a small conversation with support guy (send and recieve some messages) and saw only one message in log:
`2016-02-21 16:11:22.608 AppName[575:116273] event name = zdchat.connection`

So. observing works, but it don't post message events.

So, can you add sone incoming message tracking? 

Thanks in advance!

Stephen.

**Comment by RonanMcH** [comment]
Hi @stephenkopylov,
Currently notifications for incoming agent messages is not available but I have made our product manager aware of this feature request and it will be put on our roadmap going forward. Unfortunately I can't give a timeline on this.
Thanks for your input,
Ronan.

**Comment by stephenkopylov** [comment]
Okay, we'll wait for it =)
But maybe you have some public property, that contains total number of all messages, or array with all messages? 
If yes, I can write a logic to understand that message was received.

**Comment by RonanMcH** [comment]
Hi @stephenkopylov,
Yes if you register for chat events using this code snippet:
```
[[[ZDCChat instance].session dataSource] addObserver:self forChatLogEvents:@selector(chatLog)];
```
This following code snippet will give you an array of the chat events.
```
- (void) chatLog {
NSArray *chatLogArray = [[[ZDCChat instance].session dataSource] livechatLog];
}
```
That array will contain `ZDCChatEvent` objects which contain the `message` property.
This notification may be posted many times on the life cycle of a chat.
Hope this helps,
Ronan.

**Comment by tecknut** [comment]
Hey @stephenkopylov have you had any luck with the `ZDCChatEvent`'s ? Have you been able to use the events to achieve what you want?

**Comment by baz8080** [comment]
Going to close this issue for now. Feel free to reopen it :)
