### ISSUE TITLE
End chat notification

### ISSUE THREAD

**Issue by capecrawler** [zendesk/zendesk_sdk_chat_ios#60]
How can I determine if the user ended the chat by pressing the end button?

**Comment by StevenDiviney** [comment]
@capecrawler 
You can listen for connection events as described here: https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/sessionapi#listening-for-connection-events

When the user ends a chat that chat connection returns to the initialized state, ZDCConnectionStatusUninitialized.

The chat starts out in this state so you may have take that into account.

**Comment by tecknut** [comment]
Hey @capecrawler has this solved your issue?

**Comment by capecrawler** [comment]
Hi @StevenDiviney,

I actually was using it already and checking for ZDCConnectionStatusUninitialized before. I'm glad I was on the right path. Thanks!

@tecknut, yup. Thank you also.
