### ISSUE TITLE
ZDCChat pod and Swift project: No such module 'ZDCChat'

### ISSUE THREAD

**Issue by Dodig** [zendesk/zendesk_sdk_chat_ios#61]
Hi,

I am trying to integrate your ZDCChat pod in my Swift project and I have this error:
![image](https://cloud.githubusercontent.com/assets/15231216/13245235/258e83dc-da0c-11e5-863b-2f3d05476fa2.png)

My configuration:
- CocoaPods 0.39.0
- Xcode 7.2.1 (7C1002)
- Swift 2.1

Here my Podfile:
![image](https://cloud.githubusercontent.com/assets/15231216/13245258/48e4ecea-da0c-11e5-95e2-f49341e6eff8.png)

Your pod is it compatible with Swift projects?
Do you have a Swift version of your pod?
Why your pod is so big? (31.1MB)

**Comment by oarrabi** [comment]
Hello @Dodig,

Sorry for the inconvenience, chat SDK is not a module at the moment and cannot be used with `import` or `@import`. We are planning to ship a modular framework in the next release.

However, you still can use it in swift using modular header import. Would it be possible for you to import `ZDCChat` using modular header instead?

**Comment by Dodig** [comment]
The issue is not only the ZDCChat as a module. It's also the size of your framework (31.1MB) it's two time the size of my application :disappointed:

**Comment by Dodig** [comment]
Do you have a date for the next release?

**Comment by oarrabi** [comment]
Hello @Dodig,

We still don't have a release date fixed for Chat SDK, however, it won't be too long.

As for the size, the (31.1 MB) is the size of the library including all the symbols and objects. Also, a big chunk of that size is the LLVM bitcode section. Embedding `ZDCChat` in an app will not incur a 30+ MB increase.

On one integration the increase in size was 304kb https://github.com/zendesk/zendesk_sdk_chat_ios/issues/56

Can you try to use it and let me know?

**Comment by Dodig** [comment]
Ok 304kb is acceptable 
I can try...

**Comment by baz8080** [comment]
@Dodig sounds good. I'll close off this issue. If you need anything else just let us know.

**Comment by Dodig** [comment]
Integration is done
I hope with the next release we will have a better support of Swift project
