### ISSUE TITLE
How I can hide the "Back" button when the button "End chat" is displayed?

### ISSUE THREAD

**Issue by Dodig** [zendesk/zendesk_sdk_chat_ios#62]
Hi,
We need to customise the interface:
When the button "End chat" is displayed we want to hide the button "Back" to force the user to finish the session. 
How we can do that?

**Comment by oarrabi** [comment]
Hello, @Dodig,

You can achieve that by calling this:
In Swift.
```swift
ZDCChat.startChat {....}
ZDCChat.instance().chatViewController.navigationItem.hidesBackButton = true
```

In objective c
```objc
[ZDCChat startChat:...]
[ZDCChat instance].chatViewController.navigationItem.hidesBackButton = YES;
```

Is that solving your issue?

**Comment by Dodig** [comment]
The idea is good :smile: 
but with no effect on the interface :disappointed:

**Comment by Dodig** [comment]
I found it! :smile: 

```swift
  func zopimConnectionStateUpdated() {
    let lStatus = ZDCChat.instance().session.status()
    let lChatViewController = ZDCChat.instance().chatViewController
    
    if lChatViewController != nil && lStatus == .Connected {
      lChatViewController.navigationItem.setLeftBarButtonItem(UIBarButtonItem(), animated: false)
    }
  }

  func menuSupport() {
    ZDCChat.startChat {
      (pSession:ZDCSessionConfig!) -> Void in

      pSession.emailTranscriptAction = .NeverSend

      dispatch_async(dispatch_get_main_queue()) {
        ZDCChat.instance().session.addObserver(self, forConnectionEvents: "zopimConnectionStateUpdated")
      }
    }
  }
```

**Comment by mattk90** [comment]
Is it also possible to hide the "End Chat Button? I want them to automatically start a chat when they tap in my Tab Bar on the icon and don't give them the possibility of ending the chat.

**Comment by ralubenea** [comment]
@mattk90 did you found a solution to your question? I would like to do that too.

**Comment by Lawati97** [comment]
@mattk90 and @ralubenea did you guys find the solution for that
