### ISSUE TITLE
ZDCFormCellMessage Insets does not match and color does not apply 

### ISSUE THREAD

**Issue by eikebartels** [zendesk/zendesk_sdk_chat_ios#65]
The text insets for ZDCFormCellMessage does not match. 

I would suggest to reset the text container inset for the testView 
`.textContainerInset = UIEdgeInsetsZero;`

Also setTextColor does not apply for the placeholder label 

<img width="362" alt="screen shot 2016-03-09 at 17 16 26" src="https://cloud.githubusercontent.com/assets/767979/13641929/bba3d9ca-e61a-11e5-9885-64796fee04db.png">

**Comment by RonanMcH** [comment]
Hi @eikebartels ,
I am struggling to recreate this. Can you tell us what device and iOS version you are running this on and we recreate and fix it?
Thanks,
Ronan.

**Comment by RonanMcH** [comment]
Hi @eikebartels ,
I just tested the `setTextColor` appearance selector and you are correct, it is not setting the text color for certain cells. I shall log this error and it will be fixed in our next release. Unfortunately, I cannot give a date on when this will be.
Thanks,
Ronan.

**Comment by eikebartels** [comment]
Hi @RonanMcH 
Thanks for that.

**Comment by oarrabi** [comment]
Hello @eikebartels,

I was able to reproduce this issue, thanks for contacting us.
I created an internal bug to track the inset issue. I will keep this issue open and update you once its fixed.

Thanks

**Comment by oarrabi** [comment]
Hello @eikebartels,

We just released `ZDCChat` version 1.2.1.1 which has a fix to this issue.
Please check it out and let us know.

Thanks,
Omar...

**Comment by oarrabi** [comment]
I am going to close this for now, if you are still experiencing the issue, please feel free to reopen it
