### ISSUE TITLE
Not able to override PreChatDataRequirements 

### ISSUE THREAD

**Issue by eikebartels** [zendesk/zendesk_sdk_chat_ios#68]
It seems like, that once the preChatDataRequirements are defined there is no way to override them. Please see code snippet below. 

A case would be. 
- User want to contact the support 
- User see the name, email and message field
- User does not fill it out 
- User logged in 
- User want to contact the support 
- User are still ask for name, email and message even if I set it to `ZDCPreChatDataNotRequired` 

> // ZDCPreChatDataNotRequired - we will use this data if known but we will not ask for it

```
    [ZDCChat startChat:^(ZDCSessionConfig *config) {
        config.emailTranscriptAction = ZDCEmailTranscriptActionNeverSend;
        
        if (![Customer sharedInstance].isLoggedIn) {
            config.preChatDataRequirements.name = ZDCPreChatDataRequiredEditable;
            config.preChatDataRequirements.email = ZDCPreChatDataRequiredEditable;
            config.preChatDataRequirements.message = ZDCPreChatDataRequiredEditable;
        }else {
            config.preChatDataRequirements.name = ZDCPreChatDataNotRequired;
            config.preChatDataRequirements.email = ZDCPreChatDataNotRequired;
            config.preChatDataRequirements.message = ZDCPreChatDataNotRequired;
            
        }
    }];
```

**Comment by RonanMcH** [comment]
Hi @eikebartels ,
I have re-implemented the code you have pasted and have not been able to replicate what happens in your description.  I have found that the `preChatDataRequirements` do reset. Can you check that your `ifelse` statement works as expected by inserting a brakepoint?
Thanks,
Ronan.

**Comment by eikebartels** [comment]
@RonanMcH you are right the values do reset. But the UI does not change. 

1. Works like expected 
- ZDCPreChatDataNotRequired was set 
- switch to ZDCPreChatDataRequiredEditable
--> UI get updated like expected 

2. Works not like expected 
- ZDCPreChatDataRequiredEditable was set 
- switch to ZDCPreChatDataNotRequired
--> UI don't get updated

**Comment by RonanMcH** [comment]
Hi @eikebartels ,
I am still struggling to recreate this so I have a UI with just a button called `openChat`. `openChat` executes the above if statement you posted.
1. run app.
2. press `openChat`.
3. `config.preChatDataRequirement` are set to `ZDCPreChatDataRequiredEditable`.
4. The prechat form is displayed with textfileds for name, email and message.
5. I don't set any and I press `back` button in UI.
6. press `openChat` again
7. `config.preChatDataRequirement` are set to `ZDCPreChatDataNotRequired`.
8. The chat view is displayed as expected.

Is your flow different to this? 
Thanks,
Ronan.

**Comment by eikebartels** [comment]
Ah I see. I assume that you are doing something more then just calling the function `minimiseChat` in `[ZDCChat instance]`?

The issue happens, when I override the back button with a customised one. 

`UIBarButtonItem * bt = [[UIBarButtonItem alloc] initWithImage:[UIImage imageNamed:@"close_icon"] style:UIBarButtonItemStylePlain target:[ZDCChat instance] action:@selector(minimiseChat)];`

Can you confirm, that this issue happens when you call the `minimiseChat` directly?

**Comment by oarrabi** [comment]
Hello @eikebartels,

The `preChatDataRequirements` can only be changed when the chat is started, so if you dont end the chat. In your case, since you are using `minimiseChat` the new settings wont be applied.

Is there a reason for not using `endChat`?

**Comment by oarrabi** [comment]
I will close this issue now, if it stills persist, please don't hesitate to reopen it.
