### ISSUE TITLE
Use of [UINavigationBar appearance] for styling ZDCRatingCell

### ISSUE THREAD

**Issue by eikebartels** [zendesk/zendesk_sdk_chat_ios#69]
The current implementation used `[UINavigationBar appearance]` to style the comment cell. 
This is totally unsuitable and can destroy my app styling. 

To be consistent it should be something like 

```
[[ZDCRatingCell appearance] setBubbleInsets:[NSValue valueWithUIEdgeInsets:visitorBubbleInsets]];
    [[ZDCRatingCell appearance] setTextInsets:[NSValue valueWithUIEdgeInsets:bubbleTextInsets]];
    [[ZDCRatingCell appearance] setBubbleBorderColor:visitorBubbleColor];
    [[ZDCRatingCell appearance] setBubbleColor:visitorBubbleColor];
    [[ZDCRatingCell appearance] setBubbleCornerRadius:@(bubbleCornerRadius)];
....

```
<img width="193" alt="screen shot 2016-03-10 at 10 27 54" src="https://cloud.githubusercontent.com/assets/767979/13665044/c77fcaa2-e6aa-11e5-897d-fbe4e558eb45.png">

**Comment by RonanMcH** [comment]
Hi @eikebartels ,
It is true we get the navigation bar color but it is cuztomizable. The appearance selectors that allow you to customize this cell type are in its super class which is `ZDCChatVisitorChatCell.h` so have a look in that class.
A few of the selectors are:

```
[[ZDCRatingCell appearance] setBubbleColor:value];
[[ZDCRatingCell appearance] setBubbleInsets:value];
[[ZDCRatingCell appearance] setBubbleCornerRadius:value];
```
and there are lots of others.
Hope this helps,
Ronan.

**Comment by eikebartels** [comment]
Hi @RonanMcH , 

ah I see. Thanks for the infos. 
It would be helpful to update the example code with this infos. 

In additional I would like to customise the "Leave comment.." button independent from the bubble. I think this is not possible for now, right?

**Comment by RonanMcH** [comment]
Hi @eikebartels ,
That's a fair point about including some examples, I'll commit some example to the sample app now and they'll be there when we release.  
In relation to the "Leave comment.." button, you are right it is customizable independent from the bubble. I will log your request to have an appearance selector for this text and keep you updated on it in this issue.
Regards,
Ronan.

**Comment by ndobri** [comment]
@eikebartels this was added in [Chat SDK 1.3](https://github.com/zendesk/zendesk_sdk_chat_ios/releases/tag/1.3.0.1) and you can use: `    [[ZDCRatingCell appearance] setLeaveCommentTitleColor: [UIColor yellowColor]];` to set the comment button color.
