### ISSUE TITLE
ZDCLoadingErrorView button hidden on small devices 

### ISSUE THREAD

**Issue by eikebartels** [zendesk/zendesk_sdk_chat_ios#71]
If I set a customer icon image which is bigger then the default one, the button "leave message" is hidden. 

I would suggest to use NSLayoutConstraints and centre the content area independent from the image size.

![simulator screen shot 15 mar 2016 11 29 54](https://cloud.githubusercontent.com/assets/767979/13774886/a9a178d2-eaa1-11e5-8a9e-2abef35b7b4d.png)

**Comment by baz8080** [comment]
@eikebartels Thanks for reporting the issue. I've tracked it internally.

**Comment by eikebartels** [comment]
Hey @baz8080, when do you think will the issue be solved?

**Comment by baz8080** [comment]
closing the issue because of its age. We're actively working on Chat SDK V2 which will not be subject to these kinds of layout issues.
