### ISSUE TITLE
Cannot translate field name

### ISSUE THREAD

**Issue by thekingbk90** [zendesk/zendesk_sdk_chat_ios#73]
Name
Email address
Phone number
Message

I cannot translate these titles.
Are there any ways for translating without the fixed Localizable.strings file?

**Comment by tecknut** [comment]
Can you explain what you want to do?

It is possible to change the translation for these titles. [These docs describe how to do this](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/customization#strings-and-localization)

**Comment by RonanMcH** [comment]
Hi @thekingbk90 ,
Since we haven't heard from you in a while, I'm going to tentatively close this issue. Feel free to reopen if you're still having trouble with translations. 
Thanks,
Ronan.
