### ISSUE TITLE
"No newline at end of file" warning in ZDCEmailTranscriptAction.h

### ISSUE THREAD

**Issue by dangochi** [zendesk/zendesk_sdk_chat_ios#74]
I'm seeing this warning in Xcode after updating to version 1.2.0.1 of the SDK (from 1.1.1). Super minor issue, but I'm sure someone else has noticed it as well.

**Comment by oarrabi** [comment]
Hello @dangochi,

Yep, I can see this warning too, I just fixed it in the SDK and will be shipped in the next release.
Thanks for reporting this :)

**Comment by oarrabi** [comment]
Hello @dangochi,

We just released `ZDCChat` version 1.2.1.1 which has a fix to this issue.
Please check it out and let us know.

Thanks,
Omar...

**Comment by dangochi** [comment]
Thanks @oarrabi, looks good to me. 👍
