### ISSUE TITLE
missing photo button after update

### ISSUE THREAD

**Issue by tonezone6** [zendesk/zendesk_sdk_chat_ios#75]
There is no photo btn in the text entry area using swift

**Comment by RonanMcH** [comment]
Hi @tonezone6 ,
I have done a quick swift integration and have not managed to recreate this issue.  The photo button is present in the chat view.  The button will disappear if file sending is disabled via the Zopim dashboard or if you are on a price that does not allow file sending.  Can you check that you on a plan that allows file sending? The feature comparison for the different plans is detailed [here](https://www.zopim.com/pricing/).
Thanks,
Ronan.

**Comment by tonezone6** [comment]
Now i'm in trial period (12 days remaining - "the restrictions below will be applied after your trial ends") just for testing. Intersting fact, if i downgrade to ZDCChat v1.1.3 photo button reappears.

![screen shot 2016-04-06 at 15 08 27](https://cloud.githubusercontent.com/assets/11317885/14316081/b016e16a-fc09-11e5-80d1-b54e812082cc.png)
![screen shot 2016-04-06 at 15 06 44](https://cloud.githubusercontent.com/assets/11317885/14316080/b012e77c-fc09-11e5-9ca9-b1f9da5a0c1e.png)

**Comment by RonanMcH** [comment]
Hi @tonezone6 ,
Just check that file sending is enabled on the zopim dashboard as shown:
<img width="1210" alt="screen shot 2016-04-06 at 13 18 46" src="https://cloud.githubusercontent.com/assets/12997923/14316304/37cdd056-fbfa-11e5-90b0-9653d60cb304.png">
Thanks,
Ronan.

**Comment by tonezone6** [comment]
File sending was on but to "Sharing is limited...". Had to change to "Allow PDF ...", and to check disclaimer but now it's working.
10x :)
