### ISSUE TITLE
How to customize UI styling in Swift?

### ISSUE THREAD

**Issue by andrew-buksha** [zendesk/zendesk_sdk_chat_ios#77]
In Objective-C used UI_APPEARANCE_SELECTOR to customize chat UI, so if I want to change the color of message bubble, I'd use:
[[ZDCVisitorChatCell appearance] setBubbleColor:[ZDUUtil navBarTintColor]];
But on Swift I cannot use
ZDCVisitorChatCell.appearance().bubbleColor = *SomeColor*
How would I change styling in Swift?

**Comment by RonanMcH** [comment]
Hi @andrew-buksha ,
I was able to cuztomize the chat bubble color in Swift by using:
```
ZDCVisitorChatCell.appearance().bubbleColor = ZDUUtil.navBarTintColor()
```
Can you explain the problem more? Is it not compiling for you in your project or is the color not getting set to the chat bubble when you run it?
Thanks,
Ronan.

**Comment by RonanMcH** [comment]
Hi @andrew-buksha ,
As we haven't heard from you in a while, I am going to tentatively close this issue.  Please feel free to reopen this issue if you're still having issues translating our styling API from Objective-C to Swift.
Thanks,
Ronan.
