### ISSUE TITLE
crash after second opening

### ISSUE THREAD

**Issue by oleksiivinogradov** [zendesk/zendesk_sdk_chat_ios#8]
Hi
while integration i found crash on iOS 8:

libobjc.A.dylib`objc_msgSend + 16, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
    frame #0: 0x0000000194e8fbd0 libobjc.A.dylib`objc_msgSend + 16
    frame #1: 0x0000000183535458 CoreFoundation`CFRelease + 524
    frame #2: 0x000000018353d538 CoreFoundation`-[__NSArrayI dealloc] + 88
    frame #3: 0x0000000194e95724 libobjc.A.dylib`(anonymous namespace)::AutoreleasePoolPage::pop(void*) + 564
    frame #4: 0x0000000183539074 CoreFoundation`_CFAutoreleasePoolPop + 28
    frame #5: 0x000000018360d8a8 CoreFoundation`__CFRunLoopRun + 1500
    frame #6: 0x00000001835392d4 CoreFoundation`CFRunLoopRunSpecific + 396
    frame #7: 0x000000018cd4f6fc GraphicsServices`GSEventRunModal + 168
    frame #8: 0x00000001880fefac UIKit`UIApplicationMain + 1488
  * frame #9: 0x00000001000e9a30 CallsFreeCalls`main(argc=1, argv=0x000000016fd1f9c0) + 152 at main.m:28
    frame #10: 0x00000001954faa08 libdyld.dylib`start + 4
(
after i disable ur framework crash was gone.

looks like memory management not correct inside. i can't include it in production while u don't fix it
first version has no crash
Alex

**Comment by grahamcruse** [comment]
Hi Alex,

Can you provide detailed steps on how to obtain this crash using the sample app? I've tried numerous combinations of starting and ending chats, backgrounding/foregrounding the app and minimising the chat but have not succeeded in generating a crash.

Thanks

Graham

**Comment by oleksiivinogradov** [comment]
open and close than open
i’m using storyboard - try from there
------ 
Oleksii Vynogradov 
founder and CEO

IXC Global Wholesale Inc.
http://www.cfc.io <http://www.cfc.io/>

440 Wolfe Rd
Sunnyvale CA 94085
United States
Work:   +1 (786) 573 8717
Mobile: +1 (408) 439-1408
skype: oleksiivinogradov

**Comment by grahamcruse** [comment]
Closing; resolved via Zendesk ticket.
