### ISSUE TITLE
Getting problem in updating navigation title of screen opened via overlay. Any Solution?

### ISSUE THREAD

**Issue by bhallamohit** [zendesk/zendesk_sdk_chat_ios#80]
I have  "1234" title on my ViewController and when i open chat via overlay it shows "chat" with white navigation background color.

**Comment by oarrabi** [comment]
Hello @bhallamohit 

If you want to change the chat title in the chat view controller, you need to edit "ios.ZDCChat.title" localization key.

For more info check this section on our developer portal 
https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/customization#strings-and-localization

Thanks,

**Comment by bhallamohit** [comment]
Hello @oarrabi 

Thnx for providing solution..
