### ISSUE TITLE
Save on image space by using template images

### ISSUE THREAD

**Issue by rsaunders100** [zendesk/zendesk_sdk_chat_ios#84]
It seems you can save 25kb of library size by deleting your gray images and instead using the white images as template images.

![screen shot 2016-05-18 at 11 13 54](https://cloud.githubusercontent.com/assets/555546/15355284/b158d3fc-1ce9-11e6-9556-fecf94966bd4.png)

```
UIImage *image = [UIImage imageNamed:@"ZDCChatThumbDownWhite"];
UIImage *templateImage = [image imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate];
imageView.image = templateImage;
imageView.tintColor = [UIColor colorWithWhite:0.5 alpha:1.0];
```

**Comment by ndobri** [comment]
Good point, thanks! We've added this to the backlog and will update this issue once released.

**Comment by jstheoriginal** [comment]
Also, allowing the setting of the image view's tint color using the appearance() api would then allow the images to being any color.

**Comment by baz8080** [comment]
I'm going to close this one for now. We have this tracked internally. We now take [feature requests in our forum](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs) rather than GitHub.
