### ISSUE TITLE
Set color of the Send button text

### ISSUE THREAD

**Issue by jstheoriginal** [zendesk/zendesk_sdk_chat_ios#86]
It doesn't seem to be possible to set the color of the Send button text. Am I missing it? Or does it get set in some other way? Thanks in advance.

**Comment by jstheoriginal** [comment]
More information for you...This is how it currently looks in the app: 
![send button image missing](https://cloud.githubusercontent.com/assets/5117473/15581704/1f431a7c-2333-11e6-8fc2-258545cc27d4.png)

It doesn't look like it's rendering correctly (is the image missing? It just looks like Send text that's a blue button)...and I haven't set the Send image to nil...I'm not doing anything with the Send image.

**Comment by oarrabi** [comment]
Hello @jstheoriginal 

Thats correct, at the moment there is no way to change the color of the send button. The only way to customize it is by setting an image using:
```
[[ZDCTextEntryView appearance] setSendButtonImage:@"SampleOverlayIcon"];
```

I logged an issue in our internal bug tracker to follow up with this issue, I will update you once that is addressed.

Thanks :)

**Comment by jstheoriginal** [comment]
Thanks @oarrabi 

In the screenshot I posted, is that how the Send button should appear when no appearance() properties are touched? i.e. out of the box look? Ours above doesn't look like how it does on the Zendesk iOS SDK site with the sample app image:

![Image from Zendesk Help Page](https://raw.githubusercontent.com/zendesk/mobile_sdk_chat_images/grahamcruse/intro/ios/1.0/ios_img03.png)

**Comment by mathewcropper** [comment]
Hi there. Me again. As with the update I just made to #88, this falls into the bucket of customisation options. We aren't planning to make any updates to this right now, and the solution that @oarrabi suggested is the one we would recommend. I'll mark this issue as closed on that basis.
