### ISSUE TITLE
Pre-Chat Form view jumps when Message box expands to allow more than 1 line of text

### ISSUE THREAD

**Issue by jstheoriginal** [zendesk/zendesk_sdk_chat_ios#87]
When I'm in the message text box on the pre-chat form, if i enter more than 1 line of text, as soon as the text box expands to allow more text, the entire screen does a jump as if the scroll view is flicked down.  Any ideas?

**Comment by brendan-fahy** [comment]
Hey @jstheoriginal, we haven't heard of this issue before, it's not something we've seen. Can you give us a gif or screen capture to illustrate it? Thanks.

**Comment by jstheoriginal** [comment]
@brendan-fahy here's a gif...it's not really high fps but it shows the jump.  http://g.recordit.co/eyt2mxGwwG.gif

**Comment by brendan-fahy** [comment]
Thanks for that @jstheoriginal. This component is going to be re-worked as part of an upcoming release, but for the moment unfortunately that issue will remain as it is. 
Sorry I can't offer a more helpful answer.

**Comment by jstheoriginal** [comment]
Sounds good!

**Comment by jstheoriginal** [comment]
I just tested the latest release on my iOS 10 device and it doesn't jump anymore when it goes to a newline on the message field of the pre-chat form. So I assume this is now fixed! 🎉

**Comment by mathewcropper** [comment]
Great news. Thanks for the update @jstheoriginal. I'll close this issue :)
