### ISSUE TITLE
Is it posible to set notes for visitors?

### ISSUE THREAD

**Issue by knolga** [zendesk/zendesk_sdk_chat_ios#90]
in javascript it is possible to add notes for visitor...is it possible to do the same thing in mobile app?
Thanks for advancement

**Comment by schlan** [comment]
Hi @knolga, at the moment we don't have support for notes. I'll add it as FR to our backlog. We'll keep you updated on this issue.

**Comment by sferik** [comment]
I’d also be interested to see this feature (for use at Instacart).

**Comment by mathewcropper** [comment]
@knolga @sferik Hi there. I'm Mat, and I'm the Product Manager for our SDKs. I'm wondering if you could share a little more about how you would use this feature if it existed? I'm struggling to see a compelling use case, and so best to ask you rather than guess!

**Comment by danieldabate** [comment]
@mathewcropper Hi Mathew! This would be useful to solve my issue #97

**Comment by sferik** [comment]
@mathewcropper I have the same use case as @danieldabate (custom user information). Specifically, I’d like the ability to add user-specific links that would be clickable in the chat interface.

**Comment by mathewcropper** [comment]
Thanks for your contributions, folks.

In terms of adding additional information to a chat session is concerned, the only fields available right now are for name, email, phone number, notes, and tags. We give you the ability to populate all of those, except for notes. I think this is a fair feature to request, and so I'll follow up on this. I can't promise when we will pick it up, as it doesn't fall into our current set of priorities, but I'll log and track it.

If any of you would be open to a chat for me to better understand your specific use case, let me know. I'll look you up and get in touch directly.

**Comment by danieldabate** [comment]
Hi Mathew, please contact me at ddabate@bluesmart.com, my use case is rather simple so I can explain it in an email for you.

**Comment by mathewcropper** [comment]
Thanks @danieldabate. I've updated your comment to remove the email address (so you don't get spammed). I'll be in touch.

**Comment by mathewcropper** [comment]
Folks, we just released v1.3.2.1 of the Chat SDK (Android and iOS) which adds the ability to set visitor notes. I thought you'd like to know!

* [Android release notes](https://developer.zendesk.com/embeddables/docs/android-chat-sdk/releasenotes#version-1.3.2.1)
* [iOS release notes](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/releasenotes#version-1.3.2.1)
