### ISSUE TITLE
Setting backgroundColor via .appearance() of Chat window doesn't work

### ISSUE THREAD

**Issue by jstheoriginal** [zendesk/zendesk_sdk_chat_ios#91]
With this line of code:
`ZDCChatView.appearance().backgroundColor = UIColor.lightGrayColor()`

I've also set:
`ZDCChatUI.appearance().backgroundColor = UIColor.lightGrayColor()`

the background color remains white. Is this the correct way to set the background color?

**Comment by RonanMcH** [comment]
Hi @jstheoriginal ,
The chat background is set with this line of code:
```
ZDCChatView.appearance().chatBackgroundColor = UIColor.lightGrayColor()
```
Thanks,
Ronan.

**Comment by RonanMcH** [comment]
Hi @jstheoriginal ,
Since we haven't heard from you in a while, I am going to tentatively close this issue. Please feel free to reopen this issue if you are still struggling to set the background color in a chat.
Thanks,
Ronan.

**Comment by rsahu34** [comment]
How to change the ChatViewController navigation bar title font and colour ?
