### ISSUE TITLE
Custom user information

### ISSUE THREAD

**Issue by danieldabate** [zendesk/zendesk_sdk_chat_ios#97]
Is it possible to add some custom information to the user apart from the name, email and phone number?  

If this is not supported, is there any workaround to have this information logged both in the Zopim chat and the Zendesk ticket created later? This information is important for our customer support team to resolve our user's issues.

Thanks!

**Comment by sferik** [comment]
I also have this use case. Specifically, I’d like the ability to add user-specific links that are clickable in the chat interface.

**Comment by mathewcropper** [comment]
Hi @danieldabate. I'm going to close this thread, and continue the conversation over in #90, if that's ok? They both amount to the same thing, and it'll be easier for us to keep an eye on a single issue 😄
