### ISSUE TITLE
Include separator lines in table view

### ISSUE THREAD

**Issue by matibzurovski** [zendesk/zendesk_sdk_chat_ios#98]
I am trying to style the table with the messages, removing the bubbles and including separator lines on the table so that messages can be distinguished. I have written the following code, but it creashes with an EXC_BAD_INSTRUTCION when reaching the first line:

```
ZDCChatView.appearance().table.separatorStyle = UITableViewCellSeparatorStyle.SingleLine
ZDCChatView.appearance().table.separatorColor =UIColor.redColor()
ZDCChatView.appearance().table.backgroundColor = UIColor.whiteColor()
```

The error message is:

> fatal error: unexpectedly found nil while unwrapping an Optional value

So I guess the table is nil and so it crashes. It is weird, as I can style the cells in the same place where this method is invoked.

I have downloaded the code sample and tried to reproduce this changes in Objective-C. It doesn't crash, but doesn't include the separator lines neither. Am I missing something? The code for Objective-C is the following.
```
[[ZDCChatView appearance] setChatBackgroundColor:[UIColor clearColor]];
[[[ZDCChatView appearance] table] setSeparatorStyle:UITableViewCellSeparatorStyleSingleLine];
[[[ZDCChatView appearance] table] setSeparatorColor:[UIColor blueColor]];
```

**Comment by oarrabi** [comment]
Hello @matibzurovski,

At the moment it's not possible to change the separator color. I logged an internal ticket to follow up with this issue. I will keep this issue open and update you once this is done.

Thanks for bringing this up :)

**Comment by matibzurovski** [comment]
Thanks for your answer @oarrabi 
I am having a similar problem with changing the "Send" button colour. Is that possible or am I facing the same situation here?

**Comment by ndobri** [comment]
@matibzurovski the issue for a similar question has already been opened. See #86 for details.

**Comment by matibzurovski** [comment]
Thanks @ndobri. Just another question that may solve my problems: I am OK with most of the UI your SDK provides for the chat service. However, there are some particular screens which I would like to totally change. Is it possible to just implement some of the screens and use the default ones for the rest of them? Lets say, I would like to overwrite `ZDCPreChatFormView` but use `ZDCChatView` as it is.

**Comment by StevenDiviney** [comment]
@matibzurovski We don't provide a way to only use individual screens. The SDK provides a standard flow. However in this case you could implement you own prechat form and pass that information to the SDK using `[ZDCChat updateVisitor:]` before calling `startChat:`

**Comment by matibzurovski** [comment]
@StevenDiviney I know how to update the visitor's info, but how would I display my own prechat form? Consider I want to use the rest of the screens provided by the SDK.

**Comment by StevenDiviney** [comment]
@matibzurovski Sorry if I misunderstood you, I thought you wanted to implement your own screens. Our UI is intended to be used as is, it is not intended to be subclassed or modified. Implementing your own view controllers is probably the easiest way.

**Comment by matibzurovski** [comment]
@StevenDiviney I get that, but I don't want to implement my view controllers for every screen, just for the pre chat form :)

**Comment by brendan-fahy** [comment]
Hi @matibzurovski, you can implement your own view controller for a pre chat form, and then use our UI for the chat screen. You would need to take the information from your pre chat form and update the visitor info with it, as Steven mentioned above, and then start a chat as normal. In that way you would only have to implement a view controller for pre chat form, not for every screen. Does that solve your issue? Let me know if I've misunderstood your goal here.

**Comment by matibzurovski** [comment]
Hi @brendan-fahy, thanks for answering. I guess I explained wrong all the time, sorry for that. What I do want to show is my own UI for the form displayed when there are no agents online.

**Comment by oarrabi** [comment]
Hello @matibzurovski,

I am afraid that at the moment we don't provide a way to implement your own UI for when no agents are online. You can customize the view that is presented by setting the appearance selectors values in `ZDCLoadingErrorView`. Bellow is the header file:

https://github.com/zendesk/zendesk_sdk_chat_ios/blob/master/ZDCChat.framework/Headers/ZDCLoadingErrorView.h#L53

Would that be enough for your case? Or you would like to have a totally different viewcontroller/view for when there aren't any online agents?

Thanks :)

**Comment by matibzurovski** [comment]
Hi @oarrabi, unfortunately I would need a totally different viewController, as I want to place a bigger icon (which would leave the actual buttons almost at the bottom of the screen) and change the size and border of the buttons. Thanks anyway!

**Comment by oarrabi** [comment]
Hello @matibzurovski,

No problem :), I just logged a ticket in our tracking system to add a feature to provide a different View/ViewController when no agents are online.
I will keep this issue open and update it when it is implemented.

Sorry for not being able to help more at this time.

**Comment by mathewcropper** [comment]
Hi. I'm Mat, the Product Manager for our SDKs. I'd like to give you an update on this.

I've reviewed the feature request, and this isn't something we are planning to build right now. For Chat SDK integrators who want to have a more custom user interface, it's possible to use the Chat API in the SDK (v1.3+) to build it. The out of the box UI is for a specific experience, and the feature you're requesting isn't one that we are planning to add to it.

I'll close this issue on that basis, with thanks for sharing your feedback. If you would like to share other ideas in future, the best place is in one of our Zendesk communities, where it will have a broader reach and discussion. I'd suggest either the [Zendesk SDKs community](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs) for feature requests specific to the SDK, or the [Product feedback community](https://support.zendesk.com/hc/en-us/community/topics/200132066-Product-feedback) for more general ideas.
